### ISSUE TITLE
NullPointerException Introduced by a breaking change

### ISSUE THREAD

**Issue by xiaofen9** [wala/WALA#1033]
Hi,

I find that WALA (4aa169c82fe61a08c8e83b9c0a908b254339bc80) throws NPE when parsing node.js programs, which is caused by this method
https://github.com/wala/WALA/blob/4aa169c82fe61a08c8e83b9c0a908b254339bc80/com.ibm.wala.cast.js.nodejs/src/main/java/com/ibm/wala/cast/js/nodejs/NodejsRequiredCoreModule.java#L92-L96
Further investigation points that https://github.com/wala/WALA/commit/7a029b7054e41107f13b7692ebf9b6c00124bd1c does not work with the above code (no core-modules is downloaded to resource/ )

I manually copy core-modules to com.ibm.wala.cast.js.nodejs/src/main/resources and now it works.

Please consider fixing it. thanks.

**Comment by msridhar** [comment]
Sorry for the trouble; this should be fixed on the master branch now.  Let me know if it would help to have a release cut with this fix included.
