### ISSUE TITLE
Several questions about the tutorial regarding to build JavaScript call graph

### ISSUE THREAD

**Issue by RichardHoOoOo** [wala/WALA#1040]
I have successfully built wala 1.5.7 by following this [tutorial](https://github.com/wala/WALA/wiki/Getting-Started). I'm now reading this [tutorial](https://github.com/wala/WALA/wiki/Getting_Started:JavaScript_frontend) but I found one paragraph is difficult to follow:
```
For legal reasons, you will need to obtain version 1.7R3 of Rhino from here and install it as js.jar in the lib/ directory of 
com.ibm.wala.cast.js.rhino. Running ant on com.ibm.wala.cast.js.rhino/build.xml should fetch the jar for you. Similarly, run ant 
on com.ibm.wala.cast.js/build.xml to fetch the Jericho and nu.validator HTML parsers, another required dependence.
```

May I ask 3 questions about it?

1. Where is the lib/ directory under com.ibm.wala.cast.js.rhino? Do I need to create it by myself?
2. Where is the com.ibm.wala.cast.js.rhino/build.xml? I couldn't find the xml file under com.ibm.wala.cast.js.rhino.
3. Also where is the com.ibm.wala.cast.js/build.xml?

Could you help me resolve my problems? I would really appreciate your help.

**Comment by msridhar** [comment]
@RichardHoOoOo my apologies, that page was very out of date.  I've updated the page now.  Long story short, getting set up with WALA's JS frontend is much easier now.  I recommend getting the jars from Maven Central, as indicated [here](https://github.com/wala/WALA/wiki/Getting_Started:JavaScript_frontend#getting-the-code).  There is no need to manually download Rhino, it will be downloaded automatically.  If you need more help let us know.

**Comment by RichardHoOoOo** [comment]
@msridhar Thanks a lot for your answer! Yes, now I can try the code. I randomly created some JavaScript files to test but in some cases WALA returns me with some errors. For example, if I use the [JSCallGraphDriver](https://github.com/wala/WALA-start/blob/master/src/main/java/com/ibm/wala/examples/drivers/JSCallGraphDriver.java) to build a call graph for the following JS code

```
foo((a) => {
  let b = "";
});
```

an exception with the following message will show

```
Exception in thread "main" com.ibm.wala.util.WalaException: front end errors:
error in test.js:
[SEVERE] missing ; before statement: test.js@2:   let b = "";
end of front end errors

at com.ibm.wala.cast.util.Util.checkForFrontEndErrors(Util.java:36)
at com.ibm.wala.examples.analysis.js.JSCallGraphBuilderUtil.makeCG(JSCallGraphBuilderUtil.java:223)
at com.ibm.wala.examples.analysis.js.JSCallGraphBuilderUtil.makeScriptCGBuilder(JSCallGraphBuilderUtil.java:92)
at com.ibm.wala.examples.analysis.js.JSCallGraphBuilderUtil.makeScriptCG(JSCallGraphBuilderUtil.java:147)
at com.ibm.wala.examples.analysis.js.JSCallGraphBuilderUtil.makeScriptCG(JSCallGraphBuilderUtil.java:138)
at com.ibm.wala.examples.drivers.JSCallGraphDriver.main(JSCallGraphDriver.java:29)
```

If I remove the `let` keyword like this 

```
foo((a) => {
  b = "";
});
```
The output seems correct
```
3 = invoke 2@1 exception:4
6 = invoke 5@3 exception:7
7 = invoke 9@7 11,12 exception:13
Call graph stats:
  Nodes: 108
  Edges: 107
  Methods: 4
  Bytecode Bytes: 0
```

Since `let` keyword is common in real cases, can WALA fix this issue or how can I work around it?

**Comment by msridhar** [comment]
Can you open a new issue on support of `let`?  That is separate from the tutorial issue.

**Comment by RichardHoOoOo** [comment]
@msridhar Sure, I have opened a new issue in #1044
