### ISSUE TITLE
Point Analysis and Slice

### ISSUE THREAD

**Issue by EdisonE3** [wala/WALA#1041]
Hello, recently I need to do point analysis and slice. However, I faced some problems. 
Firstly, for example, I have a program:
```java
int l1 = x.w.length();
int l2 = y.w.length();
```
Is there any way to help me to know whether x and y are same object?

Secondly, I have another program:
```java
public class Tmp {
    Parent parent = new Child();
    public void test() {
        parent.elementAt();
    }
}
```
After tring `makeZeroCFABuilder`, `makeZeroOneCFABuilder` and `makeNObjBuilder`, I still can not get the exact type of parent which is Child. Is there any way to get the type of parent in function `test`?

**Comment by msridhar** [comment]
Sorry for the slow response.

> Hello, recently I need to do point analysis and slice. However, I faced some problems. Firstly, for example, I have a program:
> 
> ```java
> int l1 = x.w.length();
> int l2 = y.w.length();
> ```
> 
> Is there any way to help me to know whether x and y are same object?

Yes, you would query for the points-to set of `x` and `y` and see if those sets have a non-empty intersection.  You can get a `PointerAnalysis` object from a `CallGraphBuilder`.  Some more details on pointer analysis are here:

https://github.com/wala/WALA/wiki/Pointer-Analysis


> 
> Secondly, I have another program:
> 
> ```java
> public class Tmp {
>     Parent parent = new Child();
>     public void test() {
>         parent.elementAt();
>     }
> }
> ```
> 
> After tring `makeZeroCFABuilder`, `makeZeroOneCFABuilder` and `makeNObjBuilder`, I still can not get the exact type of parent which is Child. Is there any way to get the type of parent in function `test`?

I don't know if the pointer analysis on its own can make this determination.  Normally, it would compute the points-to set of the `parent` field of some `Tmp` object allocated somewhere in the program.  If you want to analyze this code on its own, you could build your own analysis of the `Tmp.<init>` method and look for field writes in that method.  But a local analysis may not be sufficient to prove what you want, as the `parent` field is not final.

**Comment by EdisonE3** [comment]
Thanks a lot!
