### ISSUE TITLE
if the instruction is not in the SSAInstructions, how can I get the line number of it?

### ISSUE THREAD

**Issue by Anditty** [wala/WALA#1048]
```java
 public static void main(String[] args) {
        String a = null;
        System.out.println(((String)a).length());
    }
```
Hello! I get a problem when I try to get the line number of a instruction, could you give me some advice to solve it?
I want to get the line number of this instruction: `String a = null;`;
but this instruction is not in the IR:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/71593976/141166373-657b7937-a03c-4f87-ad35-0ee2bba5d2c4.png">
So I can't use this way to get the answer : `node.getMethod().getLineNumber(((ShrikeBTMethod) node.getMethod()).getBytecodeIndex(instructions.iidex()))`
If there any way to get the line number? Thanks for your answer!!!

**Comment by msridhar** [comment]
@Anditty unfortunately there is no easy way to get that line number from the WALA IR.  WALA performs copy propagation when constructing the SSA IR, so some instructions that just copy values between variables or assign a variable to a constant are not represented.  I don't immediately have an alternate suggestion other than parsing the source code for these cases and looking for the initialization / copy to the relevant variable (I see that info that the variable name is `a` is still present in the IR).  Sorry!
