### ISSUE TITLE
Creating call graph for a javascript module

### ISSUE THREAD

**Issue by kal-purush** [wala/WALA#1049]
Hi,

I am trying to create a call graph of JavaScript modules. I can create a call graph for a single stand-alone javascript file but I need to create the call graph for multiple js files of a module/directory. I would really appreciate if anyone can let me know how I can get the call graph for multiple files/module. In case, the current version does not support this, I will be grateful if you can give some pointers to modify the code to generate a call graph for multiple files.

**Comment by msridhar** [comment]
Hi @kal-purush sorry the documentation isn't better on this.  Couple of questions:

* What exactly do you mean by modules?  Do you mean node.js modules?
* Which call graph construction algorithm would you like to use?  There are built-in standard pointer analysis algorithms, i.e., those described in the [correlation tracking paper](https://manu.sridharan.net/files/ECOOP12Correlation.pdf), and also the field-based or [approximate call graphs algorithm](https://manu.sridharan.net/files/ICSE-2013-Approximate.pdf).

Let me know what you're looking for and I can provide more details.

**Comment by msridhar** [comment]
Closing this out but feel free to follow up if there is still a question

**Comment by kal-purush** [comment]
@msridhar, Sorry to open the question after a long time.
To answer your question, yes, by module I meant node.js/javascript modules. 
_`Which call graph construction algorithm would you like to use? There are built-in standard pointer analysis algorithms, i.e., those described in the [correlation tracking paper](https://manu.sridharan.net/files/ECOOP12Correlation.pdf), and also the field-based or [approximate call graphs algorithm](https://manu.sridharan.net/files/ICSE-2013-Approximate.pdf).`_

any of them will, whatever default in WALA.

**Comment by msridhar** [comment]
We have some support for analyzing Node.js in the `com.ibm.wala.cast.js.nodejs` project. We don't have a Maven artifact for that module at the moment, so you'll have to build WALA from source. You can see how to call into the code by looking at the tests, e.g.:

https://github.com/wala/WALA/blob/master/com.ibm.wala.cast.js.nodejs/src/test/java/com/ibm/wala/cast/js/nodejs/test/NodejsRequireTargetSelectorResolveTest.java

This will use the pointer-analysis-based call graph algorithms.
