### ISSUE TITLE
Inter-procedure taint analysis for JavaScript

### ISSUE THREAD

**Issue by RichardHoOoOo** [wala/WALA#1050]
Hi,

I hope to use WALA to build a inter-procedure taint analysis for JavaScript. For example, considering the following two methods `foo` and `too`

```
1. function foo() {
2.    var i = source();
3.    too(i);
4. }

5. function too(j) {
6.    var k = j + 1;
7.    sink(k);
8. }
```

`foo` contains a variable `i` that is marked as a source at line 2. Then it is passed to `too` and affect the value of `k`, who is used at a sink point at line 7. In this example, if `i` is tainted, `k` should also be tainted because it depends on `i`.

How can I perform such an analysis with WALA? Specifically, how can I specify taint propagation rules (e.g., in a binary expression `z = x op y`, if `x` or `y` is tainted, `z` should be tainted) with WALA APIs? I have read some similar issues (e.g., #869) but it seems the example cannot be applied in my case.

Could you provide me with some suggestions or tutorials on JavaScript taint analysis? 

Thanks in advance!

**Comment by msridhar** [comment]
I don't have any particular suggestions or tutorials for JavaScript taint analysis.  My comments in #869 are the best I can do I think.  You would have to do some significant re-implementation or adaptation of code to build a JS taint analysis with WALA, but all the building blocks are there (call graphs, pointer analysis, inter-procedural data flow analysis).
