### ISSUE TITLE
The method is not in the call graph

### ISSUE THREAD

**Issue by Anditty** [wala/WALA#1067]
When I try to use ZeroOneContainerCFA algorithm to build my callgraph, I find that my method is not within the callgraph.

```java
IClassHierarchy cha = ClassHierarchyFactory.makeWithRoot(scope);
Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
AnalysisOptions options = new AnalysisOptions(scope, entrypoints);
CallGraphBuilder builder=Util.makeZeroOneContainerCFABuilder(options,cache,cha,scope);
CallGraph cg=builder.makeCallGraph(options,null);
```
 And I add this class to the `scope` file:
```java
public class Tmp {
    public void func(Student student){

    }
}
```
Then I traversed my `cg` and found that the method I wrote `func` was not in the result.

The reason why there is no method `func` in cg is that the parameter `Student`  of `func` is not added to the scope file (I only add the class `Tmp` to `scope` file). I would like to know if there is a way to make the `func` method appear in my cg even if class `Student` is not added to the scope file

**Comment by msridhar** [comment]
@Anditty it looks like for a dataflow-based call graph algorithm like ZeroOneContainerCFA, if there is no concrete type for an entrypoint parameter, a call to that entrypoint is not added to the fake root method; see here:

https://github.com/wala/WALA/blob/ddada31a57bafec8723263f3c602e414f6ac25d3/com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/Entrypoint.java#L164-L168

You could work around this by creating your own `Entrypoint` subclass that just passes `null` for entrypoint parameters that have no concrete types in the scope.  Or you can use `CHACallGraph`, which I don't think suffers from this issue (but will be more imprecise).
