### ISSUE TITLE
Find which place lambda function really execute

### ISSUE THREAD

**Issue by EdisonE3** [wala/WALA#1068]
Hi!
Recently I'm dealing with lambda function, however I meet a problem. For example, there is a program:
```java
public class Tmp {
    Parent parent = new Child();
    public void main(String[] args) {
        MathOperation addition = (int a, int b) -> a + b;
        Tmp tmp = new Tmp();
        System.out.println("10 + 5 = " + tmp.operate(10, 5, addition));
    }

    interface MathOperation {
        int operation(int a, int b);
    }

    private int operate(int a, int b, MathOperation mathOperation){
        return mathOperation.operation(a, b);
    }
}
```
The lambda function really execute in private function `operate`. Is there any way to find this information by using WALA?

**Comment by msridhar** [comment]
@EdisonE3 we should have support for lambdas in the dataflow-based call graph builders like 0-1-CFA or 0-1-Container-CFA.  What kind of call graph do you get for the example above?

**Comment by EdisonE3** [comment]
Thanks very much! I used CHA call graph, and I will try other call graph.

**Comment by msridhar** [comment]
Ok, great!  Another alternative for lambda support (which should work even with CHA call graph) is to run [Retrolambda](https://github.com/luontola/retrolambda) on the class files first, and then run WALA on the result.
