### ISSUE TITLE
Changes in JarFileModule lead to ill behaviour

### ISSUE THREAD

**Issue by mohrm** [wala/WALA#107]
Commit 73747cbb86df0c2448a4fd264556752ef73b3558 changed the implementation of JarFileModule dramatically and introduced a subtle error.

* Before this commit, JarStreamModule took a JarInputStream and read the class files directly from there.
* Commit 73747cbb86df0c2448a4fd264556752ef73b3558 made JarStreamModule inherit from JarInputStream. The JarInputStream it takes is not stored as a field anymore, but passed to the super constructor. This is where the problem comes in. JarInputStream's constructor takes an arbitrary input stream and assumes that it gets the zipped data from that stream. Consequently, JarStreamModule also makes this assumption now. But the constructor still takes a JarStreamModule, hence the data will be unzipped twice which leads to the problem that WALA cannot read class files in certain situations anymore, e.g. from a jar within a jar, or from a jar by using JarStreamModule.

I suggest to [change the constructor ](https://github.com/joana-team/WALA/commit/971c8c188d763ab6ea59b10e5ba4ec4c5d9f63f8) of JarStreamModule to accept any InputStreams. If I see correctly, the only place of WALA which needs to be adapted is [a place in FileProvider](https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/com/ibm/wala/util/io/FileProvider.java#L178): You only need to get rid of the outer JarInputStream. I think, this code is never executed anyway, since if it were actually used to construct a Module, WALA would crash while constructing the ClassHierarchy because it cannot load any classes.

**Comment by msridhar** [comment]
This is a bad bug; we really need to be able to read a jar from within a jar.  @juliandolby can we just revert the changes to JarFileModule from 73747cb?

**Comment by msridhar** [comment]
I assume this was fixed by #120
