### ISSUE TITLE
Is there any API to deal with line number of Kotlin inline function?

### ISSUE THREAD

**Issue by EdisonE3** [wala/WALA#1091]
Hello, recently I need to deal with kotlin bytecode. However I meet some problems about kotlin inline function. 
For example:
```java
1 fun main(args: Array<String>) {
2    foo("this is inline",::println)
3 }
4 
5 inline fun foo(str : String?, function :(String)-> Unit) {
6    function(str!!)
7 }
```
The line number of statements related to inline function is not correct. For example, if the error is happened in line 6 in source code, the line number in bytecode is line 8. 
But I find that there is debug info in bytecode like this:
```
  // compiled from: Test.kt
  // debug info: SMAP
Test.kt
Kotlin
*S Kotlin
*F
+ 1 Test.kt
TestKt
*L
1#1,7:1
6#1,2:8
*E
*S KotlinDebug
*F
+ 1 Test.kt
TestKt
*L
2#1,2:8
*E
```
With the help of these information we can find the corresponding inline function body and inline function callsite. 

Therefore I want to know is there any API to deal with line number of Kotlin inline function?

**Comment by msridhar** [comment]
There is no specific Kotlin support in WALA yet but this could be a great contribution. I think Shrike should be able to read whatever metadata is in the class file. So we could probably create a new API on top of that. Would you be interested in contributing? I'm happy to help guide.

**Comment by EdisonE3** [comment]
I am not sure I can finish it. 
But I'd like to learn how to use Shrike to analysis bytecode. Could you please give me some guide? 
Thanks a lot!

**Comment by msridhar** [comment]
@EdisonE3 this is the best guide on Shrike that we have available:

https://github.com/wala/WALA/wiki/Shrike

Beyond that, if you have specific questions, please let me know and I can try to answer.

**Comment by msridhar** [comment]
Closing this issue since the Kotlin question has been answered
