### ISSUE TITLE
Problem about condition branch Instruction in Android

### ISSUE THREAD

**Issue by EdisonE3** [wala/WALA#1092]
Hello, recently I use WALA to analysis apk, however, I meet a problem.
Here is the code in Android:
```java
if (name == null){
   name = "name";
}

return name;
```
And its corresponding byte code is:
```
    .registers 2

    .line 10
    iget-object v0, p0, Lcom/example/myapplication/Result;->name:Ljava/lang/String;

    if-nez v0, :cond_8

    .line 11
    const-string v0, "name"

    iput-object v0, p0, Lcom/example/myapplication/Result;->name:Ljava/lang/String;

    .line 14
    :cond_8
    iget-object v0, p0, Lcom/example/myapplication/Result;->name:Ljava/lang/String;

    return-object v0
```

When I use it translate to IR by using WALA, I find that the target index of condition branch instruction is -1:
```
conditional branch(ne, to iindex=-1) v2,v3:#0(line 10)
```

So how can I deal with this problem?

**Comment by msridhar** [comment]
Hrm, this looks like it might be a bug in the frontend that translates Dalvik to WALA IR.  Unfortunately I am not an expert on that code.  I think this is probably the relevant class:

https://github.com/wala/WALA/blob/master/com.ibm.wala.dalvik/src/main/java/com/ibm/wala/dalvik/ssa/DexSSABuilder.java

@EdisonE3 if you have any time to debug and diagnose, that would be helpful.  I don't know when I will get to this.  I am happy to try to answer questions about the code if you dig further.

**Comment by EdisonE3** [comment]
I find that the target of branch condition is always -1 according to the code at line 648:
```java
insts.ConditionalBranchInstruction(
                  getCurrentInstructionIndex(), instruction.getOperator(), t, val1, val2, -1));
```

So I have another question:
I find that basic block of the branch condition instruction is BB2:
```
BB2
1   conditional branch(ne, to iindex=-1) v2,v3:#0(line 10)
```
And the SSACFG is:
```
BB2[1..1]
    -> BB5
    -> BB3
```
Is there any relationship between the order of next basic blocks and target?
In another words, I want to know which Basic Block is the true target belong to. The first or the second?

**Comment by msridhar** [comment]
@EdisonE3 based on the docs [here](https://github.com/wala/WALA/wiki/Intermediate-Representation-(IR)#control-flow-graph) I found this (poorly named) CFG `Util` class:

https://github.com/wala/WALA/blob/96018215f88a94bccda2b62a7e927abaf4238023/com.ibm.wala.core/src/main/java/com/ibm/wala/cfg/Util.java

It has methods like `getTakenSuccessor()` and `getNotTakenSuccessor()`.  Is this helpful?

**Comment by EdisonE3** [comment]
Thanks a lot!
