### ISSUE TITLE
Support C or C/C++ languages.

### ISSUE THREAD

**Issue by canliture** [wala/WALA#1097]
Hello! Everyone. I wondering if someone tried to extend WALA to Support C or C/C++ languages? To my knowledge, WALA supports Java or other JVM-baed languages, JavaScript, and other IBM internal supports for Swift, PHP, .Net, Python.

I don't know whether WALA has the ability to be extended to support to analysis other languages, such as C, C/C++ languages. 

I mean, Can C or C/C++ be translated to cAst or WALA IR using some C or C/C++ frontend? I don't know whether someone has done some works in this field. 

Thanks!

**Comment by msridhar** [comment]
@canliture Thanks for the question.  I don't know of any work around supporting analysis of C/C++ with WALA.  You might want to look at Phasar instead: https://phasar.org/phasar/ It's a framework that has some similar capabilities to WALA.
