### ISSUE TITLE
Error with making call graph

### ISSUE THREAD

**Issue by JohnCheeKinChow** [wala/WALA#1110]
![CleanShot 2022-07-15 at 19 36 35](https://user-images.githubusercontent.com/47556361/179279213-282c9b44-2ad2-4891-80ce-164806f31bab.png)

Hi, I want to make a call graph using SourceDirCallGraph example from the start project, and I run this command: `./gradlew -PmainClass=com.ibm.wala.examples.drivers.SourceDirCallGraph run --args="-sourceDir /Users/chowow/Desktop/bureaublad/School/2021-2022/2de sem/Bachelorproef/callGraph/test -mainClass example.java"`

But then I got the error like in the picture. Can someone tell me why?

**Comment by msridhar** [comment]
Looks like the code didn't compile.  Can you paste more of the log so we can see the compile errors?

**Comment by JohnCheeKinChow** [comment]
![CleanShot 2022-07-16 at 15 09 55](https://user-images.githubusercontent.com/47556361/179356270-82b796e3-cd1e-40c1-86db-cc0ebbe4feda.png)
![CleanShot 2022-07-16 at 15 09 34](https://user-images.githubusercontent.com/47556361/179356271-f2c5192a-f8c0-4a58-8566-8a35a19ab88a.png)
![CleanShot 2022-07-16 at 15 09 02](https://user-images.githubusercontent.com/47556361/179356272-8c041f33-5c44-4063-b902-00639b52868d.png)
I got these error message

**Comment by JohnCheeKinChow** [comment]
ohh I don't think it is in the right order. sorryy...

**Comment by JohnCheeKinChow** [comment]
@msridhar can you help me out? I still don't find it...

**Comment by msridhar** [comment]
@JohnCheeKinChow I think the issue here is the space character in your path `/Users/chowow/Desktop/bureaublad/School/2021-2022/2de sem/...`.  Can you try running using a path without space characters, or by enclosing the path in quotes?

**Comment by msridhar** [comment]
Also, if you could paste your error messages and console output as text rather than images that would be better.

**Comment by msridhar** [comment]
Going to close this out assuming it was resolved
