### ISSUE TITLE
Where is the implementation of copy propagation in WALA?

### ISSUE THREAD

**Issue by Andres981231** [wala/WALA#1111]
I have noticed that the comment at line 19-20 of the file com.ibm.wala.core/src/main/java/com/ibm/wala/ssa/SSAOptions.java mentions that WALA does copy propagation to eliminate those bogus assignments when it generating IR. I want to cancel the copy propagartion during the process, so I need to know where WALA implements it. Any hints will be really helpful, thanks a lot!

**Comment by Andres981231** [comment]
I have use WALA to generate IR for the following code.
![image](https://user-images.githubusercontent.com/33611278/180807575-70051e59-7bce-4ff8-9901-a60a582803ce.png)
And I got the result IR printed as follow.
![image](https://user-images.githubusercontent.com/33611278/180807825-f201929c-4169-4366-9f3c-72922aea3f95.png)
As we can see that line 12, 13, 16 of the source code have not been converted into any SSA assignment instructions in IR, the basic block 11 and 13 is empty. I think the result is caused by WALA performing copy propagation, and how can I disable this to get a unpruned IR result? Thanks!

**Comment by Chaoshuai-Li** [comment]
This answer may give you a little help.

https://github.com/wala/WALA/issues/1099#issuecomment-1120554010

**Comment by Andres981231** [comment]
> This answer may give you a little help.
> 
> [#1099 (comment)](https://github.com/wala/WALA/issues/1099#issuecomment-1120554010)

@Chaoshuai-Li 
Thanks for sharing! So have you successfully recovered statements of local variables yet?  I noticed that https://github.com/wala/WALA/wiki/Slicer#warning-exclusion-of-copy-statements-from-slice
metions that the SSABuilder class performs copy propagation, but I have not found any specific implementation or calling in it, so any advice from those who is familiar with the source code is welcome. Thank a lot!

**Comment by msridhar** [comment]
Sorry for my slow response.  As noted in https://github.com/wala/WALA/issues/1099#issuecomment-1120554010 it will be very hard to recover statements involving local variables with the current WALA implementation; copy propagation is rather "baked in" to SSA construction and cannot be turned off with a flag.  In retrospect, this may not have been the right design decision, but at this point we are stuck with it.  Other analysis frameworks like Soot may be more appropriate if you really need that functionality.

I'm going to go ahead and close this issue but if you need more help feel free to comment.
