### ISSUE TITLE
There is no entrypoints while the scope is "rt.jar" in JDK8 

### ISSUE THREAD

**Issue by DroseGao** [wala/WALA#1112]
I want to do the analysis of JDK's source code and here are some lines of my codes:
```
AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope("rt.jar", exFile);
ClassHierarchy cha = ClassHierarchyFactory.make(scope);
Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope,cha);
System.out.println(entrypoints);
```
What I got is just a "[]".

**Comment by DroseGao** [comment]
@msridhar Can you help me? I have been stuck for a long time.....Thx!!

**Comment by DroseGao** [comment]
I changed it from JDK8's rt.jar to JDK7's rt.jar. I can only get some of the methods but only a few..

**Comment by msridhar** [comment]
Hi @DroseGao, sorry, I've been on holiday for the last several weeks.  I've never attempted what you are trying (putting the Java standard library into the analysis scope).  I'm not really sure what is going on to cause the problem, but one thing to keep in mind is that if the same class exists under the "primordial" classloader and the "application" classloader, any reference will resolve to the "primordial" version.  That may be the cause of the problems here.

What exactly are you trying to do that requires analyzing rt.jar as an application?  WALA should analyze the bytecodes in those classes no matter what.  Did you try using a scope file where the Primordial scope points to the rt.jar file of interest (see [here](https://github.com/wala/WALA/wiki/Analysis-Scope))?

**Comment by DroseGao** [comment]
I just want to slice the JDK's source code. So you mean if the method I want to slice is the method in Java standard library, I can't make it as an "application" class, and it will not be made as an Entrypoint?

**Comment by msridhar** [comment]
> I just want to slice the JDK's source code.

Just to clarify, are you ok with doing slicing on bytecodes, and then mapping those results back to source code based on line numbers?  I don't believe our source code front end will work for analyzing the standard library, though I'm not sure.

>  So you mean if the method I want to slice is the method in Java standard library, I can't make it as an "application" class, and it will not be made as an Entrypoint?

What does it mean to slice a method?  Do you want to do a forward / backward slice starting from some statement within the method?  If so, then that should be the `Statement` you pass to the slicing APIs.

In terms of building a call graph, you can treat library methods as entrypoints; they don't need to be in the application code.  Here is a method that makes `Entrypoint`s for public methods in some package in the primordial scope:

https://github.com/wala/WALA/blob/dc3baa8f6988ae92a63c52304da4828f32e3a7bc/com.ibm.wala.core/src/test/java/com/ibm/wala/core/tests/callGraph/CallGraphTest.java#L276-L291

**Comment by DroseGao** [comment]
It works now! Thx alot !!!!
