### ISSUE TITLE
The problem of rec function loop call

### ISSUE THREAD

**Issue by Riven-hyr** [wala/WALA#1113]
I'm currently using WALA to analyze JS code.But when I analyze one test, I found that the analysis program seems to be calling rec function(located in  com.ibm.wala.ipa.callgraph.propagation.SSAPropagationCallGraphBuilder$CrossProductRec) all the time, which causes worklist to be stuck at this step. I would like to ask what could be the cause.
![image](https://user-images.githubusercontent.com/53611729/183031275-9f4eee2c-1d64-4b31-b55c-a977765934a2.png)
And this is the test case 
![image](https://user-images.githubusercontent.com/53611729/183032021-fe2a1103-714f-4a96-b432-3c40eb41f006.png)
And this is the required files in the test case 
![image](https://user-images.githubusercontent.com/53611729/183032649-a58ad310-c625-4291-8659-25d6a8664eb0.png)

**Comment by DroseGao** [comment]
I have the same question while slicing the java program when it has a loop call.

**Comment by msridhar** [comment]
This generally just reflects a scalability bottleneck during call graph construction.  See discussion here:

https://github.com/wala/WALA/wiki/Pointer-Analysis#improving-scalability
https://github.com/wala/WALA/wiki/Slicer#performance-tips

For JavaScript you may want to try the field-based call graph builder, which scales better (particularly in pessimistic mode).  Here is an example driver for running that:

https://github.com/wala/WALA-start/blob/master/src/main/java/com/ibm/wala/examples/drivers/FieldBasedJSCallGraphDriver.java

**Comment by Riven-hyr** [comment]
I would like to know if there is any relevant information about field-based algorithm. And if we use field-based call graph builder, is it able to handle the require method in JavaScript?

**Comment by msridhar** [comment]
The field-based algorithm is described in this paper:

https://manu.sridharan.net/files/ICSE-2013-Approximate.pdf

Unfortunately we do not have support for `require` in the field-based call graph builder in WALA.  Adding that support may not be too difficult based on the extant WALA Node.js support, but it would take some time.

**Comment by Riven-hyr** [comment]
For call/apply methods in Javascript, why does the pointer analysis take a long time, is there any documentation and related information for wala when analyzing this type of method?

**Comment by msridhar** [comment]
Analysis of call/apply can take a long time due to difficulties in analyzing these constructs precisely.  Imprecision gets introduced, which then gets propagated to many other variables.  And propagating these points-to sets takes a long time.

**Comment by Riven-hyr** [comment]
I would like to know why the imprecision was introduced, that is, what is the specific approach of wala when analyzing call/apply methods.

**Comment by msridhar** [comment]
The approach is straightforward.  When WALA observes a function value _f_ flowing to the receiver of a `call` or `apply` call, it models the code as invoking _f_ with the appropriate arguments.  The problem is that any imprecision (due to lack of flow sensitivity, path sensitivity, etc.), can "cascade" in JavaScript, yielding imprecise results for many variables.  See further discussion, e.g., in Section 2 of this paper:

https://manu.sridharan.net/files/ECOOP12Correlation.pdf

**Comment by Riven-hyr** [comment]
We have a method of analyzing the call/apply. We rewrite call/apply into a normal invoke call based on AST to discard the transferring of the "this" object, and then for the function called by "this" in the function, we search for the function of the same name from the global and build the calling side, and then transfer the parameters and return value of the function based on the calling side , we would like to know whether this method can improve the efficiency of parsing the call/apply method?

**Comment by msridhar** [comment]
@Riven-hyr I don't fully understand your technique, but it sounds pretty similar to what is already done in WALA.  At a call site invoking `call`, we basically generate IR that simulates invoking the "receiver" parameter to `call` (i.e., the function) with the appropriate receiver and other arguments.  I think maybe my previous answer was a bit misleading.  The issue isn't that `call` and `apply` are hard to model per se.  It is that the tracking of dataflow for which functions are invoked via those constructs can be imprecise, and then this imprecision cascades to other parts of the analysis result.

All that said, there may still be space for innovation here.  So if you feel you have an alternate technique that could work better, I encourage you to implement it and try it out.

You may want to also look at this call graph builder:

https://github.com/Persper/js-callgraph

It may be easier to hack on.  I am not sure as to their level of call / apply support.
