### ISSUE TITLE
Where can I find com.ibm.wala.dalvik.test.* code base?

### ISSUE THREAD

**Issue by sujon335** [wala/WALA#1114]
I am looking for the source code base of com.ibm.wala.dalvik.test.* package or class. It seems to be not there on the main WALA GitHub page. Also, are these classes deprecated?

1. com.ibm.wala.util.functions.VoidFunction
2. com.ibm.wala.util.Predicate

**Comment by msridhar** [comment]
@sujon335 it is here:

https://github.com/wala/WALA/blob/master/com.ibm.wala.dalvik/src/test/java/com/ibm/wala/dalvik/test/callGraph/DalvikCallGraphTestBase.java

(For reference, to find this class, on the main WALA GitHub page I pressed the 't' key to bring up the search and then searched for "DalvikTest".)  This code is under a test package, so it doesn't ship with WALA Maven artifacts.  So if you want to use code from here, you'll need to copy-paste it into your own class.  If someone would like to make a contribution to https://github.com/wala/WALA-start with a sample driver for Dalvik analysis, that would be great!
