### ISSUE TITLE
version1.5.7 build with maven3 fail，becourse of e47.target,and no thing at http://download.eclipse.org/releases/oxygen

### ISSUE THREAD

**Issue by knightyzl** [wala/WALA#1115]
Dear WALA developer.
I build WALA 1.5.7 with maven3，but fail。
Errors: Failed to resolve target definition **\WALA-1.5.7\targets\e47\e47.target: Failed to load p2 metadata repository from location  http://download.eclipse.org/releases/oxygen: Unknown Host: http://download.eclipse.org/releases/oxygen/content.xml.
And then I visit site  http://download.eclipse.org/releases/oxygen，this's no download for oxygen。
What should I do？

**Comment by msridhar** [comment]
WALA builds with Gradle; Maven build files are only present for a few legacy Eclipse-related projects.  If you clone the latest main branch and run `./gradlew build` on Java 8 everything should work (though it will take some time to run all the tests).  This command should also work with the 1.5.7 release.

If you run into a problem building with Gradle please open a new issue.
