### ISSUE TITLE
How to use wala get if-then body and if-else body in the if statement

### ISSUE THREAD

**Issue by xxwxxwen** [wala/WALA#1130]
Dear author, in the if statement, suppose if-then just executed,how to use WALA to find if-else body ? How to find the successor basic block in WALA? I'm looking forward to your reply.Thank you very much.

**Comment by msridhar** [comment]
Not sure I understand the question but is the information in https://github.com/wala/WALA/issues/1092#issuecomment-1057163286 helpful to you?

**Comment by xxwxxwen** [comment]
Thank you for your time and reply.
