### ISSUE TITLE
how to get neighbor else block number in if statement

### ISSUE THREAD

**Issue by xxwxxwen** [wala/WALA#1132]
Dear author,when an input executed **if-then** statement,how to get **the number** of **else** statement **in the path**?
Which means how to get **how many else block**  in the path.
![4](https://user-images.githubusercontent.com/91888325/193446066-c03d9154-cecb-4c0b-a592-b26bd7d44803.jpg)

**Comment by xxwxxwen** [comment]
How to use WALA to getTakenSuccessor and getNotTakenSuccessor n of basic block number?

**Comment by xxwxxwen** [comment]
How to use WALA to getTakenSuccessor and getNotTakenSuccessor basic block number?

**Comment by msridhar** [comment]
Not sure I understand the question, but I'll try to answer.  There is no notion if an if-then-else statement in WALA IR.  That construct gets lowered down to conditional branches that can be either _taken_ (if the condition is true) or _not taken_.  For an if-then-else, I imagine the else branch will usually correspond to the not taken case, but technically that depends on how it gets compiled to bytecode by `javac`; you'll have to check.  Anyway, once you figure out whether you want the taken or not taken successors, then the [`getTakenSuccessor()`](https://github.com/wala/WALA/blob/5c0cc45120d06e3ada3c39658292fbf23883577d/com.ibm.wala.core/src/main/java/com/ibm/wala/cfg/Util.java#L80) and [`getNotTakenSuccessor()`](https://github.com/wala/WALA/blob/5c0cc45120d06e3ada3c39658292fbf23883577d/com.ibm.wala.core/src/main/java/com/ibm/wala/cfg/Util.java#L65) methods should give you what you need.
