### ISSUE TITLE
It maybe useful to add "getFirstInstruction" api to interface ISSABasicBlock

### ISSUE THREAD

**Issue by enochii** [wala/WALA#1133]
Interface [ISSABasicBlock](https://github.com/wala/WALA/blob/5c0cc45120/com.ibm.wala.core/src/main/java/com/ibm/wala/ssa/ISSABasicBlock.java) provides `getLastInstruction` to retrieve the last instruction of a basic block. But there is no `getFirstInstruction` API, which should be useful when implementing some functionalities related to basic blocks.

```java
  /** @return the last instruction in this block. */
  public SSAInstruction getLastInstruction();
```

Though users can implement this function by themselves, at the cost of figuring out how the code logic(e.g. `SSACFG` `ISSABasicBlock`). It would be more convenient to provide this API out of box. Also, it seems easy to add the patch for this?

**Comment by msridhar** [comment]
Given this is a very stable interface, I'm hesitant to make changes.  If you have a reference to the corresponding `IR` you can do `IR.getInstructions()[b.getFirstInstructionIndex()]`, and write your own `getFirstInstruction()` method that does that.  Does that work?

**Comment by enochii** [comment]
> Given this is a very stable interface, I'm hesitant to make changes. If you have a reference to the corresponding `IR` you can do `IR.getInstructions()[b.getFirstInstructionIndex()]`, and write your own `getFirstInstruction()` method that does that. Does that work?

Got it. This is also my current solution. Thanks!

**Comment by enochii** [comment]
Actually, I'm quite curious why we don't have this API in the first place. Is it out of some consideration?

**Comment by enochii** [comment]
> Let me turn the question around; why do you need this API? :-) What I would want is a way to iterate the instructions in a basic block. For (maybe outdated) efficiency reasons that API was never directly added, but you can use the instruction index APIs to do that. Also I often work with `IExplodedBasicBlock`s in which case there is a maximum of one instruction in the block and you can fetch it with `getInstruction()`.

So if I got it right, there are mainly 2 reasons: 1) efficiency; 2) This API is not frequently used.  

I'm not familiar with WALA(Learning a lot from it :)), so forgive me if  I'm wrong. In my case, I want to get the `idom`(immediate dominator) of an instruction(Basic Block). My code logic is, when given an instruction, if it's the first instruction, then I need to find the BB it locates in and get the `idom` of the BB. I need to check whether an instruction is the first instruction of its BB. Also, generally, if we have the "last", we will have the "first".

But after clarifying my mind for your question, I guess the right way is "Instruction.iIndex() == bb.getFirstInstructionIndex()". :-) Thanks a lot~

**Comment by enochii** [comment]
I look at my code again, and actually, I do need the `getFirstInstruction()`. The case is that I need to get the dominance frontiers of an instruction. There are 3 steps:
- get the BB of the instruction
- get the frontiers of the BB
- find all the first instructions frontier-BBs

After some code inspection, there are 2 ways. 
(1) **BB.iterator.next()**
This one is kind of slow but straight forword. As we can see in SSACFG.BasicBlock, there are 2 related  methods(`iterator()` and `getAllInstructions()`). And `getAllInstructions()` is a bit complicated(so it may be slow).
```java
public Iterator<SSAInstruction> iterator() {
      return getAllInstructions().iterator();
}
public List<SSAInstruction> getAllInstructions() {
      compressPhis();

      ArrayList<SSAInstruction> result = new ArrayList<>();
      for (SSAInstruction inst : Iterator2Iterable.make(iteratePhis())) {
        result.add(inst);
      }

      for (int i = getFirstInstructionIndex(); i <= getLastInstructionIndex(); i++) {
        SSAInstruction s = instructions[i];
        if (s != null) {
          result.add(s);
        }
      }

      for (SSAInstruction inst : Iterator2Iterable.make(iteratePis())) {
        result.add(inst);
      }
      return result;
}
```
(2) **working with index**
The right way to get the first instruction seems not to be `IR.getInstructions()[bb.getFirstInstrucitonIndex()]`, here is an example, in the breakpoint here, we can see `IR.getInstructions()[bb.getFirstInstrucitonIndex()]` is null, at the mean time, `IR.getInstructions()[bb.getLastInstrucitonIndex()]` is ok.

<img src=https://user-images.githubusercontent.com/33364190/194622710-dd3e0b8a-dd1f-4acf-99fe-f38a0166db65.png height=120 >

![image](https://user-images.githubusercontent.com/33364190/194622971-564c3224-f97c-49e2-805e-e730250ffdb5.png)

I guess that `getfirstInstructionIndex` means the `previous-instruction-index`+1 rather than the actual **first**. So, learning from the `SSACFG.BasicBlock.getAllInstructions()`, the right way to go is:
```java
private SSAInstruction getFirstInstruction(ISSABasicBlock bb) {
    SSAInstruction[] instructions = ir.getInstructions();
    for (int i = bb.getFirstInstructionIndex(); i <= bb.getLastInstructionIndex(); i++) {
      SSAInstruction s = instructions[i];
      if (s != null) {
        return s;
      }
    }
    Assertions.UNREACHABLE();
    return null;
  }
```
