### ISSUE TITLE
travel wala in depth first search

### ISSUE THREAD

**Issue by xxwxxwen** [wala/WALA#1137]
Dear author, how to travel control flow graph in **depth first search** (DFS) in wala from the entry point? Is it only need to take InvokeIstruction into consideration? Does it need to travel other instruction(put instruction and get instruction)?
How to understand the output of control flow graph and call graph? Sometimes it may not map to the **line number** of source code.I'm not familiar with it.
![1](https://user-images.githubusercontent.com/91888325/194823235-641ff161-d11b-44df-aeb1-82e05956c795.jpeg)

Thank you very much!

**Comment by msridhar** [comment]
Sorry I can't fully understand the question.  If you just want to do a DFS over a graph you can implement it yourself or use `com.ibm.wala.util.graph.traverse.DFSPathFinder` to find a path to node matching some criterion.  Does that answer the question?
