### ISSUE TITLE
How to judge whether a statement is for loop statement

### ISSUE THREAD

**Issue by xxwxxwen** [wala/WALA#1138]
Dear author,how to judge whether a statement is **for loop statement** in the **control flow graph** with wala?

**Comment by msridhar** [comment]
Hi, I'm not sure about this; it's possible that a `for` loop will look identical to a similarly-structured `while` loop at the WALA IR level.  I think your best bet may be to look at the source location information and then get the source construct from the source code.  Let me know if there are further questions.
