### ISSUE TITLE
How can we get the next invoked function in call graph

### ISSUE THREAD

**Issue by xxwxxwen** [wala/WALA#1144]
In a path,it may have if branch,and we can only execute one side (if-then or if-else).How can we get the truly **executed successor** **node** **in call graph**? **Which API** in wala can we use to get the **next invoked function** **in call graph**?
In the test program,how can we get is **bar1** or **bar2** executed?
I'm looking forward to your reply.
public class Foo{
    private static int i = 0;
    public static void main(String[] args) {
        Foo f = new Foo();
        int x=70,y=14;
        int a;
        **if**(x>y) {
            a = (f.**bar1**(21)+x)*y;
        }
        **else**{
         a = (f.**bar2**(21)+x)*y;
            System.out.println(a);
        }
         System.out.println(a);
       return;  
    }
    public int bar1(int n){
        return n/7;
    }
    public int bar2(int n){
        return n+42;
    }
}

**Comment by msridhar** [comment]
@xxwxxwen I think you would need to run a symbolic execution or the like to determine if one branch if a conditional is always taken; this is not built in to WALA.  Let me know if I misunderstood the question.
