### ISSUE TITLE
Missing check in getSuperclass method of com.ibm.wala.classLoader.BytecodeClass 

### ISSUE THREAD

**Issue by HaofLi** [wala/WALA#1148]
Hi,
```
public IClass getSuperclass() {
    if (!superclassComputed) {
      computeSuperclass();
    }
    if (superClass == null && !getReference().equals(TypeReference.JavaLangObject)) {
      // TODO MissingSuperClassHandling.Phantom needs to be implemented
      if (cha instanceof ClassHierarchy
          && ((ClassHierarchy) cha)
              .getSuperClassHandling()
              .equals(ClassHierarchy.MissingSuperClassHandling.ROOT)) {
        superClass = loader.lookupClass(loader.getLanguage().getRootType().getName());
      } else
        throw new NoSuperclassFoundException(
            "No superclass found for " + this + " Superclass name " + superName);
    }
    return superClass;
  }
```
When the super class is null, **getSuperclass** will return java.lang.Object in MissingSuperClassHandling.ROOT mode, however, **getSuperclass** will throw an exception in MissingSuperClassHandling.PHANTOM mode.

Whether **getSuperclass** should return java.lang.Object or another PhantomClass in MissingSuperClassHandling.PHANTOM mode? I'm not sure if this is a missing-check or expected behavior.

Thanks!

**Comment by msridhar** [comment]
Sorry for the slow response.  This is expected behavior.  I don't recommend `PHANTOM` mode as it is not fully functional; only `ROOT` mode should be used if you want to handle missing superclasses.
