### ISSUE TITLE
Backward slicing code example with WALA

### ISSUE THREAD

**Issue by smith-co** [wala/WALA#1158]
I have to to implement *backward slicing* of a statement within a method which would give me the set of statements given a slice criterion. 

- Is there any example to do this? 
- Can I run it from a IntelliJ or Eclipse plugin?
- Does it support latest JDK version such as java 16?
- Can I map back the three address code to the actual code?

For my case, what I need is to select the code based on a given statement:

For example, given the following code, and slice point:

```
x = 1;
y = 2;
z = y-2;
r = x;
z = x+y; /* the slice point is the end of the program */.
```

I need to get the backward sliced code:

```
x = 1;
y = 2;
z = x+y;
```

 I think this should have an example of its own as there have been many requests in the soot mailing list regarding this.

I know this is an extremely powerful library. But the library seems to be very convoluted and there is so much to it. 

Please help me with some example how can I achieve it or is it even possible without spending months with the tool.

**Comment by msridhar** [comment]
Hi @smith-co the slicer page on the wiki will be helpful to you:

https://github.com/wala/WALA/wiki/Slicer

It has a code example.  Note that WALA IR does not preserve vanilla copy statements:

https://github.com/wala/WALA/wiki/Slicer#warning-exclusion-of-copy-statements-from-slice

So based on your examples above, I'm not sure the WALA slicer will do what you need.  Also, we have not tested with very recent JDK versions.

**Comment by smith-co** [comment]
@msridhar does it mean that we can not map back to the actual source code using Wala?

Also do you know what other Opensource alternative I am use for my usecase?

Thanks in advance!
