### ISSUE TITLE
sourceLine num in jarfile not correct

### ISSUE THREAD

**Issue by xxwxxwen** [wala/WALA#1165]
I have read [https://github.com/wala/WALA/wiki/Mapping-to-source-code#from-ir-instruction-to-bytecode-index--source-line-number](https://hub.nuaa.cf/wala/WALA/wiki/Mapping-to-source-code#from-ir-instruction-to-bytecode-index--source-line-number) to get source line num. 

When I generate source line num for a single java file, the line num is right. However,when I try to get source line num for the **file in a jar**, the line num is wrong. 
Does the source line number related to comments and blank line in the file? Since the file has about one thousand line code. But the source line num get from wala is smaller than one hundred. I have tried another test example, however, I still failed to get the correct line num. 
Does the source line num means the offset from the function?
Some method can't be cast to IBytecodeMethod. Can we get source line from IMethod not from IBytecodeMethod?
class com.ibm.wala.ipa.summaries.SummarizedMethod cannot be cast to class com.ibm.wala.classLoader.IBytecodeMethod
@msridhar Could you give me a reply at your convenience. It is important to me. Thank you for your help in advance.
```java
 public static int getBlockSourceLine(SSACFG cfg,CGNode n,ISSABasicBlock basicBlock) throws InvalidClassFileException {
        IR ir = n.getIR();
        if(ir==null)
            return -1;
        IBytecodeMethod method = (IBytecodeMethod)ir.getMethod();

        int start = basicBlock.getFirstInstructionIndex();
        int end = basicBlock.getLastInstructionIndex();
        int byteIndex = method.getBytecodeIndex(start);
        int sourceLine = method.getLineNumber(byteIndex);
        return sourceLine;
    }

**Comment by msridhar** [comment]
A `com.ibm.wala.ipa.summaries.SummarizedMethod` is something generated by WALA and won't have source information.

Otherwise, source line numbers should be correct, and they are taken from the debug information in the bytecode.  If you can share a specific example that doesn't work, I can look more closely.

**Comment by xxwxxwen** [comment]
@msridhar Thank you for your reply! I don't know whether it is correct that different basicblocks in a CGNode could have same source line number. I think different basicblock should have different source line numbers. I get same line number for different blocks.
  I calculate the **source line number** **for a basicblock** with the following code.Is it related to the startIndex and endIndex of the basicblock?Is there anything wrong with the code?  Thanks a lot!
```java
public static int getBlockSourceLine(SSACFG cfg,CGNode n,ISSABasicBlock basicBlock) throws InvalidClassFileException {
        IR ir = n.getIR();
        if (ir == null)
            return 0;
        IBytecodeMethod method = (IBytecodeMethod) ir.getMethod();
        SSAInstruction[] ssaInstructions = ir.getInstructions();

        int startIndex = basicBlock.getFirstInstructionIndex();
        int endIndex = basicBlock.getLastInstructionIndex();
        if(startIndex<0) start=0;
        int sourceLine = 0;
        int len = ssaInstructions.length;
            for (int i = startIndex; i <= endIndex; i++) {
                if (ssaInstructions[i] != null) {
                    int byteIndex = method.getBytecodeIndex(i);
                    sourceLine = method.getLineNumber(byteIndex);
//                ISSABasicBlock basicBlock1 = cfg.getBlockForInstruction(i);
                  System.out.println("lineNum:  " + n.getMethod().getName() + " " + basicBlock.getNumber() + " " + sourceLine);
                  if(sourceLine!=0)
                   return sourceLine;
                }
            }
        return sourceLine;
    }

**Comment by msridhar** [comment]
It's entirely possible that different basic blocks have the same source line number.  E.g., consider `Object x = (p) ? p.y() : q.z();" on a single source line.  This single source line will turn into multiple basic blocks due to the conditional branch, etc.

**Comment by xxwxxwen** [comment]
@msridhar Thank you for your help!
