### ISSUE TITLE
I see WALA 1.5.8 in maven central but not under releases in GitHub

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#1168]
I see WALA 1.5.8 here: https://mvnrepository.com/artifact/com.ibm.wala/com.ibm.wala.core. That seems to be the latest release as of today. But, https://github.com/wala/WALA/releases/latest shows 1.5.7. I do see, however, a tag for 1.5.8 here: https://github.com/wala/WALA/releases/tag/v1.5.8.

Not sure how big of an issue this is, but I did go to https://github.com/wala/WALA/releases to see what the latest version was. I guess I assumed that GitHub would have the latest version, but actually, it was maven central.

**Comment by msridhar** [comment]
Fixed, and you're right, we should keep GitHub releases up to date.  Thanks!

**Comment by msridhar** [comment]
FYI @khatchad I just released Version 1.5.9.
