### ISSUE TITLE
com.ibm.wala.cast.util.test.TestCallGraphShape no longer being packaged in released JARs?

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#1171]
I believe [`com.ibm.wala.cast.util.test.TestCallGraphShape`](https://github.com/wala/WALA/blob/3c2db2d26bb5fa6b5cb739586045ac0b1936dfaf/com.ibm.wala.cast/src/testFixtures/java/com/ibm/wala/cast/util/test/TestCallGraphShape.java) got lost in the released jars during the transition to Gradle from Maven. I found this out while trying to build https://github.com/wala/ML.

I'm looking at this dependency: https://github.com/wala/ML/blob/0543c10dc78a901c3e758f950159536e1cdb8661/com.ibm.wala.cast.python.test/pom.xml#L36-L41

Although [`com.ibm.wala.cast` exists in Maven Central](https://mvnrepository.com/artifact/com.ibm.wala/com.ibm.wala.cast), the code under https://github.com/wala/WALA/tree/v1.5.8/com.ibm.wala.cast/src/testFixtures/java/com/ibm/wala/cast/util/test isn't being included in that JAR or a variant of that JAR. Is that the way it's always been?

Maybe building https://github.com/wala/ML requires a local snapshot build. I have been changing a few things to get it to work with WALA on Maven Central, but maybe that's not the way it is meant to be. The `pom.xml` file in this directory was removed in 65a6eff11d101f77d1cc26c16e450231e66c9b3e, and in there, I don't see a mention of `testFixtures`.

**Comment by khatchad** [comment]
Looking at: https://github.com/wala/ML/blob/0543c10dc78a901c3e758f950159536e1cdb8661/.travis.yml#L21-L22

WALA is being built on the CI using maven, so it must have at some point been building those test jars. Maybe they're just not deployed to Maven Central?

**Comment by msridhar** [comment]
Hi @khatchad yes we currently don't deploy artifacts to Maven Central including our test fixtures code.  I guess wala/ML depends on this?  We could look into adding an artifact for that.  Which test fixtures does wala/ML depend on?

**Comment by khatchad** [comment]
> Hi @khatchad yes we currently don't deploy artifacts to Maven Central including our test fixtures code. 

I do see some modules on Maven Central (see https://mvnrepository.com/artifact/com.ibm.wala). The last version I see there is 1.5.8. Is deployment to Maven Central not happening going forward? Since Gradle projects can use Maven Central, I was thinking that even though WALA has transitioned to Gradle, the JARs would be deployed there (or some other centralized repository).

> I guess wala/ML depends on this?

Yes.

> We could look into adding an artifact for that. Which test fixtures does wala/ML depend on?

1. The test fixtures in [`com.wala.cast`](https://github.com/wala/ML/blob/0543c10dc78a901c3e758f950159536e1cdb8661/com.ibm.wala.cast.python.test/pom.xml#L36-L41).

That's all I can see for now.

**Comment by khatchad** [comment]
But, I guess it would make sense that test JARs are not deployed for "public" consumption. Instead, a developer could build WALA and deploy the snapshot jars (including test JARs) to their local repo, which I think it what used to happen.

But, WALA/ML still seems to be using Maven (it also has Gradle metadata, but it seems less recently updated). And, installing WALA to the local maven repo seems to fail at least on 3c2db2d26bb5fa6b5cb739586045ac0b1936dfaf:

```
$ ./gradlew publishToMavenLocal
> Task :com.ibm.wala.cast.js.rhino:signRemotePublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.ibm.wala.cast.js.rhino:signRemotePublication'.
> Cannot perform signing task ':com.ibm.wala.cast.js.rhino:signRemotePublication' because it has no configured signatory
```

**Comment by khatchad** [comment]
Not sure why a 'local publication" executes "signRemotePublication," but this command seems to succeed:

```
$ ./gradlew publishToMavenLocal -x signRemotePublication

BUILD SUCCESSFUL in 2s
149 actionable tasks: 69 executed, 80 up-to-date
```

**Comment by khatchad** [comment]
Ah, now I see them in my local maven repo!

**Comment by khatchad** [comment]
And, now it builds.

**Comment by khatchad** [comment]
I'll close this issue due to my thoughts on *not* deploying test JARs. However, I believe that another issue should be opened regarding requiring a "remote" signing of a local deployment.

**Comment by msridhar** [comment]
@khatchad would you still be able to open a PR on wala/ML with updated instructions for getting things going?

**Comment by khatchad** [comment]
Yup. Working on it.

**Comment by khatchad** [comment]
Some progress here: https://github.com/wala/ML/pull/23

**Comment by khatchad** [comment]
Should be ready for review now.
