### ISSUE TITLE
Publish artifacts for test fixtures

### ISSUE THREAD

**Issue by liblit** [wala/WALA#1201]
Artifacts relating to test fixtures are not currently published to the remote Sonatype repository. We should publish these too, though. See further discussion [here](https://github.com/wala/WALA/issues/1173#issuecomment-1374881868_).

**Comment by khatchad** [comment]
Related to https://github.com/wala/WALA/issues/1171.

**Comment by msridhar** [comment]
I see some test fixtures snapshot artifacts here:

https://oss.sonatype.org/content/repositories/snapshots/com/ibm/wala/com.ibm.wala.core/1.6.0-SNAPSHOT/

So this looks promising :-)  @liblit would `test-fixtures` be the "classifier" for these artifacts?  E.g., to refer to the WALA core test fixtures in Gradle, one could write `'com.ibm.wala:com.ibm.wala.core:X.Y.Z:test-fixtures'` I think.  Assuming yes, I can try to document that somewhere.

**Comment by liblit** [comment]
> would test-fixtures be the "classifier" for these artifacts? E.g., to refer to the WALA core test fixtures in Gradle, one could write `'com.ibm.wala:com.ibm.wala.core:X.Y.Z:test-fixtures'` I think.

I believe so. Looking at [the Maven metadata for the latest `com.ibm.wala.core` snapshot](https://oss.sonatype.org/content/repositories/snapshots/com/ibm/wala/com.ibm.wala.core/1.6.0-SNAPSHOT/maven-metadata.xml), we see:

```xml
<snapshotVersion>
  <classifier>test-fixtures</classifier>
  <extension>jar</extension>
  <value>1.6.0-20230115.154234-25</value>
  <updated>20230115154234</updated>
</snapshotVersion>
```

---

A better test would be to use these newly available test fixtures in a non-WALA project. OK: done. `com.ibm.wala.core.tests.util.WalaTestCase` is published as part of the `core` test fixtures. I was able to use this class in a new Gradle project configured with the following `build.gradle.kts`:

```kotlin
plugins { id("java") }

repositories.maven { url = uri("https://oss.sonatype.org/content/repositories/snapshots/") }

dependencies { implementation("com.ibm.wala:com.ibm.wala.core:1.6.0-SNAPSHOT:test-fixtures") }
```

---

The best test of all would be to have @khatchad use the test fixtures. I believe that he already has some projects that rely on test-fixtures material. Those projects should now be able to pull what they need from the Sonatype snapshots repository in the style that I showed above in my example `build.gradle.kts`.

**Comment by khatchad** [comment]
[I removed the custom WALA build](https://github.com/ponder-lab/ML/commit/5590bbe0facfa02d872ec3281c8492e05c5e3334), but the [test fixtures are now coming from the cache](https://app.travis-ci.com/github/ponder-lab/ML/builds/259768708#L185-L188). I'll see if I can flush that.

**Comment by khatchad** [comment]
OK, got [the build to fail](https://app.travis-ci.com/github/ponder-lab/ML/builds/259768708).  Now that the custom build is gone, it looks like the test fixtures are being downloaded from a few different places (see: https://app.travis-ci.com/github/ponder-lab/ML/builds/259768708#L1351). It would seem that I need to change the WALA version to use the 1.6.0 snapshot version in order to get the newly released ones.

**Comment by liblit** [comment]
> It would seem that I need to change the WALA version to use the 1.6.0 snapshot version in order to get the newly released ones.

Yes. The test fixtures that we are releasing are on the current WALA master branch, which produces 1.6.0-SNAPSHOT artifacts. We have not back-ported releasing of test fixtures to 1.5.x, and have no plans to do so.

**Comment by msridhar** [comment]
If it's helpful I can cut a 1.6.0 release in a few days, @khatchad

**Comment by khatchad** [comment]
Thanks, @msridhar. It looks like there's a few extra steps to enable snapshot dependencies. I'll take a hack at it and let yi9y know.

**Comment by msridhar** [comment]
@khatchad if I release 1.6.0 you won't have to worry about enabling snapshot dependencies in wala/ML.  Also, for build reproducibility, it'd be best if we could have wala/ML depend on a released version of WALA, not on changing snapshots.  So, if you can wait a few days, I can release WALA 1.6.0 and then you can update wala/ML to rely on that version and (hopefully) not need to build WALA from source anymore.

**Comment by khatchad** [comment]
Sounds good, @msridhar.
