### ISSUE TITLE
Release 1.6.0 (including test fixtures)

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#1211]
@khatchad if I release 1.6.0 you won't have to worry about enabling snapshot dependencies in wala/ML.  Also, for build reproducibility, it'd be best if we could have wala/ML depend on a released version of WALA, not on changing snapshots.  So, if you can wait a few days, I can release WALA 1.6.0 and then you can update wala/ML to rely on that version and (hopefully) not need to build WALA from source anymore.

_Originally posted by @msridhar in https://github.com/wala/WALA/issues/1201#issuecomment-1385811917_

**Comment by msridhar** [comment]
Version 1.6.0 is now released.

**Comment by msridhar** [comment]
It looks like the test fixtures artifacts are present as well, e.g., you can see them here for `wala.core`:

https://repo1.maven.org/maven2/com/ibm/wala/com.ibm.wala.core/1.6.0/

@khatchad can you confirm now that for `wala/ML` you can pull the 1.6.0 artifacts just from Maven Central and complete the build, so WALA no longer needs to be built from source?

**Comment by khatchad** [comment]
https://github.com/ponder-lab/ML/commit/ec071ea1fcb50dff5359d83bda1d15bdb4b9b03e

**Comment by khatchad** [comment]
https://app.travis-ci.com/github/ponder-lab/ML/builds/259910293

**Comment by liblit** [comment]
@khatchad: do these links you're posting mean "Yes, it works" or "No, it does not work"?

**Comment by khatchad** [comment]
Means: "in progress."

**Comment by khatchad** [comment]
The build passed, so it works!

**Comment by khatchad** [comment]
I'll merge it up and open a PR on github.com/wala/ML. Thanks!

**Comment by khatchad** [comment]
We can also see from [this changeset](https://github.com/ponder-lab/ML/commit/5590bbe0facfa02d872ec3281c8492e05c5e3334) that the custom WALA build has been removed.

**Comment by liblit** [comment]
I can't speak for @msridhar, but I don't need minute-by-minute progress reports. If the final answer is "Yes, it works", then that's all I need to know here.

And...apparently it works. Hooray! I hope that this makes life easier for you to keep wala/ML building cleanly. Getting those test-fixtures components released was overdue. Thanks for pushing us to make it happen.

**Comment by khatchad** [comment]
Thanks for adding the test fixtures, @liblit!

**Comment by khatchad** [comment]
This issue can be closed.

**Comment by liblit** [comment]
It already is closed, @khatchad.
