### ISSUE TITLE
Slice Across Different Files

### ISSUE THREAD

**Issue by dareenkf** [wala/WALA#1251]
How can I create a complete slice if parts of the slice are in a different class? Sometimes the class belongs to the same package and sometimes it is located in a different package. 
Thanks in advance for any help.

**Comment by msridhar** [comment]
Slicing works based on a `CallGraph`, so it should already work across classes.  See the example:

https://github.com/wala/WALA/wiki/Slicer#example

If you have a concrete example where the slice is missing statements across classes please let us know.  Thanks!
