### ISSUE TITLE
com.ibm.wala.ide is inaccessible to client applications

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#1260]
As far as I can tell, the `com.ibm.walka.ide` (and related IDE projects) is not being published to Maven, either local or remote. This had previously made some sense, because it was packaged as an OSGi component, and such components are typically deployed to p2 repositories. However, as 2fcbdee5c1980a75709d178afb6ff95434bbe46b, it is no longer an OSGi component. It is not clear now how client applications can use this code.

**Comment by khatchad** [comment]
I can confirm that the discussion at https://github.com/wala/WALA/issues/742#issuecomment-606385878 is no longer happening. Particularly, the old `MANIFEST.mf` file in `com.ibm.wala.ide` has the following classpath:

```
Bundle-ClassPath: .,
 target/dependency/com.ibm.wala.core.jar,
 target/dependency/com.ibm.wala.shrike.jar,
 target/dependency/com.ibm.wala.util.jar,
 target/dependency/com.ibm.wala.cast.jar
```

From that discussion, it seems that these files were being copied into these directories by Maven, but now the `pom.xml` files are gone. Thus, we only have gradle, and I can confirm that those files are not being copied there.

**Comment by msridhar** [comment]
@khatchad what is the ask here?  Do you see a way to publish this to Maven Central in a usable way?

**Comment by khatchad** [comment]
Hey @msridhar. I'm not sure what the solution is yet; for now, I am just reporting the problem. My first inclination was to ask to revert that commit that removed the OSGi metadata, but that still wouldn't solve the problem because the maven build is also missing. 

Let me think about what a good solution would look like.

**Comment by khatchad** [comment]
@msridhar I believe that the IDE subprojects can be deployed to Maven Central like the others *and* be useful without the OSGi metadata. This is because Tycho and M2E can now automatically generated OSGi metadata for arbitrary Maven dependencies. See https://xn--lubisoft-0za.gmbh/en/articles/using-maven-artifacts-in-pde-rcp-and-tycho-builds.

**Comment by khatchad** [comment]
Looks like this was removed in #1163.

**Comment by khatchad** [comment]
This is where the JARs were being copied:

https://github.com/wala/WALA/blob/2e6c6d0fe7e4559d2195e8998667783f848cd9c3/com.ibm.wala.ide/pom.xml#L17-L60

**Comment by khatchad** [comment]
I see here that they are now being copied in another way:

https://github.com/wala/WALA/blob/d15ca9b6eac43b9bcca0524ac4068c81cf9ff096/ide/build.properties#L1-L7

**Comment by khatchad** [comment]
However, I don't think this is working. I just built locally off of d15ca9b6eac43b9bcca0524ac4068c81cf9ff096. Then, I had a look at `ide/build/libs/com.ibm.wala.ide-1.6.1-SNAPSHOT.jar`. In that JAR, there's a `META-INF` directory, but no WALA JARs. The only other things in the JAR are the IDE class files.

```bash
$ jar tf ./com.ibm.wala.ide-1.6.1-SNAPSHOT.jar 
META-INF/
META-INF/MANIFEST.MF
com/
com/ibm/
com/ibm/wala/
com/ibm/wala/ide/
com/ibm/wala/ide/classloader/
com/ibm/wala/ide/classloader/EclipseSourceDirectoryTreeModule.class
com/ibm/wala/ide/classloader/EclipseSourceFileModule.class
com/ibm/wala/ide/plugin/
com/ibm/wala/ide/plugin/CorePlugin.class
com/ibm/wala/ide/client/
com/ibm/wala/ide/client/EclipseProjectSourceAnalysisEngine.class
com/ibm/wala/ide/client/EclipseProjectAnalysisEngine.class
com/ibm/wala/ide/ui/
com/ibm/wala/ide/ui/ViewIRAction.class
com/ibm/wala/ide/ui/SWTTreeViewer.class
com/ibm/wala/ide/ui/SWTTreeViewer$GraphViewer.class
com/ibm/wala/ide/ui/ViewIFDSLocalAction.class
com/ibm/wala/ide/ui/IFDSExplorer.class
com/ibm/wala/ide/ui/ViewIFDSLocalAction$Labels.class
com/ibm/wala/ide/ui/AbstractJFaceRunner.class
com/ibm/wala/ide/ui/SWTTreeViewer$GraphViewer$GraphLabelProvider.class
com/ibm/wala/ide/ui/SWTTreeViewer$GraphViewer$GraphContentProvider.class
com/ibm/wala/ide/util/
com/ibm/wala/ide/util/EclipseProjectPath$AnalysisScopeType.class
com/ibm/wala/ide/util/EclipseProjectPath$Loader.class
com/ibm/wala/ide/util/EclipseFileProvider.class
com/ibm/wala/ide/util/EclipseFileProvider$EclipseUtil.class
com/ibm/wala/ide/util/HeadlessUtil.class
com/ibm/wala/ide/util/HeadlessUtil$EclipseCompiler.class
com/ibm/wala/ide/util/EclipseProjectPath$ILoader.class
com/ibm/wala/ide/util/ProgressMonitorDelegate.class
com/ibm/wala/ide/util/EclipseProjectPath.class
com/ibm/wala/ide/util/HeadlessUtil$Parser.class
com/ibm/wala/ide/util/EclipseAnalysisScopeReader.class
```

**Comment by khatchad** [comment]
I see that https://github.com/wala/WALA/tree/master/com.ibm.wala-repository is still around. I guess that clients can create their own update site using that.
