### ISSUE TITLE
How to get the heap Context for a instance which is pointed by a specific PointerKey?

### ISSUE THREAD

**Issue by ljcppp** [wala/WALA#1273]
When I using context-sensitive-heap pointer analysis in WALA, how can I get the heap Context for this instance?
Some pseudocode shows below:
```java
builder = Util.makeZeroOneCFABuilder(options, cache, cha, scope);
PointerAnalysis pointerAnalysis = builder.getPointerAnalysis();
PointerKey objectPointer = pointerAnalysis.getHeapModel().getPointerKeyForLocal(cgnode, refvalue);
// Get intanceKey Set usually by this way, but the `InstanceKey` and `ConcreteTypeKey` doesn't contain anything about heap context.
// So how can I get the heap context? That's really significant to me.
OrdinalSet<InstanceKey> lockObjects = pointerAnalysis.getPointsToSet(objectPointer);
```
I have already read the source code of WALA for weeks, but this question still troubles me. I sincerely hope someone can answer my doubts.

**Comment by msridhar** [comment]
Good question!  I think what needs to happen is that the `InstanceKey` needs to be downcasted in the case where heap contexts are non-trivial.  E.g., if you have an [`AllocationSiteInNode`](https://github.com/wala/WALA/blob/89de874efbc3369097e03b85493f4a3beb8e1a44/core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/AllocationSiteInNode.java#L22-L22), you can then call `getNode()` to get the containing `CGNode` for the allocation site, and then that `CGNode` may have a context.  Is that helpful?

**Comment by msridhar** [comment]
Which call graph builder are you using? You need to use a builder that actually uses allocation sites in its heap model to get this information.

**Comment by msridhar** [comment]
Ok, sounds good.  Note the details around the optimizations on the heap model for 0-1-CFA here:

https://github.com/wala/WALA/wiki/Pointer-Analysis#zeroonecfa

In certain cases an allocation site abstraction is not used by default, e.g., for `String`s.  Maybe that is what you are running in to?
