### ISSUE TITLE
Configuration cache failures when compiling on JDK 17

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#1278]
I've started to tinker with basic JDK 17 compatibility for WALA.  As a start, on the master branch I ran `./gradlew compileJava compileTestJava`, and got the following configuration cache warnings:

```
5 problems were found storing the configuration cache, 2 of which seem unique.
- Plugin 'com.diffplug.configuration-cache-for-platform-specific-build': external process started 'uname -a'
  See https://docs.gradle.org/8.1/userguide/configuration_cache.html#config_cache:requirements:external_processes
- Task `:cast:java:test:data:compileTestJava` of type `org.gradle.api.tasks.compile.JavaCompile`: execution of task ':cast:java:test:data:compileTestJava' caused invocation of 'Task.extensions' in other task at execution time which is unsupported.
  See https://docs.gradle.org/8.1/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

The first one looks like a plugin issue, but the second one might be in our own scripts.  FYI @liblit

**Comment by liblit** [comment]
I am unable to reproduce these problems using

* a pristine WALA build tree,
* Fedora Linux 38,
* JDK 17, and
* the following command: `env JAVA_HOME=/usr/lib/jvm/java-17 ./gradlew compileTestJava`.

Gradle's output reports no configuration cache problems:

```
[...]
0 problems were found storing the configuration cache.

See the complete report at file:///home/liblit/Documents/research/joust/WALA/build/reports/configuration-cache/ac73fxhx2rqo7rrnei59eef83/2uk93bd2cpoe4qhaqrtefziw/configuration-cache-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3m 23s
47 actionable tasks: 47 executed
Configuration cache entry stored.
```

Rerunning the same build command likewise shows no problems:

```
Encryption of the configuration cache is enabled.
Reusing configuration cache.

BUILD SUCCESSFUL in 1s
37 actionable tasks: 37 up-to-date
Configuration cache entry reused.
```

@msridhar, can you provide more details, perhaps about any aspects of your system that differ from mine?

**Comment by msridhar** [comment]
Thanks for investigating, @liblit!  This may well be a Mac-specific issue.  I'll try to reproduce more carefully and report back, with more verbose output to help debugging.

**Comment by liblit** [comment]
@msridhar, has this problem gone away, perhaps due to ff02dabdff6ca8e33fb986ff1d2c449cdefbd3c3 as part of #1285?

**Comment by msridhar** [comment]
I just retried this on WALA master branch (running `./gradlew clean compileJava compileTestJava --no-build-cache`), and only got one error:

```
* What went wrong:
Configuration cache problems found in this build.

1 problem was found storing the configuration cache.
- Plugin 'com.diffplug.configuration-cache-for-platform-specific-build': external process started 'uname -a'
  See https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:external_processes
```

I'm attaching the generated configuration cache report.  It's a plugin issue, and a quick Google search didn't turn up an existing issue.

[Gradle Configuration Cache.pdf](https://github.com/wala/WALA/files/12388614/Gradle.Configuration.Cache.pdf)

**Comment by msridhar** [comment]
FYI I am going to report this issue upstream.
