### ISSUE TITLE
unclear whether WALA supports Java 8

### ISSUE THREAD

**Issue by mohrm** [wala/WALA#132]
@msridhar @juliandolby I am a bit confused about whether WALA supports Java 8 or not. The pom.xml does not specify source or target language in the maven-compiler-plugin, so I guess maven just uses "what is there". The .travis.yml first specifies that oraclejdk8 is needed but then, before the maven jars are built, the jdk is switched to Java 7.

In the various WALA eclipse projects, Java version varies at least between 6 (e.g. com.ibm.wala.util) and 8 (e.g. com.ibm.wala.cast.js)

So, my question is: Is Java 8 code allowed in WALA? This regards both language constructs and standard library usage.

**Comment by msridhar** [comment]
I have no objection to using Java 8 code in WALA at this point.  The only thing that might be holding us back are requirements from IBM products.  I'm also fine with cutting a final Java 7 release and then changing master to use Java 8 with some kind of major version bump.  @juliandolby any thoughts?

**Comment by juliandolby** [comment]
@msridhar @ Inside IBM, I think Java 8 may be ok; however, there is still a need to run WALA using IKVM on .NET, and I have not yet tested the claims of the latest IKVM release to handle Java 8 features.

 Another issue is that I am unsure to what extent recent Android releases support Java 8, and I would like to keep the ability to compile WALA for Android.  One possible rule would be that we can use any features that Google’s Jack compiler can handle.

 I have also started using TeaVM to compile Java bytecode to JavaScript to run on browsers.  That system does mostly seem to handle Java 8 well, though.

 All in all, I would like to test these systems before moving WALA to Java 8.

  — Julian

**Comment by khatchad** [comment]
I believe that the title of this bug is a bit misleading. When you say "supports," do you mean that WALA *analyzes* Java 8 code?

**Comment by juliandolby** [comment]
Yes, it does analyze Java 8 byte code.  It also runs on Java 8.

  — Julian

**Comment by khatchad** [comment]
Thanks, @juliandolby. The reason I was wondering was due to an error I encountered yesterday. I filled #137.

**Comment by juliandolby** [comment]
I just looked into that.  While I did implement invokeDynamic support, it seems that I neglected 1 of the 5 cases in one place, perhaps because I had not seen it in Java 7.  

I can see how to implement the desired semantics and will get to it in the next few days.

 — Julian

**Comment by juliandolby** [comment]
OK, I believe I just checked in a fix for this issue.

**Comment by msridhar** [comment]
Closing this issue; the resolution is that due to IKVM / Android, we can't use Java 8 constructs in WALA yet.  Android may be less of a problem soon: https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html Not sure about IKVM.

**Comment by khatchad** [comment]
@msridhar There's also the [Jack Compiler](https://developer.android.com/guide/platform/j8-jack.html) for Android.

**Comment by msridhar** [comment]
Jack is dying; see [the post](https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html) I linked above.

**Comment by khatchad** [comment]
Ah! Thanks @msridhar.
