### ISSUE TITLE
How to turn HeapGraph into JSON for Javascript?

### ISSUE THREAD

**Issue by mwang14** [wala/WALA#1327]
Hi, I am trying to turn a HeapGraph into a JSON format, where the keys are the source variable names (and their allocation site) and the values are all the locations they can point to after performing a pointer analysis. I've been looking at issue #743. I can iterate through the PointerKeys and the InstanceKeys they point to using `PA.getPointsToSet`, but I'm a little confused on how to get the source variable name and definition line from the PointerKey.

**Comment by msridhar** [comment]
Here are the docs we have on that:

https://github.com/wala/WALA/wiki/Mapping-to-source-code#mapping-value-numbers-back-to-local-names

Are you analyzing Java?  Does that help solve your problem?

**Comment by mwang14** [comment]
Thanks! I am analyzing Javascript. I'm more so looking for a way to construct the points-to graph for the whole program. So what I would like is to get the variable name and allocation site (in the case of overlapping variable names) for a PointerKey. So given the following program:

```
function foo() {
    var a = {};
    var b = {};
    a = b;
}
var a = {};
foo();
```

I'd like a json along the lines of:

```
{
    "a defined on line 2": [heaploc1, heaploc2],
    "b defined on line 3": [heaploc2],
    "a defined on line 6": [heaploc3]
}
```

So I was going to get all the PointerKeys given a HeapGraph, and do something like:
```
for (PointerKey n : PA.getPointerKeys()) {
      try {
        if (!n.toString().contains("prologue")){
        System.out.println((n.getNode().getIR().getLocalNames(...) + n.getNode().getIR().getLineNumber(...)  + " --> " + PA.getPointsToSet(n)));
        }
    }
```
 Would that be your recommended way of going about it?

**Comment by msridhar** [comment]
Hi @mwang14 so `PointerKey` is an interface that could potentially represent local variables, globals, or many other kinds of pointers.  I think what you need to do is check if the `PointerKey` is a `LocalPointerKey`.  If it is, you should be able to call `getNode()` and `getValueNumber()` on it, and then use the value number to look up local names with the IR from `CGNode.getIR()`.  Does that help?

**Comment by mwang14** [comment]
Hi Manu! Sorry for the delay - was caught up in some other work and projects but I'm back on the pointer analysis. I was testing some of the code I had written earlier per your suggestion on some additional testcases and I'm a little confused by the output. 
I'm iterating through all the LocalPointerKeys in the heap graph returned after generating the call graph on a Javascript programs, and getting the instance keys they point to. The code snippet is here:

```
CallGraph CG = b.makeCallGraph(b.getOptions());
PointerAnalysis<? extends InstanceKey>  PA = b.getPointerAnalysis();
HeapGraph<? extends InstanceKey> HG = PA.getHeapGraph();
for (Object key : Iterator2Iterable.make(HG.iterator())) {
      if (key instanceof LocalPointerKey && !key.toString().contains("prologue")) {
        // get the local variable name of the key
        CGNode node = ((LocalPointerKey)key).getNode();
        IR ir = node.getIR();
        IMethod method = ir.getMethod();
        int valueNumber = ((LocalPointerKey)key).getValueNumber();
        DefUse du = node.getDU();
        String[] localNames = ir.getLocalNames(0, valueNumber);
        
        if (localNames != null && localNames.length > 0) {
          // Get all the instance keys that this PointerKey points to. 
          for (Object sucNode : Iterator2Iterable.make(HG.getSuccNodes(key))) {
            System.out.println(localNames[0] + " --> " + sucNode.hashCode());
          }
        }
      }
    }
```

I'm running it on the following Javascript snippet:
```
function test() {
    var src = {"field1": 1};
}

function test2() {
    var src2 = {"field2": 1};
}

var var1 = {"var1" : 1};
var var2 = var1; // should this point to the same InstanceKey as var1?
```

And this is the output:

```
// All variables have a pointer to the same InstanceKey 
var1 --> 1667158707
var2 --> 1667158707
src --> 1667158707
src2 --> 1667158707

// But there's no InstanceKey that is only pointed to by var1 and var2?
var1 --> 706261226
src --> 1816604714
src2 --> -125624134
```

Is this the expected output? I would have thought that `var1` and `var2` would share an InstanceKey that isn't also being pointed to by `src` and `src2`. I'm running 0-CFA - closely following the example [here](https://github.com/msridhar/WALA-start/blob/extra-debug-info-js/src/main/java/com/ibm/wala/examples/analysis/js/JSCallGraphBuilderUtil.java). Thanks so much for the help and hope you've been doing well!

**Comment by msridhar** [comment]
I'm not sure why all variables have a pointer to a common InstanceKey...that seems weird.  Can you print the `toString()` of that `InstanceKey` not just its hash code?

Regarding `var1` and `var2` the WALA SSA representation gets rid of copy statements.  So `var1` and `var2` might be represented by the same `LocalPointerKey`.  Could you try printing _all_ the local names for each `LocalPointerKey`, not just `localNames[0]`?

**Comment by msridhar** [comment]
Got it. Looks like the analysis models that any variable may be `undefined`.  I guess you can filter that out and ignore it if needed.

**Comment by mwang14** [comment]
Yep, that shouldn't be a problem. Thanks so much for the help!!

**Comment by msridhar** [comment]
Going to go ahead and close this one.  Please open a new issue for further problems.
