### ISSUE TITLE
How to get the target method for a java Primordial class with pointer analysis results?

### ISSUE THREAD

**Issue by ljcppp** [wala/WALA#1329]
I attempted to use the following code to obtain the `CGNode` that the `SSAAbstractInvokeInstruction invokeInst` statement invokes. The `CGNode n` is the `CGNode` in which the current invokeInst is located. However, for `Primordial` CGNodes, I cannot use Method1 `Set<CGNode> set = callGraph.getPossibleTargets(n, csr);` from the code provided to obtain the CGNode. I can use that Method1 to get the CGNode for `Application` CGNodes.
```java
protected void findChildCGNode(CGNode n, SSAAbstractInvokeInstruction invokeInst) {
    CallSiteReference csr = invokeInst.getCallSite();
    MethodReference mr = csr.getDeclaredTarget();
    IMethod imethod = callGraph.getClassHierarchy().resolveMethod(mr);

    // Method1: get the possible targets by Pointer Analysis results.
    Set<CGNode> set = callGraph.getPossibleTargets(n, csr);

    // Method2: get the possible targets by MethodReference.
    if (set.isEmpty())
        set = callGraph.getNodes(mr);

    // Method3: get the possible targets by imethod.
    if (set.isEmpty() && n.getMethod() != null) {
        try {
            if (imethod != null) {
                CGNode n2 = ((BasicCallGraph) callGraph).findOrCreateNode(imethod, n.getContext());
                set = new HashSet<>();
                set.add(n2);
            }
        } catch (CancelException e) {
            e.printStackTrace();
        }
    }
}
```
I ran the aforementioned code on Java 11, and I made sure to include the relevant **jmod files** in the `AnalysisScope`. Additionally, I did not include the relevant jmod files in the `exclusionsFile`. 

I can retrieve the corresponding `Primordial` `CGNode` by using Method3 from the provided code and based on `ClassHierarchy` to obtain the `IMethod` of parent and child classes. However, this approach relying on `ClassHierarchy` tends to produce a higher rate of false positives. Therefore, I would like to ask how I can obtain the results based on pointer analysis. 
Is it possible that I am using the API incorrectly, or have I misconfigured something elsewhere? 

I sincerely hope someone can answer my doubts.

**Comment by msridhar** [comment]
A self-contained full program to reproduce would be helpful.  From what you wrote, my guess is that the target method of the call site is simply not in the call graph.  But it's hard to figure out why that would happen without more details.

**Comment by msridhar** [comment]
> I would like to inquire why you can use `findOrCreateNode` to locate the `CGNode` that contains the target method's body.

It's because `findOrCreateNode` will create the node if it does not exist.

**Comment by msridhar** [comment]
The `IMethod` will have a pointer to the code and it's sufficient to construct an IR.  See [this API](https://github.com/wala/WALA/blob/f32887d9013493235232b4a87518dd8ca2fbb9c0/core/src/main/java/com/ibm/wala/ipa/callgraph/AnalysisCache.java#L64-L69).
