### ISSUE TITLE
Unable to Download WALA Tutorial PDF

### ISSUE THREAD

**Issue by DaisyPo** [wala/WALA#1335]
I am having trouble downloading the WALA tutorial PDF from the official website. The link https://wala.sourceforge.net/files/PLDI_WALA_Tutorial.pdf  is returning a 404 error. Could you please provide an alternative download link or share the PDF if possible?

**Comment by msridhar** [comment]
Sorry for the hassle; we just discovered this ourselves!  The updated URL is https://wala.github.io/tutorials/PLDI_WALA_Tutorial.pdf.
