### ISSUE TITLE
Request for WALA Slicer Tutorial

### ISSUE THREAD

**Issue by DaisyPo** [wala/WALA#1337]
Hello,
I'm interested in  the WALA slicer, but I've encountered a 404 error when trying to access the WALA slicer tutorial on the following URL: http://wala.sourceforge.net/wiki/index.php/UserGuide:Slicer
 I'd greatly appreciate it if someone could provide guidance on where I can find the WALA slicer tutorial or if there are any alternative resources available for learning how to use the slicer.

Thank you in advance for your assistance.

**Comment by DaisyPo** [comment]
I found this link https://github.com/wala/WALA/wiki/Slicer.

**Comment by msridhar** [comment]
The new link is correct. Unfortunately the old WALA MediaWiki installation is down. Not sure if/when we can restore it. Nearly all the content is on the GitHub wiki now and is being updated here.
