### ISSUE TITLE
How to remove nodes or edges in the original SDGs?

### ISSUE THREAD

**Issue by shanshw** [wala/WALA#1434]
Hello, I am using wala to do a SDG-based taint analysis on a java project with the easiest data-flow options and control-flow options. However, there still so many nodes and edges especially inside the built-in java classes. 
Therefore, I want to remove some unrelated nodes from the built SDG. However, the error occurs and says unimplemented. I am confused, anyone can help? Thanks a lot!

**Comment by msridhar** [comment]
You can use an exclusions file to exclude entire packages from analysis:

https://github.com/wala/WALA/wiki/Analysis-Scope#exclusions-files

If you're analyzing libraries from Java 9+, you can also see examples on [that page](https://github.com/wala/WALA/wiki/Analysis-Scope) of how to only analyze certain modules from the Java standard library.

Beyond that, you'll have to get into the guts of things a bit more to make a wrapper call graph or SDG that filters certain nodes / edges.

Regarding your error we'll need a more complete example to reproduce and give feedback.

**Comment by shanshw** [comment]
Thank you very much @msridhar , I made it by making a wrapper pathFinder to filter out some nodes and edges. For the error, I take a look into the source code of the built-in SDG, and it's clear that the `Assertions.UNREACHABLE();` making it impossible to remove nodes or edges from the built SDG. ![1](https://github.com/user-attachments/assets/eb751d3f-35cf-4636-b474-9432d94237c9) I am also confused by the design.

**Comment by shanshw** [comment]
Using a wrapper pathFinder or a wrapper SDG
