### ISSUE TITLE
Support for Slicing Concurrent Java Programs

### ISSUE THREAD

**Issue by bupt01** [wala/WALA#1457]
Hello WALA Team,

Thank you for maintaining such a valuable tool! I am currently researching slicing techniques for Java programs, with a specific focus on handling concurrent code. I wanted to ask if WALA provides any functionality or extension to support slicing for concurrent Java programs. If not, could you suggest any potential approaches within the WALA framework that might facilitate this?

Thank you for your time and assistance!

**Comment by msridhar** [comment]
Hi @bupt01 if you are asking if WALA slicing is sound for concurrent programs, the answer is no, unfortunately.  I believe you would need something like a may-happen-in-parallel analysis to account for heap writes from other threads when doing a slice.

I'm not aware of any WALA-based analysis that does sound slicing that accounts for concurrency; sorry about that.  If I hear of something I will comment here.

**Comment by bupt01** [comment]
Thank you so much for the insight on this! I appreciate the clarification regarding WALA and concurrent programs. It sounds like achieving sound slicing with concurrency considerations would indeed require a may-happen-in-parallel analysis or something comparable. If any updates or tools come up that address this, I'd definitely be interested. Thanks again for your help!
