### ISSUE TITLE
Compile Failure on Fresh Clone of R_1.4.1

### ISSUE THREAD

**Issue by dwtj** [wala/WALA#166]
```
$ git clone https://github.com/wala/WALA.git
$ git checkout R_1.4.1
HEAD is now at 2d0518963... Tag release 1.4.1
$ mvn --quiet clean compile
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
/Users/dwtj/Sources/WALA/com.ibm.wala.cast.java.test.data/src/javaonepointfive/Varargs.java:63: warning: non-varargs call of varargs method with inexact argument type for last parameter;
		varargs(2, 3, new String[] { "hello", "world" });
		              ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: /Users/dwtj/Sources/WALA/com.ibm.wala.cast.java.test.data/src/JLex/Main.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
[ERROR] Failed to execute goal on project com.ibm.wala.cast.js.test: Could not resolve dependencies for project com.ibm.wala:com.ibm.wala.cast.js.test:eclipse-plugin:1.4.1: Could not find artifact com.ibm.wala:com.ibm.wala.cast.js.test.data:jar:1.4.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.ibm.wala.cast.js.test
```

But it looks like one can work-around this particular compile failure by manually compiling/installing two of the subprojects first. (Not 100% sure, since the tests are still running.)

```
$ mvn --quiet install --projects com.ibm.wala.target:e44
$ mvn --quiet install --projects com.ibm.wala.cast.js.test.data
$ mvn --quiet compile
```

**Comment by msridhar** [comment]
Is this fixed on master by any chance?

**Comment by dwtj** [comment]
Trying now... (Is there an an option to compile everything without running any tests?)

**Comment by dwtj** [comment]
Yes, this appears to also be a problem on the latest of [master], commit 5ecbba95.

```
$ mvn --quiet compile
warning: [options] bootstrap class path not set in conjunction with -source 1.4
warning: [options] source value 1.4 is obsolete and will be removed in a future release
warning: [options] target value 1.4 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
/Users/dwtj/WALA/com.ibm.wala.cast.java.test.data/src/javaonepointfive/Varargs.java:63: warning: non-varargs call of varargs method with inexact argument type for last parameter;
		varargs(2, 3, new String[] { "hello", "world" });
		              ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: /Users/dwtj/WALA/com.ibm.wala.cast.java.test.data/src/JLex/Main.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
[ERROR] Failed to execute goal on project com.ibm.wala.cast.js.test: Could not resolve dependencies for project com.ibm.wala:com.ibm.wala.cast.js.test:eclipse-plugin:1.4.2-SNAPSHOT: Could not find artifact com.ibm.wala:com.ibm.wala.cast.js.test.data:jar:1.4.2-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.ibm.wala.cast.js.test
```

**Comment by dwtj** [comment]
Those tests finally finished... with an error, unfortunately. It looks like all 20 tests of `TestSimplePageCallGraphShapeRhinoNu>TestSimplePageCallGraphShape` fail because my system doesn't have the class `nu.validator.htmlparser.sax.HtmlParser`. See attached for the error log. This was collected with R_1.4.1.

[WALA 2d05189 Issue 166 Test Error Log.txt](https://github.com/wala/WALA/files/924565/WALA.2d05189.Issue.166.Test.Error.Log.txt)

I'm going to try to install <https://about.validator.nu/htmlparser/>. Is that a sensible move?

**Comment by dwtj** [comment]
I added the following dependency to `com.ibm.wala.cast.js.html.nu_validator/pom.xml`

```
    <dependency>
      <groupId>nu.validator.htmlparser</groupId>
      <artifactId>htmlparser</artifactId>
      <version>1.4</version>
      <scope>test</scope>
    </dependency>
```

However, this leads to a compile error that I don't initially understand:

```
$ mvn --quiet compile
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.9:copy-dependencies (copy-dependencies) on project com.ibm.wala.cast.js.nodejs: Artifact has not been packaged yet. When used on reactor artifact, copy should be executed after packaging: see MDEP-187. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.ibm.wala.cast.js.nodejs
```

**Comment by msridhar** [comment]
I wonder if this is an issue with the Maven commands you are running.  We use Tycho for integrating our Eclipse build files, and it does weird stuff under the hood that I don't fully understand.  For compiling, we usually run:
    
    mvn clean verify -DskipTests=true -q

And then to run tests, we do:
    
    mvn clean verify -q

Somehow just running the latter command doesn't seem to be sufficient to make the tests pass (last time I checked); you need to run both (weird, I know).  Can you try and see if something like that works?  I know it works on CI (see our [.travis.yml](https://github.com/wala/WALA/blob/5ecbba95ffb76798cc78bba81fe50a3c0378f94b/.travis.yml)).

**Comment by msridhar** [comment]
Also, if you're not hacking the guts of WALA, consider pulling the jars from Maven Central; see [here](https://github.com/wala/WALA/wiki/Getting-Started#quick-start-using-maven-central-packages).

**Comment by dwtj** [comment]
Oh, I didn't realize that you had a CI. (I always forget the trick to check there when struggling to build something.)

Yeah, the projects I'm trying to make are going to be built with Gradle to depend upon WALA via Maven Central. I'm trying to use the latest release of WALA's core for some basic Java program analysis.

I just want to be able to browse the whole source tree in my IDE (IntelliJ IDEA) to understand how it works (e.g. look at the tests). I'm just trying to have compiled and installed enough maven artifacts that I can browse the source in my IDE without broken imports.

It looks like your suggestion of `mvn clean verify -DskipTests=true -q` compiled fine.

I also found that I could compiling the individual subprojects. It looks like these this subset of projects in this order does the trick for me for now.

```
$ mvn install --projects com.ibm.wala.target:e44
$ mvn install --projects com.ibm.wala.util
$ mvn install --projects com.ibm.wala.shrike
$ mvn install --projects com.ibm.wala.core
```

**Comment by dwtj** [comment]
Ok, I've got my code browsing environment set up now, and it seems to be working. Thanks for your prompt feedback!

**Comment by msridhar** [comment]
Cool, glad it's working!
