### ISSUE TITLE
Long running time involving Collector and nCFABuilder when N=2

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#169]
I am experiencing a (seemingly) infinite loop when processing the following program and using a nCFABuilder with n = 2:

```java
package p;

import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

class A {
	void m() {
		Set<Object> set = new HashSet<>();
		Stream<Object> stream = set.parallelStream();
		stream.sorted(); 
		stream.collect(Collectors.toList()); // this call forces the error.
	}
}
```

The file may also be found on [my fork](https://github.com/khatchad/WALA/blob/master/StreamTest.java). Also on my fork, I have modified `PDFCallGraph.java` example driver to expose the issue. To reproduce the issue, please follow the following steps:

1. Clone [my fork](https://github.com/khatchad/WALA).
1. Compile `StreamTest.java`: `javac StreamTest.java`
1. Package `StreamTest.java` into a jar: `jar cvf StreamTest.jar StreamTest.class`
1. Copy `StreamTest.jar` into the main workspace directory: `cp StreamTest.jar ../`
1. Run the `PDFCallGraph` run configuration.

## More Information

The following information may or may not be helpful in diagnosing this issue:

- The debugger can also be used to pause WALA during the infinite loop. 
- This issue was found whilst verifying #144.
- The fix for #144 seems to be in https://github.com/wala/WALA/commit/7e3066b6cda07ea6e977495b82cb0d2a202bb0c2.
- The loop seems to be in the call graph construction. It's getting stuck on the call to `solver.solve(monitor);` in `com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(AnalysisOptions, IProgressMonitor)`.
- There is an example stack trace from an earlier WALA version [here](https://github.com/wala/WALA/issues/144#issuecomment-286576334).

## Regression

- The problem does not happen using the `ZeroCFABuilder`
- The problem only happens for certain terminal operations on Java 8 Streams like `collect()` or certain intermediate operations like `distinct()`.

**Comment by msridhar** [comment]
@juliandolby can you take a look?  You know more about the Java 8 support than I do, and this involves Java 8 classes.

**Comment by khatchad** [comment]
Suppose we have the following method:
```java
public static void main(String[] args){
  new ArrayList().stream().reduce((x,y) -> x);
}
```
which produces the following CFG:
```java
=< Application, LC, main([Ljava/lang/String;)V >
CFG:
BB0[-1..-2]
    -> BB1
BB1[0..0]
    -> BB2
    -> BB7
BB2[1..2]
    -> BB3
    -> BB7
BB3[3..3]
    -> BB4
    -> BB7
BB4[4..4]
    -> BB5
    -> BB7
BB5[5..5]
    -> BB6
    -> BB7
BB6[6..7]
    -> BB7
BB7[-1..-2]
```
and instructions:
```java
BB0
BB1
0   v3 = new <Application,Ljava/util/ArrayList>@0(line 6)
BB2
2   invokespecial < Application, Ljava/util/ArrayList, <init>()V > v3 @4 exception:v4(line 6)
BB3
3   v6 = invokevirtual < Application, Ljava/util/ArrayList, stream()Ljava/util/stream/Stream; > v3 @7 exception:v5(line 6)
BB4
4   v8 = invokestatic < Application, Ljava/lang/invoke/LambdaMetafactory, apply()Ljava/util/function/BinaryOperator; > @10 exception:v7(line 6)
BB5
5   v10 = invokeinterface < Application, Ljava/util/stream/Stream, reduce(Ljava/util/function/BinaryOperator;)Ljava/util/Optional; > v6,v8 @15 exception:v9(line 6)
BB6
7   return                                   (line 7)
BB7
}
```
The error does not occur with this input.

**Comment by khatchad** [comment]
Now suppose we have this method:
```java
public static void main(String[] args){
  new ArrayList().stream().forEach(x -> {
  }
);
}
```
which produces the following CFG:
```java
=< Application, LC, main([Ljava/lang/String;)V >
CFG:
BB0[-1..-2]
    -> BB1
BB1[0..0]
    -> BB2
    -> BB7
BB2[1..2]
    -> BB3
    -> BB7
BB3[3..3]
    -> BB4
    -> BB7
BB4[4..4]
    -> BB5
    -> BB7
BB5[5..5]
    -> BB6
    -> BB7
BB6[6..6]
    -> BB7
BB7[-1..-2]
```
and instructions:
```java
BB0
BB1
0   v3 = new <Application,Ljava/util/ArrayList>@0(line 6)
BB2
2   invokespecial < Application, Ljava/util/ArrayList, <init>()V > v3 @4 exception:v4(line 6)
BB3
3   v6 = invokevirtual < Application, Ljava/util/ArrayList, stream()Ljava/util/stream/Stream; > v3 @7 exception:v5(line 6)
BB4
4   v8 = invokestatic < Application, Ljava/lang/invoke/LambdaMetafactory, accept()Ljava/util/function/Consumer; > @10 exception:v7(line 6)
BB5
5   invokeinterface < Application, Ljava/util/stream/Stream, forEach(Ljava/util/function/Consumer;)V > v6,v8 @15 exception:v9(line 6)
BB6
6   return                                   (line 7)
BB7
```
The problem *does* exhibit itself here.

**Comment by khatchad** [comment]
Let's have a look at differences in the IR:
```diff
9c9
< 4   v8 = invokestatic < Application, Ljava/lang/invoke/LambdaMetafactory, apply()Ljava/util/function/BinaryOperator; > @10 exception:v7(line 6)
---
> 4   v8 = invokestatic < Application, Ljava/lang/invoke/LambdaMetafactory, accept()Ljava/util/function/Consumer; > @10 exception:v7(line 6)
```
This is the first difference. Let's see if we can change the non-working version to also utilze `apply()` as to elimate possible causes.

**Comment by khatchad** [comment]
Actually, I don't think that the parameter matters at all because I *cannot* exhibit the problem by calling `count()` and *can* exhibit by calling `toArray()`. Both take no parameters ...

**Comment by khatchad** [comment]
Turned on debug logging. Here's a log of a working instance:
```
Iteration 1
Solved 1
adding constraints
handling reflection
adding constraints again
Iteration 2
Solved 2
adding constraints
handling reflection
...
```
Here's one where it's getting stuck:
```
Iteration 1
Solved 1
adding constraints
handling reflection
adding constraints again
Iteration 2
Solved 2
adding constraints
handling reflection
```
Perhaps the handling of reflection has something to do with the problem.

**Comment by khatchad** [comment]
> Perhaps the handling of reflection has something to do with the problem.

Removing the reflection handling code doesn't seem to make a difference.

**Comment by khatchad** [comment]
This problem also seems to surface with N=1.

**Comment by khatchad** [comment]
To keep things simple, let's set N=1.

**Comment by khatchad** [comment]
OK, with N=1, actually, I can get the analysis to end within about 7 mins.

**Comment by khatchad** [comment]
It looks like the problem is as follows. Certain stream operations involve more of the JDK, When that happens, being that N=2, there are too many instances to track, making the problem intractable. In conclusion, in some situations, using N=2 is okay but not others. Closing as expected behavior.
