### ISSUE TITLE
Can't get examples to compile

### ISSUE THREAD

**Issue by sarahscheffler** [wala/WALA#170]
Hi there, originally my goal was to use WALA for static analysis of some JavaScript.  Now my goal is to get any of the examples to compile.  I'm in the JLex example.  I've done a fair amount of Java in the past, but never in Eclipse.  (By the way, a lot of the intro is very confusing, especially to someone unfamiliar with Eclipse.  But here we go.)

Originally, when I ran it using the SWTTypeHierarchy launcher in `com.ibm.wala.ide.tests/launchers/SWTTypeHierarchy.launcher`, I got an error "Variable references non-existent resource : ${resource_loc:/com.ibm.wala.core.testdata/JLex.jar}".

I figured I had just put the JLex jar in the wrong place, so I spent a while trying to fix the statement in the launcher, which reads `-classpath ${resource_loc:/com.ibm.wala.core.testdata/JLex.jar}`.

I put the JLex jar in several different places, everywhere I could think of, just to be sure.  It's in the main project folder, it's in `com.ibm.wala.core.testdata`, it's in `com.ibm.wala.core` (which is the project I'm trying to run), and it's in src and bin directories of all of these.  I also manually added JLex.jar to the Java Build Path in the properties of the `com.ibm.wala.core` project.

None of these worked.  So I said, okay, forget the JLex jar, let's just get this thing to compile.  I changed the statement, putting in things like `-classpath ${resource_loc}` and `-classpath /my/actual/path/com.ibm.wala.core.testdata/JLexjar` and some other stuff.  Whenever I do this, I get the error "Error: Could not find or load main class com.ibm.wala.examples.drivers.SWTTypeHierarchy".

I've been messing around with these for the better part of two days now, so I think it's time to ask for help.  What can I do to get these to compile?

Alternatively, is there another tutorial I can follow somewhere?  As mentioned, all I really want is to do some static analysis of some JavaScript.  At this point I'd settle for a call graph.  Does anyone have recommendations?  I looked briefly at JS_WALA, but it looks like that's a JavaScript version of WALA, not WALA designed to work on JavaScript.

Thanks for the help.

**Comment by khatchad** [comment]
The `JLex.jar` file should be at the root of your workspace directory.

**Comment by sarahscheffler** [comment]
It is there, I have my workspace set as my project root.  (I have no idea if that is a good idea or not.)  The same folder that contains all the com.ibm.wala.core, com.ibm.wala.core.testdata, etc. also contains the JLex.jar file, and is the root of my workspace directory.

(Though I don't believe this is where the SWTTypeHierarchy launcher actually looks for the jar.)

**Comment by khatchad** [comment]
@sarahscheffler As far as I understand it, you should not have the workspace as the same directory as your project in Eclipse. A workspace should have (possibly) multiple projects, each in their own directory within the workspace directory.

For example, my workspace directory is `$HOME/Workspaces/MyWorkspace` and I have WALA in `$HOME/Workspaces/MyWorkspace/WALA`. Moreover, I have the `JLex.jar` file in `$HOME/Workspaces/MyWorkspace`.

**Comment by msridhar** [comment]
@sarahscheffler My apologies for the confusing and outdated instructions.  I've updated the Getting Started document [here](https://github.com/wala/WALA/wiki/Getting-Started#running-wala-example-programs).  Basically, all you need to do is run the appropriate `mvn` or `ant` command and `JLex.jar` should be in the right place.  Can you give it a try?

**Comment by msridhar** [comment]
Regarding JS call graphs, there is some documentation here:

http://wala.sourceforge.net/wiki/index.php/Getting_Started:JavaScript_frontend

Start at the Building Call Graphs part.  I'm actively working on making this easier by adding an example to [WALA-start](https://github.com/wala/WALA-start).

**Comment by msridhar** [comment]
@sarahscheffler Ok, did an update.  Now you can build JS call graphs by doing the following (assuming you have Gradle and python installed):
```
git clone https://github.com/wala/WALA-start
cd WALA-start
./run.py com.ibm.wala.examples.drivers.JSCallGraphDriver path_to_js_file
```

That should be easier 😄 I still recommend reading [the docs](http://wala.sourceforge.net/wiki/index.php/Getting_Started:JavaScript_frontend) to understand the call graph format.  Let us know if there are other questions.
