### ISSUE TITLE
Eclipse Maven lifecycle mapping errors

### ISSUE THREAD

**Issue by liblit** [wala/WALA#198]
When I have a fresh checkout of the WALA projects in Eclipse, I often see two build errors in the Eclipse Problems view:

Description|Resource|Path|Location|Type
-|-|-|-|-
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-antrun-plugin:1.7:run (execution: default, phase: process-resources)|pom.xml|/com.ibm.wala.cast.js.nodejs|line 18|Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.eclipse.tycho:tycho-source-plugin:0.23.1:plugin-source (execution: attach-source, phase: process-classes)|pom.xml|/com.ibm.wala.cast.js.nodejs|line 5|Maven Project Build Lifecycle Mapping Problem

I usually get these to go away eventually through some combination of closing projects, reopening projects, cleaning projects, reverting project configuration changes automatically introduced by Eclipse, etc. To be honest, I am never really quite sure what I have done to make these errors go away. I hope there is a proper, permanent way to fix these instead. But I have no idea what that might be.

**Comment by msridhar** [comment]
What's the Eclipse version?

**Comment by liblit** [comment]
I have seen this most often with Eclipse Neon, as that's the version I have mainly used until now. I also see it with Eclipse Oxygen, but it's definitely not *new* to Oxygen.
