### ISSUE TITLE
Update the target platform for Tycho build?

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#199]
Currently, building WALA with Maven via Tycho [uses target platform](https://github.com/wala/WALA/blob/master/pom.xml#L107) [e44](https://github.com/wala/WALA/blob/master/targets/e44/e44.target), which I think corresponds to Eclipse Luna.  We should decide if we want to build with a more recent Eclipse version.  Eclipse Oxygen adds some new compiler warnings [which seem to be useful](https://github.com/wala/WALA/pull/197).  If we update to Oxygen we can block the build on CI if these warnings crop up again.  But, I'm not sure if there are constraints internal to IBM that prevent us from updating.

**Comment by juliandolby** [comment]
I don't think there are any internal dependencies on Eclipse versions.  We can update to whatever we prefer.

**Comment by juliandolby** [comment]
done.  now we run Oxygen on Travis CI.

**Comment by msridhar** [comment]
@juliandolby don't we also need to update the target in the main `pom.xml` file [here](https://github.com/wala/WALA/blob/2ba40c99fac5043f4914ea5eb4a4c19a57dc8d11/pom.xml#L108)?

**Comment by juliandolby** [comment]
you are right.  i had been running e47 on my machine, but somehow failed to commit that file.  done now.
