### ISSUE TITLE
Warning about not having an explicit target runtime environment configuration

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#222]
When I use `mvn install`, one of the log messages is as follows:

```
[WARNING] No explicit target runtime environment configuration. Build is platform dependent.
```

Shouldn't the run time environment be set to Java 1.8?

**Comment by msridhar** [comment]
Yeah, I've been seeing this error for years, we should fix it.  Do you know how?

**Comment by khatchad** [comment]
@msridhar Found [this thread](https://dev.eclipse.org/mhonarc/lists/tycho-user/msg00650.html):

> It's because of not specifying os/ws/arch environment(s) for your target-platform-configuration.
>
> See http://wiki.eclipse.org/Tycho/Reference_Card#Examplary_parent_POM

**Comment by liblit** [comment]
No longer relevant since switching to Gradle as the recommended build system.
