### ISSUE TITLE
remove redundant release-identifying branches

### ISSUE THREAD

**Issue by liblit** [wala/WALA#223]
The WALA git repository has two stale branches that redundantly identify tagged releases:

* git branch [`R_1.3.3`](https://github.com/wala/WALA/tree/R_1.3.3) is identical to git tag [`R_1.3.3`](https://github.com/wala/WALA/releases/tag/R_1.3.3): both refer to commit 7630cd79c9b41bdf1f26cdba491956c0cbb2aad3. The [`R_1.3.3`](https://github.com/wala/WALA/tree/R_1.3.3) branch has not changed in six years.

* git branch [`R_1.3.4`](https://github.com/wala/WALA/tree/R_1.3.4) is identical to git tag [`R_1.3.4`](https://github.com/wala/WALA/releases/tag/R_1.3.4): both refer to commit d81d8569ebb7c63915e7d03111f15fddd647e43a. The [`R_1.3.4`](https://github.com/wala/WALA/tree/R_1.3.4) branch has not changed in five years.

All other releases are marked using git tags only; these are the only two that still have named branches as well. I recommend removing the [`R_1.3.3`](https://github.com/wala/WALA/tree/R_1.3.3) and [`R_1.3.4`](https://github.com/wala/WALA/tree/R_1.3.4) branches. The same-named tags will remain, of course, to mark these releases just as we mark all other releases.

**Comment by msridhar** [comment]
Fixed, thanks
