### ISSUE TITLE
remove already-merged branches

### ISSUE THREAD

**Issue by liblit** [wala/WALA#224]
The WALA git repository has some stale branches representing changes that have already been merged into [`master`](https://github.com/wala/WALA/tree/master). Rebasing before merges has obscured the relationships between the merged commits and the named branches, but I believe that the following branches are indeed already merged in spirit:

* git branch [`ms-speed-up-cg-tests`](https://github.com/wala/WALA/tree/ms-speed-up-cg-tests) has not been modified in two months. Based on commit descriptions, this branch appears to have been rebased as fbf4ff731d34cbfb5ccd483f78a562e8230d989f  and subsequently merged into [`master`](https://github.com/wala/WALA/tree/master) in 7ea9bca169148f66c47d19ee4994824454936bc6.

* git branch [`fix-nodejs-pom`](https://github.com/wala/WALA/tree/fix-nodejs-pom) has not been modified in two months. Based on commit descriptions, this branch appears to have been rebased as 469734f61e7ccbd6d8e99cf26b102ff24e9f8cb4  and subsequently merged into [`master`](https://github.com/wala/WALA/tree/master) in 6c217a7ee4ab4559ef681e8b3fadb6d9296c261e.

If others agree that these two branches have effectively been merged into [`master`](https://github.com/wala/WALA/tree/master) by now, then the named branches should be deleted to clearly indicate that they are no longer active sites for continued development.

**Comment by msridhar** [comment]
Fixed, thanks for the report
