### ISSUE TITLE
No instruction in block when an expression is stored in its own variable

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#247]
Consider the following code:
```java
ArrayList<Object> a = new ArrayList<>();
a.stream().count();
```
which produces the following IR:
```
BB0
BB1
0   v3 = new <Application,Ljava/util/ArrayList>@0(line 20)
BB2
2   invokespecial < Application, Ljava/util/ArrayList, <init>()V > v3 @4 exception:v4(line 20)
BB3
5   v6 = invokevirtual < Application, Ljava/util/ArrayList, stream()Ljava/util/stream/Stream; > v3 @9 exception:v5(line 25) {3=[unorderedWidgets]}
BB4
6   v8 = invokeinterface < Application, Ljava/util/stream/Stream, count()J > v6 @12 exception:v7(line 25)
BB5
8   return                                   (line 70)
BB6
```
Now suppose I have a `com.ibm.wala.ipa.cfg.BasicBlockInContext<T>` that represents block `BB4`.  A `toString()` on this object produces the following:
```
ExplodedBlock[7](original:BB[SSA:6..6]4 - in.Ex.main([Ljava/lang/String;)V)
```
This block has one and only one instruction, namely, the instruction at index 6. All is well and good, specifically, if I call `com.ibm.wala.ipa.cfg.BasicBlockInContext.iterator()`, the iterator will iterate over the instruction.

Now consider the following code, which is the same as the above code but with using a separate variable:
```java
ArrayList<Object> a = new ArrayList<>();
Stream<Object> stream = a.stream();
stream.count();
```
This produces the following IR:
```
BB0
BB1
0   v3 = new <Application,Ljava/util/ArrayList>@0(line 20)
BB2
2   invokespecial < Application, Ljava/util/ArrayList, <init>()V > v3 @4 exception:v4(line 20)
BB3
5   v6 = invokevirtual < Application, Ljava/util/ArrayList, stream()Ljava/util/stream/Stream; > v3 @9 exception:v5(line 25) {3=[unorderedWidgets]}
BB4
8   v8 = invokeinterface < Application, Ljava/util/stream/Stream, count()J > v6 @14 exception:v7(line 26) {6=[stream]}
BB5
10   return                                  (line 71)
BB6
```
Notice that the instructions are basically the same with one major difference, i.e., there is now a jump in instruction indices from what was **5 to 6** is now **5 to 8**. Consequentially, the `BasicBlockInContext` representing `BB4` spans SSA 6 to 8 rather than 6 to 6:

    ExplodedBlock[7](original:BB[SSA:6..8]4 - in.Ex.main([Ljava/lang/String;)V)

However, retrieving an instruction iterator on this block returns an empty iterator. That's because the value of `com.ibm.wala.ssa.analysis.ExplodedControlFlowGraph.ExplodedBasicBlock.instructionIndex` is still 6 rather than (what looks like it should be) 8.

Questions:
1. Why is there a jump in instruction indices?
1. `com.ibm.wala.ssa.analysis.ExplodedControlFlowGraph.ExplodedBasicBlock` has a comment: `A basic block with exactly one normal instruction (which may be null), corresponding to a single instruction index in the SSA instruction array.` This doesn't seem like the right kind of block for such a block spanning multiple "instructions." Could this be a bug?

**Comment by msridhar** [comment]
@khatchad how are you constructing control-flow graphs?  An `ExplodedControlFlowGraph` is a view on a CFG where each block is allowed to have at most one instruction.  It makes expressing some analyses easier, e.g., since you don't need to worry about computing a composed transfer function for a multi-instruction basic block.  Do you want a more traditional CFG?

Regarding instruction indices, this is a historical artifact.  The WALA IR instruction array is set up to "mirror" the corresponding bytecodes for the method, so the two arrays are exactly the same length.  After conversion to three-address SSA form, some bytecode instructions (like stack manipulation instructions) no longer have a representation, so those instruction indices end up being `null`.  @sjfink might recall more details on the reason for this mirrored index scheme.

**Comment by khatchad** [comment]
@msridhar:
> how are you constructing control-flow graphs? 

https://github.com/tech-srl/safe/blob/c0a5c887c390ae419515dd1926d3bf3a2b1ea931/com.ibm.safe.typestate/src/com/ibm/safe/typestate/core/AbstractTypestateSolver.java#L772-L774

> An ExplodedControlFlowGraph is a view on a CFG where each block is allowed to have at most one instruction. It makes expressing some analyses easier, e.g., since you don't need to worry about computing a composed transfer function for a multi-instruction basic block. Do you want a more traditional CFG?

No, that sounds perfect actually.

> Regarding instruction indices, this is a historical artifact. The WALA IR instruction array is set up to "mirror" the corresponding bytecodes for the method, so the two arrays are exactly the same length. After conversion to three-address SSA form, some bytecode instructions (like stack manipulation instructions) no longer have a representation, so those instruction indices end up being null. @sjfink might recall more details on the reason for this mirrored index scheme.

OK, that makes sense. But, given this, any thoughts on how I can deal with this situation?

**Comment by msridhar** [comment]
Is the situation that you can't find the block containing the `count()` invoke instruction?  If you have the block for index 6, I think the successor will be for index 7 (also `null`), and then its successor should be for index 8.

**Comment by khatchad** [comment]
> Is the situation that you can't find the block containing the count() invoke instruction?

Not quite. I have the block, but the problem is that the block has "3 instructions" with the first two being `null`. But, as you pointed out, the block can only have *one instruction* which may be `null`.

> If you have the block for index 6, I think the successor will be for index 7 (also null), and then its successor should be for index 8.

The block as instructions 6 through 8. Since it's only supposed to hold one instruction, it just returns the null instruction at 6. It should really be returning the one at 8.

**Comment by khatchad** [comment]
> An ExplodedControlFlowGraph is a view on a CFG where each block is allowed to have at most one instruction.

How is it then possible to have:
```
ExplodedBlock[7](original:BB[SSA:6..8]4 - in.Ex.main([Ljava/lang/String;)V)
```
The exploded block here has three instructions (`6..8`)?

**Comment by khatchad** [comment]
Ah, because that is the original :). OK, I think I see what you mean by the successor.

**Comment by khatchad** [comment]
OK, so because there are three instructions between `6..8`, where should be three exploded blocks corresponding to each instruction. Indeed, there is:
```
ExplodedBlock[7](original:BB[SSA:6..8]4 - in.Ex.main([Ljava/lang/String;)V)
ExplodedBlock[8](original:BB[SSA:6..8]4 - in.Ex.main([Ljava/lang/String;)V)
ExplodedBlock[9](original:BB[SSA:6..8]4 - in.Ex.main([Ljava/lang/String;)V)
```
I have the one at index 7 but I really should have the one at index 9. Thanks for clarifying!

**Comment by msridhar** [comment]
Cool, glad we got this resolved.
