### ISSUE TITLE
IF-ELSE branches share the same condition

### ISSUE THREAD

**Issue by waooog** [wala/WALA#255]
Our tool finds the following fault-prone code snippet in the file: `com.ibm.wala.cast.js/source/com/ibm/wala/cast/js/ipa/callgraph/JSSSAPropagationCallGraphBuilder.java`

**Buggy code snippet**:
`if (constParams != null && constParams[i] != null && i >= num_pseudoargs) {
              targetVisitor.newFieldWrite(target, av, fn, constParams[i]);
  } 

else if (i >= num_pseudoargs) {
            PointerKey A = builder.getPointerKeyForLocal(caller, instruction.getUse(i));
            targetVisitor.newFieldWrite(target, av, fn, A);
          }`

In the above code snippet, the `if` branch and the following `else-if` branch share the same condition, i.e., `i >= num_pseudoargs`. If the first `if` branch is executed, the second `else-if` branch will also be executed, which may lead to unexpected logical issues.

**Comment by msridhar** [comment]
How can an if and else-if both execute? Do you have an actual input that leads to buggy behavior?

**Comment by juliandolby** [comment]
'If the first if branch is executed, the second else-if branch will also be executed' surely cannot be true.  That is the purpose of having an 'else if' rather than another if.

**Comment by waooog** [comment]
Just tested, you two are right, thanks for your quickly action. I will close this issue.
