### ISSUE TITLE
Working with WALA in Eclipse Language Server

### ISSUE THREAD

**Issue by czardoz** [wala/WALA#260]
Hello,

I'm integrating WALA into the [Eclipse Language Server](https://github.com/eclipse/eclipse.jdt.ls). It seems that WALA depends on some eclipse UI components though. For example, 

![image](https://user-images.githubusercontent.com/3726484/32975788-cf2adf6e-cbd0-11e7-814a-a531ac7bc43d.png)

[Link to source](https://github.com/wala/WALA/blob/944f620537f731ae852f43f84f58b28d9cb462c4/com.ibm.wala.ide/src/com/ibm/wala/ide/util/EclipseProjectPath.java#L355)

The JDT server does not initialize PDECore, so this ends up throwing NullPointerExceptions. Any idea how to best work around this problem? 

Thanks!

**Comment by msridhar** [comment]
> I'm integrating WALA into the Eclipse Language Server

What exactly does it mean?  WALA does have some Eclipse dependencies, but the GUI / PDE dependencies are narrowly scoped to the IDE-related code.  Any code for which there is a [Maven artifact](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.ibm.wala%22) should have no dependencies on Eclipse PDE.

**Comment by juliandolby** [comment]
If the server does not use PDECore, then it will not be able to use the parts of WALA that are integrated into the IDE, I think.  Those are meant for analyzing Eclipse projects, and so rely on Eclipse utilities.  The analysis of Java source is separate from that code, though; look at com.ibm.wala.cast.java.ecj

**Comment by czardoz** [comment]
Ah I see. That's why I was not able to construct a `WalaProjectCGModel`. 

Thanks for your help!
