### ISSUE TITLE
support invokedynamic

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#27]
This will be more important when Java 8 is released, as lambdas my be compiled using invokedynamic:

http://zeroturnaround.com/rebellabs/java-8-the-first-taste-of-lambdas/#!/

**Comment by sewe** [comment]
Are there any updates/plans on this?

FWIW, the OPAL analysis library has the very nice ability to resolve an `invokedynamic` generated by the Oracle `javac` based on its naming conventions. See <https://bitbucket.org/delors/opal/src/36975359fad1875b494f7690aafd958d9534f2bc/OPAL/br/src/main/scala/org/opalj/br/instructions/INVOKEDYNAMIC.scala?at=master#cl-95>. Maybe it is worth adding this feature to WALA as well?

**Comment by msridhar** [comment]
Julian has actually added a lot of support for invokedynamic to WALA.  @juliandolby can we close this issue?

**Comment by msridhar** [comment]
We do support lambdas now, which was the intent of this issue, so closing this.  We do not yet support other uses of invokedynamic from Java, e.g., for string concatenation in JDK 9+.  But we should open separate issues for those uses
