### ISSUE TITLE
ant scripts only download stuff

### ISSUE THREAD

**Issue by mohrm** [wala/WALA#279]
I just had a look at the ant scripts in the WALA repo. It appears to me that all they do is:
* download dependencies
* download (and maybe compile) testdata
This is not very surprising given the fact that WALA is built with maven for several years now but I ask myself if all these build.xml's could not be removed altogether? This would simplify the whole build process (since we could get rid of all the statements in the poms which merely invoke ant scripts) and may also lead to less build errors (I think everyone who builds WALA on a regular basis knows how annoying it is when the WALA build fails mere because some file could not be downloaded).
Downloading dependencies is what maven (or maybe gradle in the near) is used for, so that could be moved from ant to maven.
What could be more tricky is to get rid of downloading the test data. The obvious alternative would be to just have the test data in the WALA repo. Then it would not need to be downloaded anymore and the 'compile' step could be integrated e.g. into the process-test-resources. But I guess that there are licensing issues with that? From my perspective it should be fine for most test programs as they are distributed with liberal open source licenses but for some they may be the need to get permission.

Are there legal issues which I miss here @juliandolby ? Or are there other tasks which are performed by the ant scripts which justify their existence?

**Comment by msridhar** [comment]
This should all be cleaned up now
