### ISSUE TITLE
Problem with cpm.ibm.eala.cast.java.ecj and com.ibm.wala.cast.js.nodejs

### ISSUE THREAD

**Issue by Ameerah89** [wala/WALA#282]
Hello,

**com.ibm.wala.cast.java.ecj**  
under package com.ibm.wala.cast.java.translator.jdt, the class FakeExceptionTypeBinding giving me this error:

The type FakeExceptionTypeBinding must implement the inherited abstract method ITypeBinding.getAnchorPath()	FakeExceptionTypeBinding.java	/com.ibm.wala.cast.java.ecj/src/com/ibm/wala/cast/java/translator/jdt	line 58	Java Problem

**com.ibm.wala.cast.js.nodejs**
the build properties giving me this error:

Default encoding (UTF-8) for library "." should be removed as the workspace does not specify an explicit encoding.	build.properties	/com.ibm.wala.cast.js.nodejs	line 14	

I am using eclipse plugin for this. And I am new to WALA so I really need help with this.

Thank you

**Comment by juliandolby** [comment]
What version of Eclipse are you using?  FakeExceptionTypeBinding problems sometimes come from using older (or newer) versions of Eclipse.  I currently run with Eclipse Oxygen.2, release 4.7.2

**Comment by Ameerah89** [comment]
I am using the latest Eclipse Oxygen

**Comment by juliandolby** [comment]
Hmm.  I just got the latest Eclipse Oxygen.2 (the splash screen says December 2017) and I do not see this issue.  Could you paste what 'About Eclipse' says for you?

mine says the following:
Eclipse IDE for Eclipse Committers

Version: Oxygen.2 Release (4.7.2)
Build id: 20171218-0600

**Comment by Ameerah89** [comment]
It's working now. I download exactly the version that you use and it's work. Thank you so much.

**Comment by juliandolby** [comment]
Great.  I am curious what version you had before, though.  Did you by any chance have a pre-release of Photon (4.8)?  In general, our support tracks released versions of Eclipse but not generally pre-releases.

**Comment by Ameerah89** [comment]
I used Oxygen 4.7.2. Downloaded it from Eclipse websites. I don't know what happens too. So after you replied, I download the zip file and run the exe file instead. And it is work.
