### ISSUE TITLE
Generate CFG from source code files without dependency packages

### ISSUE THREAD

**Issue by lavenzg** [wala/WALA#284]
Previously I used WALA to generate CFGs for some jar files. I also know how to use it to get the CFGs for source code files. But now I have some java files without dependency packages. Is it still possible to generate CFGs from these files? Thanks!

**Comment by chenzhegodspeed** [comment]
Hello lavenzg,
    Can you tell me how to generate CFGS form source code files?

**Comment by zhaogang92** [comment]
@chenzhegodspeed I used the polyglot package (this may not be included in recent version of WALA). If the source code files contain dependency, this works pretty good, just like generating CFG from .jar files. But if some dependencies are missing, the generated CFGs for some methods may not be correct.
