### ISSUE TITLE
Resource leak: 's' is never closed In ClassLoaderImpl

### ISSUE THREAD

**Issue by lujiefsi** [wala/WALA#301]
In ClassLoaderImpl#314:
final JarInputStream s = new JarInputStream(new ByteArrayInputStream(jarFileContents), false);

s never close

**Comment by liblit** [comment]
The code in question uses a `try`-with-resources statement to manage the stream’s lifetime:

https://github.com/wala/WALA/blob/0286c2b0487735176fb98c526a2eddc442c324f1/com.ibm.wala.core/src/com/ibm/wala/classLoader/ClassLoaderImpl.java#L314

The stream will close upon exit from this statement, regardless of whether that happens through normal or exceptional control flow. That is, after all, exactly what `try`-with-resources statements are for.

Issue #236 notes that there are currently ten Eclipse warnings about potential resource leaks involving `JarFile`. However, the cited code on line 314 of `ClassLoaderImpl.java`, is not among them. As far as I can tell, this `ClassLoaderImpl.java` code does not leak at all.
