### ISSUE TITLE
Print IR for all source code

### ISSUE THREAD

**Issue by Ameerah89** [wala/WALA#306]
Hello,

In the PLDI tutorial, it shows an example to print IR for a function in the code. Is there any way to print IR for the whole source code?

**Comment by msridhar** [comment]
https://github.com/wala/WALA/blob/master/com.ibm.wala.core.tests/src/com/ibm/wala/examples/analysis/ConstructAllIRs.java Does that help?

**Comment by juliandolby** [comment]
If you are using the source front end, there is CAstCallGraphUtil.dumpCG, which dumps the IR along with pointer analysis information..

**Comment by Ameerah89** [comment]
I want to print the IR for nodejs. Will try the suggestion above

**Comment by liblit** [comment]
I assume that this question has been answered to @Ameerah89’s satisfaction. If not, please reopen or create a new issue.
