### ISSUE TITLE
Next WALA release on Maven Central?

### ISSUE THREAD

**Issue by anantoni** [wala/WALA#310]
Hello,

Since it's been a while (almost 10 months) since WALA 1.4.3 was released on Maven Central, is there any roadmap for the next WALA release? If not, do you guys have any plans to provide nightly snapshots of WALA in the future?

Thanks in advance,
Tony

**Comment by anantoni** [comment]
@msridhar Pinging as a reminder of my request for a new WALA release. Thanks in advance!

**Comment by msridhar** [comment]
1.5.0 is on Maven Central.  Will email out release notes (of some sort) soon
