### ISSUE TITLE
Can't build on windows 10 with jdk 8

### ISSUE THREAD

**Issue by rzs840707** [wala/WALA#323]
I am trying build wala 1.4.2 on windows environment with jdk 1.8.0_144 and maven 3.5.1. When I follow the instruction with readme and instructions on wiki page or github help, it wasn't work. I am so depressed to tell you that. 

May you tell me the way to build it on windows, or on linux environments, thanks.

**Comment by liblit** [comment]
Perhaps [the Gradle build instructions](https://github.com/wala/WALA/blob/master/README-Gradle.md) will work better for you. Please try these on Linux, as Windows is not fully supported. If you have any further, specific questions either reopen this issue or create a new one.
