### ISSUE TITLE
since ''findMethod'' has the same logic with else block, I think else block can be omitted.

### ISSUE THREAD

**Issue by jay2013** [wala/WALA#339]
https://github.com/wala/WALA/blob/d92c732decbff36dc68e45f351a94af8df9ba69b/com.ibm.wala.core/src/com/ibm/wala/ipa/cha/ClassHierarchy.java#L627

on line 624, it seems that ''findMethod" has the same logic with the else block between line 628 and 640. I think the else block can hence be omitted.

I am willing to make contribution to wala, but currently I do not know what I can do.

**Comment by msridhar** [comment]
Looks like one case returns `null` and another case returns the result of `resolveMethod`?

**Comment by msridhar** [comment]
Closing but let me know if my assessment was wrong
