### ISSUE TITLE
Why the type of classLoader of java.lang.String is Application 

### ISSUE THREAD

**Issue by lhf777111** [wala/WALA#349]
The java.lang.String is loaded by Primordial loader in the statement if "cha = ClassHierarchyFactory.make(scope);". Why the type of classLoader of java.lang.String is changed to Application later?

![1](https://user-images.githubusercontent.com/16070223/45215072-d288fc00-b2ce-11e8-9d2d-3f4af8414f3e.JPG)

**Comment by msridhar** [comment]
A `TypeReference` to a type usually uses the same class loader as the enclosing class that mentions the type.  So if an Application class refers to String, you'll see a reference like the one you posted.  If you want the resolved reference with the correct class loader, do `cha.lookupClass(ref).getReference()`.

**Comment by lhf777111** [comment]
works，thanks
