### ISSUE TITLE
Cannot retrieve Constant values from IR

### ISSUE THREAD

**Issue by Jacoppy** [wala/WALA#351]
Hi, 
I have another issue for you unfortunately. 
I have done a little apk app just for trying to extract some basic variables values , I put this sentence into the onCreate method of the MainActivity:

final int z =1000;

Now with this code section of WALA:
`SymbolTable symbols = n.getIR().getSymbolTable();

for ( int nu :symbols.getParameterValueNumbers()){
	        			System.err.println(nu);
	        			System.err.println(symbols.isIntegerConstant(nu));
	        		}`

I expect to have some true values, cause in the smali code I can see this : 

   const/16 v5, 0x3e8

Unfortunately the output is : 

Node :< Application, Lcom/example/jacopo/mwe/MainActivity, onCreate(Landroid/os/Bundle;)V >

1
false
2
false

How can I fix this? Or how can I retrieve constant values from the IR in the correct way?
Thanks

**Comment by juliandolby** [comment]
You are looking at just the parameter values, based on the method you called.  Try using a loop like the one below, to iterate across all value numbers:

```for ( int nu = 1; nu <= symbols.getMaxValueNumber())```

**Comment by Jacoppy** [comment]
It works, thank you :)
