### ISSUE TITLE
Is it possible to extract the body of an Android method

### ISSUE THREAD

**Issue by Jacoppy** [wala/WALA#354]
Hi all,
Does WALA support the extraction of the body of and Android method?
Or should I rely on another framework?
Thanks :)

**Comment by msridhar** [comment]
What do you mean "extract the body"?  Can you give an example of input and
output?

**Comment by Jacoppy** [comment]
I mean if it is possible to retrieve some sort of bytecode given a specific Activity.
Retrieving smali or dalvik bytecode...

**Comment by msridhar** [comment]
For any method coming from bytecode you can [get the Shrike instructions](https://sourcegraph.com/github.com/wala/WALA@1c6a6b0cbd2a6d747dab52ae932326c8c2b7d8cf/-/blob/com.ibm.wala.core/src/com/ibm/wala/classLoader/IBytecodeMethod.java#L43) corresponding to that method.  Not sure what format you want for dalvik bytecodes (raw bytes?) but probably wouldn't be too hard to hack WALA to get it.  But I'm guessing there might be better tools just for printing dalvik bytecodes.

**Comment by Jacoppy** [comment]
Thank you very much :)

**Comment by msridhar** [comment]
You're welcome!
