### ISSUE TITLE
Build failure issue:  Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec

### ISSUE THREAD

**Issue by levoncf** [wala/WALA#365]
Hi, I faced some troubles when I run `mvn verify -DskipTests=true -q`

**Environment :**
Apache Maven 3.5.3
Java version: 1.8.0_171
mac os x version: 10.13.3
Eclipse Java EE. Version: Oxygen.3a Release (4.7.3a)

Could anyone help me to fix this problem? Thanks a lot!

**Output is as following:** 

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] WALA 1.5.1-SNAPSHOT ................................ SUCCESS [  1.782 s]
[INFO] targets ............................................ SUCCESS [  0.017 s]
[INFO] e47 ................................................ SUCCESS [  0.181 s]
[INFO] com.ibm.wala.util .................................. SUCCESS [ 10.309 s]
[INFO] com.ibm.wala.shrike ................................ SUCCESS [  6.014 s]
[INFO] com.ibm.wala.core .................................. SUCCESS [ 21.208 s]
[INFO] com.ibm.wala.cast .................................. FAILURE [  8.032 s]
[INFO] com.ibm.wala.cast.java ............................. SKIPPED
[INFO] com.ibm.wala_feature ............................... SKIPPED
[INFO] com.ibm.wala.core.testdata ......................... SKIPPED
[INFO] com.ibm.wala.cast.java.ecj ......................... SKIPPED
[INFO] com.ibm.wala.ide ................................... SKIPPED
[INFO] com.ibm.wala.ide.jdt ............................... SKIPPED
[INFO] com.ibm.wala.core.tests ............................ SKIPPED
[INFO] com.ibm.wala.cast.test ............................. SKIPPED
[INFO] com.ibm.wala.cast.java.test ........................ SKIPPED
[INFO] com.ibm.wala.cast.java.test.data ................... SKIPPED
[INFO] com.ibm.wala.ide_feature ........................... SKIPPED
[INFO] com.ibm.wala.ide.tests ............................. SKIPPED
[INFO] com.ibm.wala.ide.jdt.test .......................... SKIPPED
[INFO] com.ibm.wala.cast.js ............................... SKIPPED
[INFO] com.ibm.wala.cast.js.rhino ......................... SKIPPED
[INFO] com.ibm.wala.cast.js.test.data ..................... SKIPPED
[INFO] com.ibm.wala.cast.js.test .......................... SKIPPED
[INFO] com.ibm.wala.cast.js.rhino.test .................... SKIPPED
[INFO] com.ibm.wala.cast.js.html.nu_validator ............. SKIPPED
[INFO] com.ibm.wala.cast.js.nodejs ........................ SKIPPED
[INFO] com.ibm.wala.cast.js.nodejs.test ................... SKIPPED
[INFO] com.ibm.wala.ide.jsdt .............................. SKIPPED
[INFO] com.ibm.wala.ide.jsdt.tests ........................ SKIPPED
[INFO] com.ibm.wala.dalvik ................................ SKIPPED
[INFO] com.ibm.wala.dalvik.test ........................... SKIPPED
[INFO] com.ibm.wala.scandroid ............................. SKIPPED
[INFO] com.ibm.wala-repository 1.5.1-SNAPSHOT ............. SKIPPED
[INFO] ------------------------------------------------------------------------
**[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 min
[INFO] Finished at: 2018-10-27T23:54:45-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (default) on project com.ibm.wala.cast: Command execution failed.: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.ibm.wala.cast**

**Comment by ForeverZyh** [comment]
I encountered the same issue. Please let me know if you have already fixed that. Thanks a lot!

**Comment by nyf429** [comment]
Are you fixed? I met the the same issue.

**Comment by z420** [comment]
I met the the same issue

**Comment by ChangWinde** [comment]
@nyf429 @z420 Did u fix it？I meet the same problem.

**Comment by z420** [comment]
> @nyf429 @z420 Did u fix it？I meet the same problem.
@ChangWinde 
放弃了，用gradle可以编译成功

**Comment by msridhar** [comment]
Maven is no longer supported for building the latest WALA master.  Please use Gradle instead (see [instructions](https://github.com/wala/WALA/blob/master/README-Gradle.md)).  Closing this issue as out-of-date
