### ISSUE TITLE
something wrong about Slice result

### ISSUE THREAD

**Issue by IscoGary** [wala/WALA#367]
![default](https://user-images.githubusercontent.com/24207891/47863771-0138d400-de33-11e8-8c62-9337e534a37d.PNG)
Hi,I try to use slicer to slice the progrm.The statement I want to slice is the parameter E e.
I send the statement [statement:  PARAM_CALLEE:Node: < Application, Llist/LinkedList, linkBefore(Ljava/lang/Object;Llist/LinkedList$Node;)V > Context: Everywhere v2] in SDG as the slice statement, the slice result is line140.But I think line141,143,145 should also show in the result.I'm confused about it.Could you please  explain it?
Thanks,
Best wishes

**Comment by msridhar** [comment]
Forward or backward slice?  Also I don't see `linkBefore` in your example.  A self-contained, reproducible example is always best for getting help

**Comment by IscoGary** [comment]
Oh sorry ，I made a mistake in last comment.That should be linkFirst,not linkBefore.And the example is forward slice.I just found that line140 contains 2 statements：
statement:  NORMAL linkFirst:5 = new <Application,Llist/LinkedList$Node>@5 Node: < Application, Llist/LinkedList, linkFirst(Ljava/lang/Object;)V > Context: Everywhere
----------140
statement:  NORMAL linkFirst:invokespecial < Application, Llist/LinkedList$Node, <init>(Llist/LinkedList$Node;Ljava/lang/Object;Llist/LinkedList$Node;)V > 5,6,2,4 @12 exception:7 Node: < Application, Llist/LinkedList, linkFirst(Ljava/lang/Object;)V > Context: Everywhere
----------140
 
The slice result of parameter E e is the second statement,while the slice result of the first statement includes line 141,143,145.
So maybe I should look for the solution.

**Comment by IscoGary** [comment]
Hello,I met a new problem.It's about options of sdg and slice .
![default](https://user-images.githubusercontent.com/24207891/47923895-8c7a9e00-def5-11e8-8bac-5b12afecca0f.PNG)

It's the same program I want to forwardSlice.The statement I want to slice is line140.As I suppose,the result is line140-145.Because line 146,147 are about instance field,I don't think it should be in the result.
Now I set `ControlDependenceOptions.NO_EXCEPTIONAL_EDGES,DataDependenceOptions`.FULL.Then the result is line 140,141,143,145 without the control block `if...else...`.
Maybe I'm wrong.Could you give me some advice?
My codes:
```
public static void main(String args[]) throws IOException, ClassHierarchyException, IllegalArgumentException,
			InvalidClassFileException, CancelException {       
                                File exFile = new FileProvider().getFile("Java60RegressionExclusions.txt");
		AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope("D:\\work\\Java\\mix\\list", exFile);
		ClassHierarchy cha = ClassHierarchyFactory.make(scope); 

		Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
		Iterable<Entrypoint> entrypoints1 = makeEntrypoints(entrypoints);
		AnalysisOptions options = new AnalysisOptions(scope, entrypoints);
		options.setReflectionOptions(ReflectionOptions.FULL);

		// build call graph
		CallGraphBuilder<InstanceKey> builder = Util.makeZeroCFABuilder(Language.JAVA, options, new AnalysisCacheImpl(),cha, scope);

		CallGraph cg = builder.makeCallGraph(options1, null);
		// Build sdg
		ModRef<InstanceKey> modRef = ModRef.make();
		final PointerAnalysis<InstanceKey> pa = builder.getPointerAnalysis();

		SDG<?> sdg = new SDG<>(cg, pa, modRef, DataDependenceOptions.FULL,ControlDependenceOptions.NO_EXCEPTIONAL_EDGES, null);

                               Statement state = getStatement(sdg, 140);//get the slice statement
		Collection<Statement> slice Slicer.computeForwardSlice(sdg, state);

		for (Statement s : slice) {
			if (s.getKind() == Statement.Kind.NORMAL) {
				printState(s);
			}
		}
                         }
```
