### ISSUE TITLE
Wala does not model Runtime.addShutdownHook

### ISSUE THREAD

**Issue by kalhauge** [wala/WALA#368]
As mentioned in #364, I'm trying to write a reachable-methods analysis in WALA, but 
I have a problem with the following program:

```
public class Main {
    public static void main( String[] argv) {
        Runtime.getRuntime().addShutdownHook(new Thread() {
            public void run() { System.out.println("Hello, World!"); }
        });
    }
}
```

So even though the program prints "Hello, World!" , the run method is not seen as 
reachable.

```
$ grep Main reachable-methods.txt
Main.main:([Ljava/lang/String;)V
Main$1."<init>":()V
```

**Comment by msridhar** [comment]
Thanks for the reports @kalhauge!  WALA models this kind of thing in `natives.xml`.  E.g. [here](https://github.com/wala/WALA/blob/0752bf321c9a62548ebe38f1dc09b882916c7130/com.ibm.wala.core/dat/natives.xml#L692) is where WALA models the fact that `doPrivileged` ends up invoking `run()` on the argument passed in.  We could do something similar to handle this case.  A PR is welcome.

**Comment by reddr** [comment]
Interesting, didn't know about this before. Is this just for call/arg mapping in general or could this also be used as a shortcut for data-dependency mapping, e.g.  if arg1 in StringBuilder.append(arg1) is tainted, put a new rule saying that the returned StringBuilder object is tainted as well, hence removing the need to analyse such commonly used framework code?

I often had this problem for Android app analysis where the trade-off was to use the Android SDK with stub implementations (no DD information) to reduce graph complexity or going with the full implementation (at least for frequently used classes/packages) to get higher accuracy but (significantly) larger processing time.

**Comment by msridhar** [comment]
@reddr sorry for the slow response.

> Interesting, didn't know about this before. Is this just for call/arg mapping in general or could this also be used as a shortcut for data-dependency mapping, e.g. if arg1 in StringBuilder.append(arg1) is tainted, put a new rule saying that the returned StringBuilder object is tainted as well, hence removing the need to analyse such commonly used framework code?

I wouldn't use the XML for this use case.  It's not really extensible and so putting in taint-analysis-specific stuff won't really work too well I think.  I would find some other way to do one-off library modeling for the taint analysis.  Is there a specific taint analyzer you're using?  I'm surprised it doesn't model the StringBuilder methods already.  Or are you building the analyzer?
