### ISSUE TITLE
Wala does not handle Thread.setDefaultUncaughtExceptionHandler

### ISSUE THREAD

**Issue by kalhauge** [wala/WALA#369]
Yet another special case, as in #368, with the same setup as #364. 

```java
public class Main implements Thread.UncaughtExceptionHandler {
  public static void main(String[] argv) {
    Thread.setDefaultUncaughtExceptionHandler(new Main());
    throw new RuntimeException();
  }
  public void uncaughtException(Thread t, Throwable e) {
    System.out.println("Hello, World!");
  }
}
```

Wala does not model the case where `Thread.setDefaultUncaughtExceptionHandler` can set up a 
handler that is called when a runtime exception is never caught.

**Comment by msridhar** [comment]
Yup, see https://github.com/wala/WALA/issues/368#issuecomment-435269842
