### ISSUE TITLE
How to get the value of Class Literal?

### ISSUE THREAD

**Issue by coder-chenzhi** [wala/WALA#387]
I want to get the value of class literal in expressions ilke `LoggerFactory.getLogger(ClassA.class)`. I can get the value of string literal in expression like `LoggerFactory.getLogger("ClassA")` by using `Instruction.getUse(int index)` and `IR.getSymbolTable().getStringValue(int index)`. But this method doesn't work for class constant. It seems that WALA doesn't handle the ClassLiteral, because SymbolTable is empty in this case.
Any hints? Thanks!

**Comment by msridhar** [comment]
I don't remember 100% but I think you should be able to use a `UseDef` to find the instruction defining the argument to `getLogger`, and that defining instruction should be an `SSALoadMetadataInstruction` whose `TypeReference` argument should give you what you need.  Does that work?

**Comment by coder-chenzhi** [comment]
@msridhar Thanks! It works!
