### ISSUE TITLE
Add something like `set -x` to scripts in travis folder

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#421]
It would be nice to be able to see which command is currently running during Travis CI jobs.  Currently we can only see which script from the `travis/` folder is running.  Can we add something like `set -x` from Bash to these scripts so they will print commands as they run?

**Comment by liblit** [comment]
Is it OK for the values of `$AUTH_TOKEN` and `$GH_TOKEN` from `travis/script-maven` to be visible in public Travis CI job logs? Or do I need to suppress that verbose output somehow?

**Comment by msridhar** [comment]
@liblit unfortunately I'm not sure about that.  I thought these things were supposed to be encrypted in some way?  I guess it's safer to suppress if we're not sure.  Sorry, wish I knew more.

**Comment by msridhar** [comment]
actually looking at [this page](https://blog.travis-ci.com/2017-05-08-security-advisory) it seems that printing these variables is a bad idea, so we should probably suppress
