### ISSUE TITLE
How to get the initial value of static field?

### ISSUE THREAD

**Issue by coder-chenzhi** [wala/WALA#431]
There are some method invocation take the value of static field as the parameter, and I want to get the  initial value of these static field.  Are there any methods like getInitialValue() can be used? Or  I have to analyze the `<clinit>` method of the class and maintain the initial values myself? Any suggestions? Thanks!

**Comment by msridhar** [comment]
There is no built-in API for getting the initial value of a static field, as far as I know.  I think your best bet is to look for the relevant `SSAPutInstruction`s inside `<clinit>`.  In the general case you'd have to do a dataflow analysis to figure out the possible values at the end of `<clinit>`.

Does that answer the question?

**Comment by coder-chenzhi** [comment]
@msridhar Thanks for your reply! I will analyze the `<clinit>` to get the initial value.
