### ISSUE TITLE
Call graph construction for constructor reference seems to be broken

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#445]
Test case:

https://github.com/wala/WALA/blob/4d4a1fda93f538aac04c575781f29a1de6f625a9/com.ibm.wala.core.testdata/src/lambda/MethodRefs.java

The key code is here:

https://github.com/wala/WALA/blob/4d4a1fda93f538aac04c575781f29a1de6f625a9/com.ibm.wala.core.testdata/src/lambda/MethodRefs.java#L74-L75

This should make `C4.target()` reachable, but when I construct a call graph for the example, it is not reachable.

I've pushed a branch `ms/test-method-refs` with the test case.  On that branch you can run `./gradlew :com.ibm.wala.core.tests:test --tests *LambdaTest.testMethodRefs*` to see the failing test.

@juliandolby can you take a look?

**Comment by juliandolby** [comment]
Definitely looks like a bug, and the pull request looks good to me.
