### ISSUE TITLE
Is it possible to filter unused classes in third-party libraries before constructing call graph?

### ISSUE THREAD

**Issue by coder-chenzhi** [wala/WALA#450]
I am working on call graph analysis on medium or large-scale software systems (100K+ LOC), but strucking in OOM error.  I have tried the solution in this [guideline](http://wala.sourceforge.net/wiki/index.php/UserGuide:PointerAnalysis) to improve the scalability. Unfortunately, I still can not address the OOM error by doing so.

I think one of the possible solution is to filter unused classes in third-party libraries before constructing call graph. Because the software under analysis depend on lots of third-party libraries (100+), but only used a few classes in these libraries. I realize that I can exclude classes by specifying `exclusionFile` when initializing  `AnalysisScope`. However, I do not know which classes of these third-party are unused in the software under analysis.

Are there other approaches to filter these unused classes? Thanks!

**Comment by msridhar** [comment]
This is a chicken-and-egg problem.  You need to compute a call graph to determine unused classes, but you'd like to filter the unused classes to compute the call graph.

My only thought is that if you can execute the relevant systems, run the JVM with `-verbose:class` to see which classes are being loaded, and use that as a guideline as to which classes can be excluded.  In some cases maybe you can remove entire jar files from the AnalysisScope.

Closing for now, but feel free to re-open if you have a follow-up question

**Comment by Fan0429** [comment]
@coder-chenzhi  你好，你也在研究wala么，可否加个QQ或者微信交流一下~？我的qq是953476101，谢谢啦
