### ISSUE TITLE
Download parser.cup file from Maven Central

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#455]
We're currently seeing Travis failures due to a failure to download http://www.cc.gatech.edu/gvu/people/faculty/hudson/java_cup/classes.v0.9e/java_cup/parser.cup.  It looks like the file is available in this jar from Maven Central, which should be a more reliable host:

https://repo1.maven.org/maven2/java_cup/java_cup/0.9e/java_cup-0.9e-sources.jar

@liblit how hard would it be to download this jar instead and extract the file we need from there?

**Comment by liblit** [comment]
Sounds doable. I'm on it. @msridhar, thanks for taking the time to find an alternate download location!
