### ISSUE TITLE
Allow using ECJ in Gradle builds

### ISSUE THREAD

**Issue by liblit** [wala/WALA#466]
If we retire the Maven build system as proposed in #379, then we will also lose our only automated test that uses Eclipse’s ECJ Java compiler. That would be unfortunate, as we do want to ensure that changes to WALA code do not produce new Eclipse build errors.

We should add an option to use ECJ in Gradle builds. This would presumably not be the default, but could be selected by using an appropriate `./gradlew` command-line flag. A Travis CI job configured to use ECJ would then help us keep everything Eclipse-clean.

**Comment by liblit** [comment]
I have [an implementation](https://github.com/wala/WALA/tree/gradle-builds-optionally-use-ecj), but it [fails JUnit checks in six tests](https://travis-ci.org/wala/WALA/jobs/528368589). For example:

```
com.ibm.wala.core.tests.ir.CFGTest > testSync1 FAILED
    java.lang.AssertionError: expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at com.ibm.wala.core.tests.ir.CFGTest.testSync1(CFGTest.java:125)
```

@msridhar or @juliandolby, do either of you know what could be going wrong with these six tests when using ECJ instead of the standard JDK 1.8 compiler?

**Comment by msridhar** [comment]
Not sure about test failures, but why not only run `assemble` with ECJ? That seems sufficient to get its static checking.

**Comment by liblit** [comment]
Do we only want ECJ for static checking, or do we also want to know that WALA runs correctly when compiled using ECJ?

**Comment by liblit** [comment]
I suppose a compromise approach would be to

1. selectively disable the six failing tests when using ECJ,
2. file a WALA bug report as a reminder to ourselves that someone should look into those failures eventually, and
3. merge the ECJ changes into `master`, so that at least we have ECJ static checking as a start.

Delaying merging the ECJ changes until all tests pass might be letting perfect be the enemy of good.

**Comment by msridhar** [comment]
I personally don't particularly care if WALA runs correctly when compiled with ECJ.  I'd rather save the CI time and just run the static checking rather than also running tests.  But I don't have a strong opinion.

**Comment by liblit** [comment]
OK, that’s easy enough. I will tweak my implementation to compile all Java code using ECJ but then switch back to (and therefore recompile using) the default compiler for running tests.

**Comment by msridhar** [comment]
So we'll get a recompile when you run `./gradlew build` and have the compiler set as ECJ?  Will the Travis CI ECJ job only run `./gradlew assemble`?

**Comment by liblit** [comment]
What I have in mind is to discard the ECJ-specific Travis CI job. Instead, the regular Travis CI jobs will do an ECJ compile of all Java code (`compileJava` and `compileTestJava` tasks), and then proceed with a regular compile and test using the default compiler. Gradle’s caching seems to understand that the Java toolchain matters, so the ECJ-compiled `.class` files will effectively be discarded and replaced by those rebuilt using the default compiler.

**Comment by msridhar** [comment]
Ah ok, sounds good.  We'll lose a bit of parallelism but I'm guessing it won't slow down builds all that much (since they are dominated by testing time).
