### ISSUE TITLE
“Could not create a entrypoint callsites:” problems

### ISSUE THREAD

**Issue by Fan0429** [wala/WALA#472]
@liblit  @msridhar  Hi, Li and msridhar . I am using WALA to conducting static analysis, but I met some problem. When I buliding call graph, some jars have these problem :

Exception in thread "main" java.lang.IllegalStateException: Could not create a entrypoint callsites: 1. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavafx/embed/swt/CustomTransfer> No superclass found for <Primordial,Ljavafx/embed/swt/CustomTransfer> Superclass name Lorg/eclipse/swt/dnd/ByteArrayTransfer 2. [Moderate] class com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion : <Primordial,Ljavafx/embed/swt/FXCanvas> No superclass found for <Primordial,Ljavafx/embed/swt/FXCanvas> Superclass name Lorg/eclipse/swt/widgets/Canvas 3. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/dnd/DragSourceListener 4. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/dnd/DropTargetListener com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder.makeCallGraph(PropagationCallGraphBuilder.java:263)

the wala seems cannot get the eclipse.swt package‘s .class file, and so I cannot build a Call Graph to slice.
Did you meet any problems like this? This problem brother me for a long time.
the problem Jar like this [：http://mirror.bit.edu.cn/apache/commons/io/binaries/](url)
the WALA version is 1.4.3.
and my code is :
`AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope(jarPath, exFile);
ClassHierarchy cha = ClassHierarchyFactory.make(scope);
			
Iterable<Entrypoint> entrypoints = Util.makeMainEntrypoints(scope, cha);
AnalysisOptions options = new AnalysisOptions(scope, entrypoints);// the problem line
options.setReflectionOptions(ReflectionOptions.NONE);`

So ,how do I deal this problem.Thank you very very much.

**Comment by Fan0429** [comment]
@juliandolby  Did you have any thoughts about this problems? Thank you very much

**Comment by msridhar** [comment]
Can you try on WALA 1.5.2?  If it still crashes, can you post the full call stack?

**Comment by Fan0429** [comment]
We have already solve the problem. We found that WALA dont't have this problem in liunx , because in windows,the WALA will call an oracle jdk jar package called jfxswt.jar, and in jfxswt.jar it depends on some of class in org.eclipse.swt package. So i delete the jfxswt.jar，the problem has been done.

**Comment by qingdujun** [comment]
> We have already solve the problem. We found that WALA dont't have this problem in liunx , because in windows,the WALA will call an oracle jdk jar package called jfxswt.jar, and in jfxswt.jar it depends on some of class in org.eclipse.swt package. So i delete the jfxswt.jar，the problem has been done.

Hello, I have the same problem.

My WALA is `1.5.3` and using `ubuntu18.04`
```
Could not create a entrypoint callsites: 1. [Moderate] class 
com.ibm.wala.ipa.cha.ClassHierarchy$ClassExclusion :
 <Application,Lcom/ibm/wala/analysis/
//...
```

I was given a error, when I called `makeCallGraph`.

```
CallGraph cg = builder.makeCallGraph(options, null);
```

**Comment by Fan0429** [comment]
@qingdujun  你好，你没有成功创建图的原因，WALA只能对含有main方法的jar包去创建图，所以会报错

**Comment by qingdujun** [comment]
> @qingdujun 你好，你没有成功创建图的原因，WALA只能对含有main方法的jar包去创建图，所以会报错


I found that WALA can set the entry itself, or use the `com.ibm.wala.ipa.callgraph.impl.AllApplicationEntrypoints;` function to create the entry, not just the `main` function.


Also, WALA can create graphs for Java Source Files.


我发现WALA可以自己设置入口，或者使用`com.ibm.wala.ipa.callgraph.impl.AllApplicationEntrypoints;`函数创建入口，不仅仅是`main`函数。


还有，WALA还可以对Java Source Files创建图。

https://github.com/wala/WALA/issues/520

**Comment by Fan0429** [comment]
> 
> 
> > @qingdujun 你好，你没有成功创建图的原因，WALA只能对含有main方法的jar包去创建图，所以会报错
> 
> I found that WALA can set the entry itself, or use the `com.ibm.wala.ipa.callgraph.impl.AllApplicationEntrypoints;` function to create the entry, not just the `main` function.
> 
> Also, WALA can create graphs for Java Source Files.
> 
> 我发现WALA可以自己设置入口，或者使用`com.ibm.wala.ipa.callgraph.impl.AllApplicationEntrypoints;`函数创建入口，不仅仅是`main`函数。
> 
> 还有，WALA还可以对Java Source Files创建图。
> 
> #520

是的，可以自己创建函数入口的，这样就可以针对入口进行创建图了。
yes，we can create our own entry point to build the call graph.

**Comment by bupt01** [comment]
Hello, sorry to bother you. I'm using My WALA 1.5.3 for development in IDEA on a Windows environment, and I encountered this issue. However, out of the many programs I tested, only one had this problem. After inspecting, I found that this program has a main function. Could you please help me understand why this is happening?

**Comment by bupt01** [comment]
I still encounter errors when running the experiment on Linux
