### ISSUE TITLE
Arguments fetching from IR is not matched original statement

### ISSUE THREAD

**Issue by NEUZhangy** [wala/WALA#509]
Hi, I am currently trying to retrieve the arguments inside the statement. In some cases, the argument in a statement might be a variable, so I use a backward slicing to fetch the actual constant value. However, I met a problem that the argument is not matching the original statement.

For the code shown below:
```java
package org.cryptoapi.bench.ecbcrypto;

import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;

public class EcbInSymmCryptoABICase1 {
    public void go(String crypto) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException {
        KeyGenerator keyGen = KeyGenerator.getInstance("AES");
        SecretKey key = keyGen.generateKey();
        Cipher cipher = Cipher.getInstance(crypto);
        cipher.init(Cipher.ENCRYPT_MODE, key);
    }

    public static void main (String [] args) throws NoSuchPaddingException, NoSuchAlgorithmException, InvalidKeyException {
        EcbInSymmCryptoABICase1 bc = new EcbInSymmCryptoABICase1();
        String crypto = "AES/ECB/PKCS5Padding";
        bc.go(crypto);
    }
}


```
When I run the backward slicing on `Cipher.getInstance(crypto)`, I will get a list of IRs. Then I retrieve the constant from the symboltable in the first IR which is shown below. However, the constant I retrieved from this IR is "AES" not "AES/ECB/PKCS5Padding".   The code I used is basically modified the code PDFSlice.java. The settings I used are:
`-callee getInstance -full none -cd none`. I have my own function to find the location of `caller`. The result of `caller` is correct since the line number of the IR matched the code file.  Besides, I developed a function that can find the correct getInstance function. 

How can I solve this issue?

The dump file is shown below:
```
Statement: NORMAL go:10 = invokestatic < Application, Ljavax/crypto/Cipher, getInstance(Ljava/lang/String;)Ljavax/crypto/Cipher; > 2 @12 exception:9 Node: < Application, Lorg/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase1, go(Ljava/lang/String;)V > Context: Everywhere
SLICE:

1   NORMAL go:10 = invokestatic < Application, Ljavax/crypto/Cipher, getInstance(Ljava/lang/String;)Ljavax/crypto/Cipher; > 2 @12 exception:9 Node: < Application, Lorg/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase1, go(Ljava/lang/String;)V > Context: Everywhere
2   PARAM_CALLEE:Node: < Application, Lorg/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase1, go(Ljava/lang/String;)V > Context: Everywhere v2
3   PARAM_CALLER:Node: < Application, Lorg/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase1, main([Ljava/lang/String;)V > Context: Everywhere[8]invokevirtual < Application, Lorg/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase1, go(Ljava/lang/String;)V > 3,5 @13 exception:6 v5
```

**Comment by msridhar** [comment]
That's a strange one.  I don't see the string `"AES"` anywhere in this code at all.  Honestly I am wondering if somehow your source code and bytecode are inconsistent?  Could you somehow decompile the bytecodes with `javap` or IntelliJ and make sure the right string constant is in the bytecode?

**Comment by msridhar** [comment]
You can also call `IR.toString()` on the IR of `main()` and see what strings you see there

**Comment by NEUZhangy** [comment]
> That's a strange one. I don't see the string `"AES"` anywhere in this code at all. Honestly I am wondering if somehow your source code and bytecode are inconsistent? Could you somehow decompile the bytecodes with `javap` or IntelliJ and make sure the right string constant is in the bytecode?

Thanks for helping me! 
"AES" is at `KeyGenerator keyGen = KeyGenerator.getInstance("AES");`. That's why I felt strange too.
The decompile bytecodes:
```
Compiled from "EcbInSymmCryptoABICase1.java"
public class org.cryptoapi.bench.ecbcrypto.EcbInSymmCryptoABICase1 {
  public org.cryptoapi.bench.ecbcrypto.EcbInSymmCryptoABICase1();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: return

  public void go(java.lang.String) throws javax.crypto.NoSuchPaddingException, java.security.NoSuchAlgorithmException, java.security.InvalidKeyException;
    Code:
       0: ldc           #2                  // String AES
       2: invokestatic  #3                  // Method javax/crypto/KeyGenerator.getInstance:(Ljava/lang/String;)Ljavax/crypto/KeyGenerator;
       5: astore_2
       6: aload_2
       7: invokevirtual #4                  // Method javax/crypto/KeyGenerator.generateKey:()Ljavax/crypto/SecretKey;
      10: astore_3
      11: aload_1
      12: invokestatic  #5                  // Method javax/crypto/Cipher.getInstance:(Ljava/lang/String;)Ljavax/crypto/Cipher;
      15: astore        4
      17: aload         4
      19: iconst_1
      20: aload_3
      21: invokevirtual #7                  // Method javax/crypto/Cipher.init:(ILjava/security/Key;)V
      24: return

  public static void main(java.lang.String[]) throws javax.crypto.NoSuchPaddingException, java.security.NoSuchAlgorithmException, java.security.InvalidKeyException;
    Code:
       0: new           #8                  // class org/cryptoapi/bench/ecbcrypto/EcbInSymmCryptoABICase1
       3: dup
       4: invokespecial #9                  // Method "<init>":()V
       7: astore_1
       8: ldc           #10                 // String AES/ECB/PKCS5Padding
      10: astore_2
      11: aload_1
      12: aload_2
      13: invokevirtual #11                 // Method go:(Ljava/lang/String;)V
      16: return
}
```

**Comment by msridhar** [comment]
My best guess is there is a bug in your code using slicer results, rather than a bug in WALA.  I don't immediately see how it could get the constants confused across methods.  But, if you post a git repo and instructions for how to reproduce, I can take a closer look.

**Comment by NEUZhangy** [comment]
> My best guess is there is a bug in your code using slicer results, rather than a bug in WALA. I don't immediately see how it could get the constants confused across methods. But, if you post a git repo and instructions for how to reproduce, I can take a closer look.

I cannot share the whole project but I can share the file which contains the problem described above. 
Here is the link for the files: https://github.com/NEUZhangy/WALA_TEST
If the instructions are not clear enough or the code cannot run on your environment, feel free to contact me~

**Comment by msridhar** [comment]
Looking over the posted code, this doesn't look right:

https://github.com/NEUZhangy/WALA_TEST/blob/cf4a657729377d42e10af5c0c320c76fade3e039/PDFSlice.java#L288-L294

It looks like it just adds all constant values in the IR to the list.  But you only care about the argument to the method call, not all the constants at the caller.  This is why you are getting extraneous values.

I'm going to close out this issue for now as it does not seem to be a WALA bug
