### ISSUE TITLE
switch to gradle-maven-publish plugin for cutting releases

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#521]
https://github.com/vanniktech/gradle-maven-publish-plugin

Looks like a maintained version of the script we are using.  We should try it.

**Comment by msridhar** [comment]
Would still be nice to do this, for this reason alone (from [the README](https://github.com/vanniktech/gradle-maven-publish-plugin?tab=readme-ov-file#advantages-over-maven-publish)):

> Maven central integration. The plugin makes it easy to configure publishing to Maven Central with dedicated APIs to set it up and configure everything that is required. It also avoids issues like having multiple staging repositories on Sonatype OSS and supports automatic releasing without requiring any interaction with the web interface.

@liblit how hard do you think it'd be to switch our scripts over to use this?

**Comment by liblit** [comment]
Most WALA subprojects load the `publishing.gradle.kts` script, but that script itself does not export anything that importing subprojects use. The script‘s ”API“, if you want to think of it that way, is the empty set. So replacing this script with a different script should not disrupt other build logic.

Now, there are some unusual things about our publication logic. For example, we create and publish a Javadoc artifact that covers all of WALA. So we would need to figure out how to do any of these atypical things using the proposed replacement plugin. Having not looked at the latter yet, I cannot say how customizable it might be.

All in all, though, this change sounds pretty doable to me.

@msridhar, would you like me to take a swing at this change? Or are you already trying it yourself?

**Comment by msridhar** [comment]
I am not working on this. I just noticed the pain point when cutting a release today. That said I would say it is low priority and it's certainly not blocking anything critical. If you think it'd be fun to try @liblit feel free to take a crack at it 🙂
