### ISSUE TITLE
Propagation failure trying to support source-code lambdas for CAst

### ISSUE THREAD

**Issue by mattkindy-praetorian** [wala/WALA#549]
I've locally manipulated some of the code to create desugared synthetic methods and set up (dynamic) invoke instructions for lambdas using the CAst system. So far I'm mostly relying on a modified version of the `LambdaTargetMethodSelector` to handle construction of the lambda summary class and redirection.

However, in In `com/ibm/wala/ipa/callgraph/propagation/SSAPropagationCallGraphBuilder.java`, I noticed that whenever I get to an instruction like 
```
4 = invokeinterface < Source, LMyFunctionalInterface, applyFn(I)I > 2,5 @1 exception:6
```
a side effect dispatch operator is created. This seemed normal at first (it seems this also happens with the current bytecode lambda system), but the dispatch never resolves.

I don't see the lambda summary class being discovered during propagation. I think I am probably missing the connection to the invocation of the lambda summary class somehow here

**Comment by msridhar** [comment]
@mattkindy-praetorian are you looking for some better documentation on how lambda support currently works for bytecodes?  I'm not 100% sure of the question here

**Comment by mattkindy-praetorian** [comment]
That *might* help, although I think I have a grasp on what's going on there. I guess my question would be how method summaries are managed in a more general sense

**Comment by msridhar** [comment]
Hrm, still not sure how to answer your question exactly.  This is the key code for the method summary used for lambdas:

https://github.com/wala/WALA/blob/4cc8db88d96c82b0f0312023f97d79f1aee41f79/com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaMethodTargetSelector.java#L119-L133

It generates synthetic instructions that allocate an instance of the `LambdaSummaryClass` for the lambda, set its fields, and then return the instance.  In the bytecode, there is an `invokedynamic` instruction for the lambda, and the `LambdaMethodTargetSelector` sets things up so that the call graph thinks that instruction is invoking the summary method.

At the source level, you won't see something like an `invokedynamic` instruction.  But I guess the idea would be the same?  Wherever you see a lambda value, at the IR you would want that represented by the result of a call to a summary method, i.e., an instance of the corresponding `LambdaSummaryClass`.  But you'll have to generate the call instruction invoking the summary method yourself.

**Comment by mattkindy-praetorian** [comment]
Yes, that makes sense. I had constructed my own `invokedynamic` instruction to the `LambdaMetafactory` for a lambda declaration, and it appeared that the `LambdaSummaryClass` was constructed with the appropriate bootstrap information (I had to construct my own, but it seemed to match what I observed in the byte code).

The problem is that call graph construction then fails to include the instructions for the [desugared](https://cr.openjdk.java.net/~briangoetz/lambda/lambda-translation.html) method that corresponds to the lambda body. At least it doesn't seem like I'm going down the wrong path.

**Comment by mattkindy-praetorian** [comment]
What's not particularly clear to me is when you say 

> But you'll have to generate the call instruction invoking the summary method yourself.

From inspecting the instructions output by the bytecode-based callgraph builder, it looks like the only thing that *should* be necessary is an interface invocation for the functional interface in question. So given the following example:

```
@FunctionalInterface
public interface MyFunctionalInterface {

  int functionOverInteger(int i);

}
```

```
public class Lambdas {

  public static void main(String[] args) {

    MyFunctionalInterface fi = i -> i;

    int myInt = fi.functionOverInteger(10);

  }
}
```

I get some instructions for `main` that look like
```
2 = invokestatic < Primordial, Ljava/lang/invoke/LambdaMetafactory, functionOverInteger()LMyFunctionalInterface; > @0 exception:3
4 = invokeinterface < Source, LMyFunctionalInterface, functionOverInteger(I)I > 2,5 @1 exception:6
```

or 
```
BB1
0   v2 = invokestatic < Primordial, Ljava/lang/invoke/LambdaMetafactory, functionOverInteger()LMyFunctionalInterface; > @0 exception:v3Lambdas.java [5:26] -> [5:37] [2=[fi]]
1   v4 = invokeinterface < Source, LMyFunctionalInterface, functionOverInteger(I)I > v2,v5:#10 @1 exception:v6Lambdas.java [7:16] -> [7:42] [4=[myInt]2=[fi]]
``` 
if you prefer.

But during callgraph construction, the bytecode is traversed in such a way that this `invokeinterface` call eventually is resolved to invoke the `LambdaSummaryClass` (e.g. something like `Lwala/lambda$Lambas$0` method `functionOverInteger(I)I`) and that of course proxies to `lambda$main$0(I)I` by design. 

I don't see any particular instruction that does this though. Instead, the `SSAPropagationCallGraphBuilder` creates a `DispatchOperator` in `visitInvokeInternal` for the `invokeinterface` call, and the bytecode proceeds through a number of different instructions (presumably related to the `LambdaMetafactory` but I'm not sure how to verify this) until it eventually lands on the summary class.

So it's not clear to me whether my `invokeinterface` instruction for a functional interface should be sufficient to lead the call graph builder to the summary class (my original thought here was "yes" since there's a variable reference to the output of the `invokedynamic` call that's being invoked upon) or whether there's a step that I'm missing here. Maybe you can shine some light on that?

**Comment by msridhar** [comment]
Ok, I think I'm understanding better what's happening here.  You are basically trying to generate IR for the source front-end roughly identical to what gets generated for lambda bytecodes, including an `invokedynamic` instruction.  Then the hope is that the `LambdaMethodTargetSelector` will just do its job and the call graph will look fine.  Is that correct?

I'm surprised that the IR instructions print as `invokestatic` when they should be `invokedynamic`; we should probably fix that.  What do you see as the target of the call to the lambda metafactory in each case (source vs. bytecode)?

The code I would be concerned about is the code for making the trampoline method:

https://github.com/wala/WALA/blob/7790a8c4453a4035390d30bd4aa7c1a226cbd5c6/com.ibm.wala.core/src/com/ibm/wala/ipa/summaries/LambdaSummaryClass.java#L312-L321

This seems to read a lot of bytecode-specific constants.  You might want to step through it with a debugger when using the source frontend to see what it is doing exactly.

**Comment by mattkindy-praetorian** [comment]
> You are basically trying to generate IR for the source front-end roughly identical to what gets generated for lambda bytecodes, including an `invokedynamic` instruction. Then the hope is that the `LambdaMethodTargetSelector` will just do its job and the call graph will look fine. Is that correct?

That's right.

> I'm surprised that the IR instructions print as `invokestatic` when they should be `invokedynamic`; we should probably fix that. What do you see as the target of the call to the lambda metafactory in each case (source vs. bytecode)?

During call graph generation for bytecode, the declaredTarget I see for the metafactory invocation is 
```
< Application, Ljava/lang/invoke/LambdaMetafactory, functionOverInteger()LMyFunctionalInterface; >
```
which gets handled in `LambdaMethodTargetSelector::getCalleeTarget` to get the summary  
```
synthetic < Application, Ljava/lang/invoke/LambdaMetafactory, functionOverInteger$Lambdas$0()LMyFunctionalInterface; >
```

For source code:
```
< Primordial, Ljava/lang/invoke/LambdaMetafactory, functionOverInteger()LMyFunctionalInterface; >
```
which has summary
```
synthetic < Primordial, Ljava/lang/invoke/LambdaMetafactory, functionOverInteger$Lambdas$0()LMyFunctionalInterface; >
```
(well that seems like it's the issue perhaps)

Regarding  `invokestatic` on the instruction: that seems to come from the `LambdaMetafactory` callsite reference. The only values I see for `Dispatch` code are `VIRTUAL`, `SPECIAL`, `INTERFACE`, `STATIC`. 

For the CAst to IR translator, I basically use `doMaterializeFunction` to handle lambda creation. Here's my source for that (admittedly hacky):

```
@Override
  protected void doMaterializeFunction(CAstNode n, WalkContext context, int result, int exception, CAstEntity fn) {

    final JDTJava2CAstTranslator<Position>.LambdaEntity lambdaEntity = (JDTJava2CAstTranslator<Position>.LambdaEntity) fn;
    final CAstType.Method methodType = (Method) fn.getType();

    final int lambdaIndex = lambdaEntity.getLambdaIndex();

    final IncipientCFG cfg = context.cfg();
    int currentInstruction = cfg.getCurrentInstruction();

    // Lambda Capture: invokedynamic call site
    final String enclosingClass = methodType.getDeclaringType().getName();

    final String variableDescriptors = lambdaEntity
      .getCapturedVariables()
      .stream()
      .map((IVariableBinding capturedVariable) -> capturedVariable.getType().getBinaryName())
      .collect(joining(","));

    final Selector metaFactorySelector =
      Selector.make(lambdaEntity.getName() + "(" + variableDescriptors + ")" + enclosingClass);

    final MethodReference lambdaFactoryConstructor =
      MethodReference.findOrCreate(LambdaMetaFactory, metaFactorySelector);

    int[] args = new int[0]; // TODO captured values go here

    final CallSiteReference callSiteReference =
      CallSiteReference.make(currentInstruction, lambdaFactoryConstructor, STATIC);

    final MethodHandleData methodHandle = MethodHandleData
      .builder()
      .invokeType((byte) REF_INVOKESTATIC)
      .methodClass(lambdaEntity.getEnclosingClass())
      .methodName(lambdaEntity.getDesugaredMethodName())
      .methodSignature(lambdaEntity.getSignature())
      .build();

    final CallArgument[] bootstrapArgs = Streams
      .concat(
        Stream.<CallArgument>of(new AstCallArgument<>(methodHandle)),
        Stream.<CallArgument>of(new AstCallArgument<>(methodHandle.getInvokeType())),
        methodType.getArgumentTypes().stream().map(AstCallArgument::new))
      .toArray(CallArgument[]::new);

    final AstBootstrapMethod bootstrap = new AstBootstrapMethod(lambdaIndex, methodHandle, bootstrapArgs);

    final SSAAbstractInvokeInstruction lambdaMetaFactoryInvocation = insts
      .InvokeInstruction(currentInstruction, result, args, exception, callSiteReference, bootstrap);

    cfg.addInstruction(lambdaMetaFactoryInvocation);
  }
```

You'll notice for bootstrap, I have a `AstBootstrapMethod`, which I've used to replace the normal constant-pool-reliant `BootstrapMethod` in this case. The code for that looks like

```
public class AstBootstrapMethod implements BootstrapMethodsReader.BootstrapMethod {

  private final int lambdaIndex;

  @NonNull
  private final MethodHandleData methodHandleData;

  @NonNull
  private final CallArgument[] arguments;

  public AstBootstrapMethod(@NonNull final int lambdaIndex,
                            @NonNull final MethodHandleData methodHandleData,
                            @NonNull final CallArgument... arguments) {
    this.lambdaIndex = lambdaIndex;
    this.methodHandleData = methodHandleData;
    this.arguments = arguments;
  }

  public MethodHandleData getMethodHandleData() {
    return this.methodHandleData;
  }

  public String getLambdaSignature() {
    return this.methodHandleData.getMethodSignature();
  }

  @Override
  public byte invokeType() {
    return this.methodHandleData.getInvokeType();
  }

  @Override
  public String methodClass() {
    return this.methodHandleData.getMethodClass();
  }

  @Override
  public String methodName() {
    return this.methodHandleData.getMethodName();
  }

  @Override
  public String methodType() {
    return this.methodHandleData.getMethodSignature();
  }

  @Override
  public int callArgumentCount() {
    return arguments.length;
  }

  @Override
  public Object callArgument(ClassLoader cl, int i) {
    return arguments[i].getArgument(cl);
  }

  @Override
  public int callArgumentIndex(int i) {
    return -1;
  }

  @Override
  public int callArgumentKind(int i) {
    return -1;
  }

  @Override
  public ConstantPoolParser getCP() {
    return null;
  }

  @Override
  public int getIndexInClassFile() {
    return lambdaIndex;
  }
}
```

One thing there is that I'm using `REF_INVOKESTATIC` (for right now) for the method handle information. Perhaps that's not right? The available codes are 
```
REF_INVOKEVIRTUAL = 5;
REF_INVOKESTATIC = 6;
REF_INVOKESPECIAL = 7;
REF_NEWINVOKESPECIAL = 8;
REF_INVOKEINTERFACE = 9;
```

Finally, I've shimmed in my `AstLambdaSummaryClass` to `LambdaSummaryClass` with the following for the relevant bootstrap methods
```
private String getLambdaCalleeClass() throws InvalidClassFileException {
    final BootstrapMethodsReader.BootstrapMethod bootstrap = invoke.getBootstrap();

    if (bootstrap instanceof AstBootstrapMethod) {
      return 'L' + ((AstBootstrapMethod) bootstrap).getMethodHandleData().getMethodClass();
    }

    int cpIndex = bootstrap.callArgumentIndex(1);
    return 'L' + bootstrap.getCP().getCPHandleClass(cpIndex);
  }

  private String getLambdaCalleeName() throws InvalidClassFileException {
    final BootstrapMethodsReader.BootstrapMethod bootstrap = invoke.getBootstrap();

    if (bootstrap instanceof AstBootstrapMethod) {
      return ((AstBootstrapMethod) bootstrap).getMethodHandleData().getMethodName();
    }

    int cpIndex = bootstrap.callArgumentIndex(1);
    return bootstrap.getCP().getCPHandleName(cpIndex);
  }

  private String getLambdaCalleeSignature() throws InvalidClassFileException {
    final BootstrapMethodsReader.BootstrapMethod bootstrap = invoke.getBootstrap();

    if (bootstrap instanceof AstBootstrapMethod) {
      return ((AstBootstrapMethod) bootstrap).getMethodHandleData().getMethodSignature();
    }

    int cpIndex = bootstrap.callArgumentIndex(1);
    return bootstrap.getCP().getCPHandleType(cpIndex);
  }

  private String getLambdaDeclaredSignature() throws InvalidClassFileException {
    final BootstrapMethodsReader.BootstrapMethod bootstrap = invoke.getBootstrap();

    if (bootstrap instanceof AstBootstrapMethod) {
      return ((AstBootstrapMethod) bootstrap).getLambdaSignature();
    }

    int cpIndex = bootstrap.callArgumentIndex(0);
    return bootstrap.getCP().getCPMethodType(cpIndex);
  }

  private int getLambdaCalleeKind() throws InvalidClassFileException {
    final BootstrapMethodsReader.BootstrapMethod bootstrap = invoke.getBootstrap();

    if (bootstrap instanceof AstBootstrapMethod) {
      return ((AstBootstrapMethod) bootstrap).getMethodHandleData().getInvokeType();
    }

    int cpIndex = bootstrap.callArgumentIndex(1);
    return bootstrap.getCP().getCPHandleKind(cpIndex);
  }
```

**Comment by mattkindy-praetorian** [comment]
The summary classes for those have instructions
```
2 = new <Primordial,Lwala/lambda$Lambdas$0>@0
return 2
```

**Comment by msridhar** [comment]
Hi @mattkindy-praetorian unfortunately I don't have time to dig super deep to help debug this issue.  My best advice is to look at the current [test cases](https://github.com/wala/WALA/tree/master/com.ibm.wala.core.testdata/src/lambda) and try to step through to see what the differences are between the bytecode front end and the source front end you are building.  It looks like you're already doing this.  You could try rewriting the `MethodRefs` tests to use lambdas instead and then see if some cases are handled and some cases aren't.

If there are other specific questions I can answer, please let me know.

**Comment by mattkindy-praetorian** [comment]
It turned out (after much debugging) that this section of code in `doMaterializeFunction`
```
final MethodReference lambdaFactoryConstructor =
      MethodReference.findOrCreate(LambdaMetaFactory, metaFactorySelector);
```
needed to be 
```
final MethodReference lambdaFactoryConstructor = MethodReference.findOrCreate(
      TypeReference.findOrCreate(SOURCE, "Ljava/lang/invoke/LambdaMetafactory"), metaFactorySelector);
```

**Comment by msridhar** [comment]
@mattkindy-praetorian so glad you figured this out.  Sorry the debugging was so painful.  Do you have any suggested changes for WALA to make this situation easier to detect in the future?  I can think about getting more visibility when `ClassHierarchy` has to deal with an exception if that would be helpful.
