### ISSUE TITLE
data-flow problem-retrive the (static) field value 

### ISSUE THREAD

**Issue by NEUZhangy** [wala/WALA#576]
I have a question regarding the data-flow problem. Currently, we are doing some static analysis about the value of parameters in some method invocations in a relative big Jar file. Our current approach is to first run the backward slicing and save into a result list, then loop this result list to get the value. Our current backward slicing options are DataDependenceOptions.NO_HEAP and ControlDependenceOptions.FULL. The entry points are using the AllApplicationEntrypoints. Since this jar file contains several different test cases.

 
But after we implement this approach, we found that this approach becomes very complicated when retrieving the value of a static field in an interprocedural scenario. For instance, as shown below, if I want to retrieve the value of keyBytes (line 52), I need to trace all the way up to line 19/21. I first need to check if the result list is in reverse order (from target statement to its parents and ancestors) and there are a lot of ParamCallee and ParamCaller needs to be handled. Besides, my program should keep updating the relationship between a static field and the value number which make my program logic cumbersome and hard to debug  
![image](https://user-images.githubusercontent.com/17584444/67729045-f709d100-f9c5-11e9-9546-69081d83b444.png)

When I check the Wala example file under the dataflow directory, I found there were some examples regarding the dataflow part. Could someone guiding me about if I can use the dataflow to solve this inter- and intra-procedural case? If so, would you mind also providing some info or hints about how I can implement this dataflow example to retrieve the value of a variable in the following example?

**Comment by msridhar** [comment]
Hi @NEUZhangy, are you trying to figure out which `String` values flow to the `key` variable?  If you could clarify the question you want answered, and what the answer would be on the example, that would be helpful.

Also, we can't see line numbers in your screenshot.

**Comment by NEUZhangy** [comment]
Hi Manu,

I have figured it out. Thanks!

- Ying

Manu Sridharan <notifications@github.com> 于2019年11月16日周六 下午9:41写道：

**Comment by msridhar** [comment]
Great!  Can you write a brief comment indicating how you solved the problem, so others can benefit as well?

**Comment by NEUZhangy** [comment]
Currently, I am testing the approach. I will update when I get time.

- Ying

Manu Sridharan <notifications@github.com> 于2019年11月16日周六 下午9:45写道：

**Comment by msridhar** [comment]
Ok, in the meantime I am going to close this issue, but @NEUZhangy it would be great if you could follow up.
