### ISSUE TITLE
"Unable to get progress logger" message

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#597]
On WALA master I am getting these new messages while building:
```
> Task :com.ibm.wala.core.testdata:downloadJavaCup
Unable to get progress logger. Download progress will not be displayed.
```

@liblit could this be related to the Gradle 6.0.1 update?  I don't remember seeing these before.

**Comment by liblit** [comment]
This is issue michel-kraemer/gradle-download-task#143 in our upstream download plugin. Claimed to be fixed in v4.0.2 of that plugin.
