### ISSUE TITLE
Use java-test-fixtures plugin for com.ibm.wala.cast.java.test

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#613]
See [this comment](https://github.com/wala/WALA/pull/612#pullrequestreview-332197057).  When we add the plugin, we should be sure that cutting artifacts (including for `com.ibm.wala.cast.java.test`) works as expected.

**Comment by liblit** [comment]
How well do we understand “works as expected”? @msridhar, what would you do by hand to skeptically check whether a pending change had broken things? Perhaps we can distill that into an automated test too!

**Comment by msridhar** [comment]
My plan is to have Maven gone before addressing this issue.  At that point, `com.ibm.wala.ide.jdt.test` will be in a separate repository and will depend on `com.ibm.wala.cast.java.test` as a Maven artifact.  Basically adding the test-fixture configuration / plugin shouldn't break that.  It may lead to a renaming of the artifact, but the artifact should still have a correct pom.xml with appropriate dependencies listed, etc.

**Comment by liblit** [comment]
c588a15f11c963fbe41f63d82322f78069ce0b4c on [the `reconcile-non-test-code-in-com.ibm.wala.cast.java.test-and-com.ibm.wala.cast.java-subprojects` branch](https://github.com/wala/WALA/tree/reconcile-non-test-code-in-com.ibm.wala.cast.java.test-and-com.ibm.wala.cast.java-subprojects) uses Gradle’s `java-test-fixtures` plugin to move `com.ibm.wala.cast.java.test`’s code into the `testFixtures` `sourceSet`. It also arranges for test-fixtures artifacts to be installed in the local Maven repository as part of the standard Gradle `install` task. These artifacts consist of three jar archives, all under `~/.m2/repository/com/ibm/wala/com.ibm.wala.cast.java.test/1.5.5-SNAPSHOT`:

* `com.ibm.wala.cast.java.test-1.5.5-SNAPSHOT-test-fixtures.jar`
* `com.ibm.wala.cast.java.test-1.5.5-SNAPSHOT-test-fixtures-javadoc.jar`
* `com.ibm.wala.cast.java.test-1.5.5-SNAPSHOT-test-fixtures-sources.jar`

This alone is not enough, though. Other existing WALA subprojects need to be updated to look for this dependency using the `test-fixtures` classifier. That has already been taken care of for Gradle builds, but I do not know Maven well enough to understand how the remaining Maven-dependent subprojects need to be updated.

Additionally, the installed `pom` file is still called `com.ibm.wala.cast.java.test-1.5.5-SNAPSHOT.pom`, and makes no mention of the artifacts with the new `test-fixtures` classifier. I don’t know whether those should be added to this existing `pom` file, or whether a new `pom` file called `com.ibm.wala.cast.java.test-1.5.5-SNAPSHOT-test-fixtures.pom` should be added instead. Presumably somewhere there needs to be a `<dependencies><dependency>...</dependency></dependencies>` element into which `<classifier>test-fixtures</classifier>` has been added along with the usual `groupId`, `artifactId`, and `version` elements.

Can you lend a hand here, @msridhar?

**Comment by liblit** [comment]
It is entirely possible that at this point it would be easier to move WALA’s Gradle builds to use [the modern `maven-publish` plugin](https://docs.gradle.org/current/userguide/publishing_maven.html) instead of the deprecated `maven` plugin. Perhaps the newer plugin already knows what should go where in any generated `pom` files. However, I probably don’t understand the Maven publishing side of things well enough to make this change myself without breaking things.

**Comment by msridhar** [comment]
This will likely take some digging. I can look but probably not for a couple of weeks or so. Thanks for getting things started @liblit!

**Comment by liblit** [comment]
By request from @msridhar, I have rebased the `reconcile-non-test-code-in-com.ibm.wala.cast.java.test-and-com.ibm.wala.cast.java-subprojects` branch mentioned [above](https://github.com/wala/WALA/issues/613#issuecomment-570099347) on the current `master` branch (commit c657201439274ccb70b5de5d546008ffa573285d). To be extra cautious, I left the original `reconcile-non-test-code-in-com.ibm.wala.cast.java.test-and-com.ibm.wala.cast.java-subprojects` branch in place, and pushed up the rebased copy as [`rebased-reconcile-non-test-code-in-com.ibm.wala.cast.java.test-and-com.ibm.wala.cast.java-subprojects`](https://github.com/wala/WALA/tree/rebased-reconcile-non-test-code-in-com.ibm.wala.cast.java.test-and-com.ibm.wala.cast.java-subprojects).

Commit c588a15f11c963fbe41f63d82322f78069ce0b4c mentioned [above](https://github.com/wala/WALA/issues/613#issuecomment-570099347) corresponds to commit e687d12dbdf4c429185d3f2812d10aa8a0d4d717 on this newly rebased branch.

**Comment by msridhar** [comment]
I added the `<classifier>` tag and fixed the corresponding Eclipse build files in 29f3e44.  There seem to be other CI failures that are unrelated to the test-fixtures change, though, as far as I can see.  @liblit can you take a quick look?  Maybe the rebase didn't go as expected

**Comment by liblit** [comment]
Thank you, @msridhar! I'll take over from here, or let you know if more @msridhar magic is needed.
