### ISSUE TITLE
get error when ./gradlew assemble

### ISSUE THREAD

**Issue by shaghayegh70** [wala/WALA#616]
Hi
I download the project and then run ./gradlew assemble in command line and get this error
![Untitled](https://user-images.githubusercontent.com/34592274/70866952-03051e80-1f85-11ea-980f-3dd5d72cdd10.png)

how could I solve this error?

**Comment by liblit** [comment]
This and other Windows build bugs were [fixed just yesterday](https://github.com/wala/WALA/pull/607). Grab a newer git commit and things should work fine. That being said, WALA has less mileage on Windows than on Linux or macOS, so please let us know if you run into other problems.

**Comment by msridhar** [comment]
Also, if you don’t need to hack on WALA itself, you are much better off pulling WALA libraries from Maven Central than building from source. See the WALA-start project for an example of that.

**Comment by shaghayegh70** [comment]
@msridhar  @liblit  thank you so0o0o much. It is built.
