### ISSUE TITLE
How to do cross-class analyze？

### ISSUE THREAD

**Issue by liberatorqjw** [wala/WALA#617]
When i analyze the source code and do the Slice, but i can not do th cross-class analyze.
is there an method to solve it?
Thank you.

**Comment by msridhar** [comment]
The slicer certainly works across methods / classes.  You need to make sure all relevant classes are in your `AnalysisScope` and things should just work.  You can also print out your `CallGraph` and make sure the calls you expect are present.

If you've done the above and it's still not working, can you post a more detailed example?

**Comment by msridhar** [comment]
Also, do you have a strong reason to analyze source code?  Could you compile and analyze the byte code instead?

**Comment by liberatorqjw** [comment]
Thanks for your help, I add the entrypoint and solve it. I have a need to deal with source code and byte code.

**Comment by xxwxxwen** [comment]
@liberatorqjw could you share how to add entrypoint for a method without mainmethod? I also need to build call graph cross-class.But I failed to build call graph for a java file without main method.Could you share how you build call graph cross-class? Thank you very much for your help!
