### ISSUE TITLE
Cleanup Util.make*CFABuilder apis to not take unnecessary AnalysisScope parameter

### ISSUE THREAD

**Issue by QRXqrx** [wala/WALA#621]
Hi,

I have noticed that one need to use `AnalysisScope` and `ClassHierarchy` several times to create a call graph. Like follows:
```
AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope(classPath, exFile);
ClassHierarchy cha = ClassHierarchyFactory.make(scope);
Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
AnalysisOptions options = new AnalysisOptions(scope, entrypoints);
CallGraphBuilder builder = Util.makeZeroCFABuilder(
         Language.JAVA, options, new AnalysisCacheImpl(), cha, scope
);
CallGraph callGraph = builder.makeCallGraph(options, null);
```
But in fact, as far as I know, the call graph result is only related to the `ClassHierarchy` parameter. So, what I want to know is that:
1. What's the meaning of repeatively passing `scope` and `cha` in? It seems it is enough to generate a call graph by pass a `scope` only once. Or is there any usage I didn't know about them?
2. Is it possible to avoid unecessary overhead in call graph generation by using a full `ClassHierarchy` and a small `AnalysisScope` as parameter-in?  Like follows:
```
public void specificAndFull() throws IOException, ClassHierarchyException, CallGraphBuilderCancelException {
    AnalysisScope specificScope = getSpecificScope(classPath);
    AnalysisScope fullScope = getFullScope(classPath);
    ClassHierarchy fullCHA = ClassHierarchyFactory.make(fullScope);
    CallGraph callGraph = getCallGraph(specificScope, fullCHA);
    ioHelper.setFileName("Specific-Full");
    ioHelper.writeCGNodeInfoIntoTXT(callGraph);
}
```
```
private CallGraph getCallGraph(AnalysisScope scope, ClassHierarchy cha) throws CallGraphBuilderCancelException {
    Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
    AnalysisOptions options = new AnalysisOptions(scope, entrypoints);
    CallGraphBuilder builder = Util.makeZeroCFABuilder(
            Language.JAVA, options, new AnalysisCacheImpl(), cha, scope
    );
    return builder.makeCallGraph(options, null);
}
```
According to the experiment result I got, it doesn't work. It seems the call graph result only related to the `ClassHierarchy` I passed.

Please reply me at your convenience, thanks a lot :-)

**Comment by msridhar** [comment]
I am not sure off the top of my head why the `scope` gets passed in separately to those methods.  In fact there is a method `com.ibm.wala.ipa.cha.IClassHierarchy#getScope` so really it's unnecessary.  It's an annoyance in the API but I wouldn't worry to much about it; it's not leading to a bunch of extra work.

Regarding your second question, it won't work to restrict the `AnalysisScope` after constructing the `ClassHierarchy`; you should construct the `ClassHierarchy` using the restricted `AnalysisScope` and then go from there.

Sorry for the confusing APIs!  I will close this issue but just comment if you have more questions

**Comment by QRXqrx** [comment]
Ok, then it is consistent to my experiment result. WALA is a really helpful tool, but it may not easy for a noob(well, someone like me) to use it. Although it really takes me some time to "guess" the usage of APIs, there still lots of things I learned through this process. Anyway, thanks a lot, may your works getting better.

**Comment by msridhar** [comment]
Feel free to keep asking questions!  Google will index these GitHub issues so hopefully it will help others.  I will re-open this issue to make it about refactoring these `Util.make*CFABuilder` APIs to avoid confusion.  We can make a new API that doesn't require the `scope` argument and then mark the old APIs as deprecated.

**Comment by msridhar** [comment]
For clarity, the `Util` class in question is this one:

https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/impl/Util.java

**Comment by QRXqrx** [comment]
Thanks for the great cleanup!

**Comment by msridhar** [comment]
Sure, the thanks belong to @jerryxu158!
