### ISSUE TITLE
How use com.ibm.wala.ipa.slicer.Slicer?

### ISSUE THREAD

**Issue by shaghayegh70** [wala/WALA#624]
Hi 
I'm not a java developer .I download and run wala project but I don't know How can I use Class Slicer in com.ibm.wala.ipa.slicer.Slicer ?
Is there any way that I put my test case in folder and then wala slice my test cases? Or Should I write a java program and in this program use this class? 
My test cases include javascript and java codes that they include security bugs!
for more detail look this link:
http://wala.sourceforge.net/javadocs/trunk/com/ibm/wala/ipa/slicer/Slicer.html

**Comment by msridhar** [comment]
See my comment on the other issue; the tutorial has some slides on the slicer.

**Comment by shaghayegh70** [comment]
@msridhar thank you but the some slider is not enough and there isn't clear and help full document about slicing the code with wala or how use the APIs
