### ISSUE TITLE
How use Wala API?

### ISSUE THREAD

**Issue by shaghayegh70** [wala/WALA#625]
Hi
I'm not a java developer. How can I use Wala API?
API Link:
https://wala.github.io/javadoc/index.html

Is this posible give me an example or tutorials?

**Comment by msridhar** [comment]
@shaghayegh70 tutorials are here:

http://wala.sourceforge.net/wiki/index.php/Tutorials

Also see the [getting started](https://github.com/wala/WALA/wiki/Getting-Started) page and [WALA-start](https://github.com/wala/WALA-start).  But, I don't think you are going to get very far without knowing Java.  I suggest learning Java before trying to dig deeply into WALA.
