### ISSUE TITLE
I get a prog-slice-master's error when run a com.ibm.wala.core.testdata

### ISSUE THREAD

**Issue by shaghayegh70** [wala/WALA#629]
I'm trying to run a com.ibm.wala.core.testdata but when I'm running the one of java program I get this error! I'm not a java developer . Is there anyone to help me?
![wala](https://user-images.githubusercontent.com/34592274/71424320-bc5ea500-26a5-11ea-9fba-4686a4cec342.png)

**Comment by msridhar** [comment]
Sorry, this is not enough info to reproduce the problem, but if you're trying to run the slicer I don't think this is the right approach.  You can see this example for how to run the slicer:

https://github.com/wala/WALA/wiki/Slicer#example

Hopefully that will get you started.  Also WALA is designed for those who have a decent Java background; it will be almost impossible to use if you don't know Java.

Let us know if you have further questions.
