### ISSUE TITLE
I have known the linenumber in the sourcecode and the cg node.

### ISSUE THREAD

**Issue by 161250029** [wala/WALA#643]
Having the condition as the title says , how can I get the instructionIndex so that I can make a nomal statement.

**Comment by msridhar** [comment]
You kind of want to do the reverse of this:

https://github.com/wala/WALA/wiki/Mapping-to-source-code#from-ir-instruction-to-bytecode-index--source-line-number

There you are given an instruction index `i` and are trying to find the source line number.  Here, I would iterate through all indices until you find an index `i` with the corresponding source line number.  As a sanity check, if you know what kind of expression you are looking for, you should see if the type of the `SSAInstruction` matches up.

Hope that helps!

**Comment by 161250029** [comment]
From source line number to  the index i of some SSAInstruction in an IR ir,how can I get it.
Given the IR ir and source line number, how can I get the index in the IR ir.
I want to know how to get the index so that I can generate the seed statement corresponding to the line number . In your reply , I cannot get an answer.

**Comment by msridhar** [comment]
My reply answers the question.  Just iterate through the SSAInstructions in the IR (using `IR.getInstructions()`) until you find one matching the desired source line.  Then you have the index.

**Comment by 161250029** [comment]
Now I get what you mean ! As is known , we can get the index only from the statement.However ,By IR.getInstructions(), we can only get the SSAInstructions.So I want to know How can I revert a SSAInstruction to Statement.

**Comment by msridhar** [comment]
`IR.getInstructions()` returns an array.  The index of an instruction in that array *is* the desired `instructionIndex`.

**Comment by 161250029** [comment]
As you say,I try the function to get seed statement. Following is my code.
public static Statement findSeedStatementByLineNumber(CGNode n, int LineNumber) throws InvalidClassFileException {
        IR ir = n.getIR();
        SSAInstruction[] ssaInstructions = ir.getInstructions();
        for (int i = 0 ; i < ssaInstructions.length ; i ++) {
            if (n.getMethod().getSourcePosition(i).getFirstLine() == LineNumber)
                return new NormalStatement(n , i);
        }
        Assertions.UNREACHABLE("failed to find LineNumber "  + " in " + n);
        return null;
    }

In the target method , the target LineNumber exists.However ,I only the assertions "failed to find LineNumber".

**Comment by msridhar** [comment]
Your code is incorrect.  See the example [here](https://github.com/wala/WALA/wiki/Mapping-to-source-code#from-ir-instruction-to-bytecode-index--source-line-number); it shows how to use `i` and `ir` to get the corresponding source line.

**Comment by 161250029** [comment]
I have got the seed statement and then call the method Slicer.computeBackwardSlice to do slice. However ,when I run it , it will cause an exception NullPointerException. I want to know why cause this exception.

**Comment by msridhar** [comment]
Please open a new issue regarding the NullPointerException with a full
stack trace and information on how to reproduce
