### ISSUE TITLE
Source code analysis across multiple files?

### ISSUE THREAD

**Issue by jfeingold35** [wala/WALA#648]
Can a JavaSourceAnalysisEngine build a callgraph from a package that contains multiple files? I'm playing around with the JavaIRTests code trying to get a handle on how everything works, and that's the only part I'm struggling with.

For example, if I define ReferencerClass and ReferencedClass1 in the same file, I'm able to build a callgraph that contains both. But if I instead define the classes in separate files (ReferencerClass.java and ReferencedClass1.java), I get an assertion failure at line 1465 of JDTJava2CAstTranslator, and nothing I've tried has managed to resolve that assertion failure.

My hope is that someone can either explain the rookie mistake I'm making, or confirm that what I'm trying to do isn't possible.

I'm attaching a few small files so people can see exactly what I'm doing.
[ThisWorksFine.txt](https://github.com/wala/WALA/files/4027113/ThisWorksFine.txt), [BrokenReferencer.txt](https://github.com/wala/WALA/files/4027112/BrokenReferencer.txt), [BrokenReferencee1.txt](https://github.com/wala/WALA/files/4027111/BrokenReferencee1.txt), and [BrokenReferencee2.txt](https://github.com/wala/WALA/files/4027110/BrokenReferencee2.txt) are all .txt conversions of .java files that live in a new package I created called `mytestpackage` at `/com.ibm.wala.cast.java.test.data/src/mytestpackage`, right next to the `p` package referenced by at least one of the tests.
[JavaIRTests.txt](https://github.com/wala/WALA/files/4027109/JavaIRTests.txt) contains the two new tests I added to the existing JavaIRTests.java file. testThisWorksFine() successfully creates a callgraph, and testBrokenReferencer() hits the assertion I mentioned.

Thanks in advance for the help, I appreciate it.

**Comment by jfeingold35** [comment]
I seem to have figured out the problem. For a package, you want to submit the entire package as a source, not a list of the files in the package.

**Comment by juliandolby** [comment]
Josh,

  This should work fine.  Looking at your code, I would suggest that the
same code in the first test should also be sufficient for your second
test.  That is, use singlePkgTestSrc for the scope in the second test too.
As long as your source files are all in that package, then cross references
should work since all the code in that package will be included.

 You likely want a different package for each test, though, so the code
does not get confused between them.

 And make sure that singlePkgTestSrc returns something useful for the entry
points for the second test.

 Let me know if you have any other questions, or if my suggestion does not
work.

  -- Julian

**Comment by tuanngokien** [comment]
I'm stucking at how to make WALA directly analyze an *.java project. 
JavaSourceAnalysisEngine couldn't build the ClassHierarchy. 
Can you tell me how you done with this?

**Comment by msridhar** [comment]
@tuanngokien I'm not too familiar with the source front end.  Can you paste the error you are getting?  I agree we should have a better code example here.  One thing you seem to be missing is setting of entrypoints.  There is some code that does that here:

https://github.com/wala/WALA/blob/master/com.ibm.wala.cast.java.ecj/src/test/java/com/ibm/wala/cast/java/test/ECJJavaIRTest.java#L32-L40

Once we work out an example here I can add it to https://github.com/wala/WALA-start and the documentation.
