### ISSUE TITLE
[Shrike] Float- and DoubleConstants instrumented as int's

### ISSUE THREAD

**Issue by RalfHerzog** [wala/WALA#649]
Hello, I am using WALA for quite a while and was wondering why adding new double/float constants do not have the expected value in the compiled bytecode.

I created a simple method which pushes a double value as a first instruction and print its value. The first instruction is pushing the constant on the stack. As expected, the value is printed on the console. For example:
```java
public class TestClass {
	public static void main(String[] args) {
		double value = Math.PI;
		System.out.println("Value starts with: " + value);
	}
}
```
Bytecode of the main-method:
```
0: Constant(D,3.141592653589793)
1: LocalStore(D,1)
2: Get(Ljava/io/PrintStream;,STATIC,Ljava/lang/System;,out)
3: LocalLoad(D,1)
4: InvokeDynamic [java/lang/invoke/StringConcatFactory:makeConcatWithConstants(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;] makeConcatWithConstants(D)Ljava/lang/String;
5: Invoke(VIRTUAL,Ljava/io/PrintStream;,println,(Ljava/lang/String;)V)
6: Return(V)
```

After using an OfflineInstrumenter and replacing (only) the first instruction (index 0 above), the compiled method does only push the int value of the new double constant, which results in the following output (example for double value 9.55555):
```java
	...
	me.replaceWith(0, new Patch() {
		@Override
		public void emitTo(Output w) {
			w.emit(ConstantInstruction.make(9.55555d));
		}
	});
	me.applyPatches();
	...
```
`Value starts with: 9.0`

The conversion issue is located in com.ibm.wala.shrike/src/com/ibm/wala/shrikeCT/ClassWriter.java in method:
```java
private void emitConstantPool() {
	...
	} else if (o instanceof Double) {
		int offset = reserveBuf(9);
		buf[offset] = CONSTANT_Double;
		setDouble(buf, offset + 1, ((Double) o).intValue());
	}
	...
}
```
Why is `intValue()` called on a new double constant? The same applies to new float constants a few lines above. If needed, I can offer a minimal example implementation.

**Comment by msridhar** [comment]
This looks like a bug to me. The fix looks pretty clear too. Ralf, any
chance you could submit a pull request to fix that includes a couple of
unit tests? Thanks!
