### ISSUE TITLE
can't understand Context

### ISSUE THREAD

**Issue by ZhangYiGang** [wala/WALA#652]
When I use callstring's context to analyze the program, I get the following results. I use bytecode.Here are my configuration options.
` Iterable<Entrypoint> entrypointsWithMainclasses = getEntryPoints();
// The entrypoints here is all the methods included in the analysis program
        AnalysisOptions realEntryPointOption = new AnalysisOptions(mScope, entrypointsWithMainclasses);
        realEntryPointOption.setReflectionOptions(AnalysisOptions.ReflectionOptions.FULL);
        Util.addDefaultSelectors(realEntryPointOption, mCha);
        Util.addDefaultBypassLogic(realEntryPointOption, mScope, BuildGraph.class.getClassLoader(), mCha);
        IAnalysisCacheView cache = new AnalysisCacheImpl();
        SSAPropagationCallGraphBuilder builder =
                new nCFABuilder(
                        3,
                        Language.JAVA.getFakeRootMethod(mCha, realEntryPointOption, cache),
                        realEntryPointOption,
                        cache,
                        null,
                        null);
        // nCFABuilder uses type-based heap abstraction by default, but we want allocation sites
        // NOTE: we disable ZeroXInstanceKeys.SMUSH_PRIMITIVE_HOLDERS for this test, since IntWrapper
        // is a primitive holder
        builder.setInstanceKeys(
                new ZeroXInstanceKeys(
                        realEntryPointOption,
                        mCha,
                        builder.getContextInterpreter(),
                        ZeroXInstanceKeys.ALLOCATIONS
                                | ZeroXInstanceKeys.SMUSH_MANY /* | ZeroXInstanceKeys.SMUSH_PRIMITIVE_HOLDERS */
                                | ZeroXInstanceKeys.SMUSH_STRINGS
                                | ZeroXInstanceKeys.SMUSH_THROWABLES));
        mBuilder = builder;
        mSdg = new SDG<>(mCg,  mBuilder.getPointerAnalysis(), ModRef.make(), Slicer.DataDependenceOptions.NO_HEAP, Slicer.ControlDependenceOptions.NONE);
`
I did not select datadependenceoptions.no_Base_ PTRs, but full.Because the former will trigger program GC exceptions.
The result of one paracaller appear as shown below.

> PARAM_CALLER:Node: < Source, Lcom/book/service/LoginService, adminRePasswd(ILjava/lang/String;)Z > Context: CallStringContext: [ com.ibm.wala.FakeRootClass.fakeRootMethod()V@258 ][4]7 = invokevirtual < Source, Lcom/book/dao/AdminDao, rePassword(ILjava/lang/String;)I > 5,2,3 @6 exception:6 v5

My question is: As mentioned in the paper TAJ,context consists of invoked method and  abstraction of object. So if @258 is the abstraction of object, why invoked method is com.ibm.wala.FakeRootClass.fakeRootMethod,rather than the method calling  **rePassword**.
Is there a problem with my understanding or with the program settings？

**Comment by msridhar** [comment]
Hi @ZhangYiGang,

For the statement you give:

> PARAM_CALLER:Node: < Source, Lcom/book/service/LoginService, adminRePasswd(ILjava/lang/String;)Z > Context: CallStringContext: [ com.ibm.wala.FakeRootClass.fakeRootMethod()V@258 ][4]7 = invokevirtual < Source, Lcom/book/dao/AdminDao, rePassword(ILjava/lang/String;)I > 5,2,3 @6 exception:6 v5

This is a `PARAM_CALLER` statement, representing a method parameter at a call site (the "actual" parameter).  The call site is within the method `adminRePasswd`.  The context is a `CallStringContext`, meaning it represents an abstraction of the call stack at the point `adminRePasswd` was invoked.  Here, I think the call string is of length 1, and the caller is the "fake root method", which WALA uses to represent calls into entrypoint methods.  I've updated the [entrypoints documention](https://github.com/wala/WALA/wiki/Pointer-Analysis#entry-points) to discuss the fake root method a bit more.

The TAJ paper is discussing an object-sensitive context.  WALA supports both call-string contexts and object contexts; you are seeing an example of the former.

Does that answer your question?

**Comment by ZhangYiGang** [comment]
Yes, Thank you very much for your reply!
