### ISSUE TITLE
Hello!I use wala for program slicing and get the statements,How can i get the actual parameters of the seed？

### ISSUE THREAD

**Issue by killerking5** [wala/WALA#653]
I want to get the actual params of seed and then determine the sources of the arguments.For example,the seed is the function that execute SQL statements,now,i want to get the actual params of this function,namely the SQL statement.Then how can i know the source of the SQL fields?

**Comment by msridhar** [comment]
You should get the IR instruction for the seed, which should be an `SSAInvokeInstruction`.  The actual parameters are the values this instruction uses.  So you can call `getNumberOfUses()` and `getUse(i)` to get the value numbers of the actual parameters.

Let me know if that doesn't answer the question.  Closing for now.  Thanks!

**Comment by killerking5** [comment]
> You should get the IR instruction for the seed, which should be an `SSAInvokeInstruction`. The actual parameters are the values this instruction uses. So you can call `getNumberOfUses()` and `getUse(i)` to get the value numbers of the actual parameters.
> 
> Let me know if that doesn't answer the question. Closing for now. Thanks!

Thank you very much! I used the functions what you mentioned,it's ok.The SSAInvokeInstruction also includes getNumberOfDefs() and getNumberOfParameters().

**Comment by killerking5** [comment]
> You should get the IR instruction for the seed, which should be an `SSAInvokeInstruction`. The actual parameters are the values this instruction uses. So you can call `getNumberOfUses()` and `getUse(i)` to get the value numbers of the actual parameters.
> 
> Let me know if that doesn't answer the question. Closing for now. Thanks!

Hello! The java project I want to analyze is a javaweb project which is implemented with spring + mybatis framework.It has no main function in class. So do I need to override the makeMainEntrypoints method?
