### ISSUE TITLE
Inconsistency in published Sonatype artifacts

### ISSUE THREAD

**Issue by sblackshear** [wala/WALA#68]
The [util](https://oss.sonatype.org/content/repositories/snapshots/com/ibm/wala/com.ibm.wala.util/) artifact was updated yesterday, but [core](https://oss.sonatype.org/content/repositories/snapshots/com/ibm/wala/com.ibm.wala.core/) and [shrike](https://oss.sonatype.org/content/repositories/snapshots/com/ibm/wala/com.ibm.wala.shrike/) have not been updated since November 2014. Tools that rely on both the core and util artifacts fail at runtime with errors like `java.lang.NoClassDefFoundError: com/ibm/wala/util/collections/Filter` because of the inconsistency between the artifacts.

**Comment by msridhar** [comment]
@sblackshear I just updated the core and shrike artifacts.  Can you see if this fixes the problem?

**Comment by sblackshear** [comment]
Yeah, that fixed it. Thanks!
