### ISSUE TITLE
How can I invert Collection<statement> into  Intermediate Representation like simple code.

### ISSUE THREAD

**Issue by 161250029** [wala/WALA#680]
As seen in the title, I need  Intermediate Representation to extract feature.

**Comment by msridhar** [comment]
For `NormalStatement`s you can get the `CGNode` and instruction index, or the `SSAInstruction` directly with `getInstruction()`.  For other types of statements you might need to add some custom logic.  We don't have a routine that does exactly what you want right now, but it shouldn't be hard to code up.

Does that answer your question?
