### ISSUE TITLE
Commit hello_hash.jar generated by ocamljava to repository?

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#710]
Right now for WALA core tests, we generate `hello_hash.jar` from scratch by downloading ocamljava and running it on `hello_hash.ml`.  Our regression test just checks some properties of the call graph generated from `hello_hash.jar`.

I propose we just commit `hello_hash.jar` to our repository rather than generating it from scratch.  
ocamljava hasn't been updated in years, so I don't see any issue with keeping up to date with recent versions.  Plus the ocamljava download really slows down an initial build (it is hosted on a lower-bandwidth web site rather than Maven Central).  We can keep around scripts for re-generating `hello_hash.jar` from scratch if needed.

@juliandolby @liblit thoughts?

**Comment by liblit** [comment]
Seems like a fine idea to me. I think I know how to keep the corresponding Gradle build logic in place but disabled unless needed in the future. (Disabled in a principled way, not just by commenting it out.)

**Comment by msridhar** [comment]
Cool.  Another thing I forgot to mention is that there should be no licensing issues here, since the bytecodes we are checking in are for OCaml source code that we wrote.

@liblit do you want to take a crack at this when you have time (not at all urgent), since you have an idea around preserving the relevant Gradle logic?

**Comment by liblit** [comment]
Will do.
