### ISSUE TITLE
Several questions about dependence options. And how to slice try-catch?

### ISSUE THREAD

**Issue by QRXqrx** [wala/WALA#713]
Hi there,
I have several questions about Wala dependence options:
1.What the difference between ``REFLECTION`` & ``NONE`` in ``DataDependenceOptions``, and what's the difference between ``NONE`` & ``NO_INTERPROC_NO_EXCEPTION`` in ``ControlDependenceOptions``? It seems the two pairs of options is equivalent respectively according to source code like follows:
![image](https://user-images.githubusercontent.com/49576982/75650088-ec22be00-5c8f-11ea-8ffd-d319ff97f90c.png)
But in fact, I did observe great difference in slice results when using different options. So I guess they are not just simply different in ``name``, there must be other distinction. I'm curious about the reason behind it.

2.How one treat ``try-catch`` statement when doing program analysis? Maybe we should treat it as a control statement I guess. If I want to slice the following statements out completely, want should I do?
```
     try {
            aStar0.distanceBetween(graph_Vertex1, graph_Vertex0);
            org.junit.Assert.fail("Expecting exception: NullPointerException");
        } catch (java.lang.NullPointerException e) {
            org.evosuite.runtime.EvoAssertions.verifyException("net.mooctest.AStar", e);
        }
```
 
Please reply me at your convenience, wish your a nice day :-), thx!

**Comment by msridhar** [comment]
My apologies for the slow response here.

> 1.What the difference between REFLECTION & NONE in DataDependenceOptions, and what's the difference between NONE & NO_INTERPROC_NO_EXCEPTION in ControlDependenceOptions? 

Good question!  The key here is that some code checks for the `NONE` case explicitly, e.g.:

https://github.com/wala/WALA/blob/4687ae4b547fecc82f4e1bf859ff58f15109214c/com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/slicer/PDG.java#L355

So, the behavior of the `NONE` case is not entirely captured by the boolean `is*()` methods.  I will add a comment documenting this.

> 2.How one treat try-catch statement when doing program analysis?

This will depend on what your seed is, forward vs. backward slicing, etc.  But the principle is that if the seed has any (transitive) data or control dependence on code within the `try-catch`, the slicer must be configured to ignore such dependencies.  With more details on your case (like more complete code example and showing the seed) I can help more.

**Comment by QRXqrx** [comment]
@msridhar 
Thank u for your reply! Actually, what I'm trying to do is refactoring test cases(methods) which are similar to the following example:
```
@Test(timeout = 4000)
public void test() {
	ALU alu = new ALU();
	assertEquals("00000000", alu.integerRepresentation("0", 8));
	assertEquals("11111111", alu.integerRepresentation("-0", 8));
	assertEquals("11111111", alu.integerRepresentation("-1", 8));
	assertEquals("00000001", alu.integerRepresentation("1", 8));
	assertEquals("000000000", alu.floatRepresentation("0", 4, 4));
	assertEquals("NaN", alu.floatRepresentation("2", 1, 4));
	assertEquals("1000000", alu.floatRepresentation("-0", 3, 3));
	assertEquals("NaN", alu.floatRepresentation("-1",0, 1));
	assertEquals("10111", alu.floatRepresentation("-1",4, 4));
	try{
		alu.floatRepresentation("-",4, 4);
		fail();
	}catch(Exception e){
		assertTrue(e instanceof NumberFormatException);
	}

        assertEquals("0011",alu.floatRepresentation("0.1",1, 1));
	assertEquals("1011",alu.floatRepresentation("-0.1",1, 1));
}
```
This example is only a part, the original test case is much longer. From source code, It is easy for us to know that this test case has multiple test tasks at the same time. I want to split it into smaller parts, each part is represented as an independent test case, like follows:
```
	@org.junit.Test(timeout = 4000)
	public void testALUTest0() {
		ALU alu = new ALU();
		assertEquals("00000000", alu.integerRepresentation("0", 8));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest1() {
		ALU alu = new ALU();
		assertEquals("11111111", alu.integerRepresentation("-0", 8));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest2() {
		ALU alu = new ALU();
		assertEquals("11111111", alu.integerRepresentation("-1", 8));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest3() {
		ALU alu = new ALU();
		assertEquals("00000001", alu.integerRepresentation("1", 8));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest4() {
		ALU alu = new ALU();
		assertEquals("000000000", alu.floatRepresentation("0", 4, 4));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest5() {
		ALU alu = new ALU();
		assertEquals("NaN", alu.floatRepresentation("2", 1, 4));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest6() {
		ALU alu = new ALU();
		assertEquals("1000000", alu.floatRepresentation("-0", 3, 3));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest7() {
		ALU alu = new ALU();
		assertEquals("NaN", alu.floatRepresentation("-1",0, 1));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest8() {
		ALU alu = new ALU();
		assertEquals("10111", alu.floatRepresentation("-1",4, 4));
	}
/*     // try-catch fail()
        @org.junit.Test(timeout = 4000)
	public void testALUTest9() { 
		ALU alu = new ALU();
		alu.floatRepresentation("-",4, 4);
		assertTrue(e instanceof NumberFormatException);
	}

	@org.junit.Test(timeout = 4000)
	public void testALUTest10() {
		ALU alu = new ALU();
		alu.floatRepresentation("-",4, 4);
		assertEquals("0011",alu.floatRepresentation("0.1",1, 1));
	}
	@org.junit.Test(timeout = 4000)
	public void testALUTest11() {
		ALU alu = new ALU();
		alu.floatRepresentation("-",4, 4);
		assertEquals("1011",alu.floatRepresentation("-0.1",1, 1));
	}
*/
```
However, since ``org.junit.Assert.Assertion.fail()`` represent logic that should not to be executed, the ``try-catch`` block should be treated as an indivisible part and should be sliced out together(or be treated as a seed together). Souce lines within the ``try-catch`` should not appear in subsequent test methods, so test failures will occur if someone try to execute ``testALUTest9~11``, since they contain ``alu.floatRepresentation("-",4, 4);`` . This is Obviously not the result I expect because this changes the test requirements of the original test.
I use the following logic to find ``seed``s:

```
/**
 * Find seed statements for slicing by text source code line.
 *
 * @param javaSrcPath for getting source code.
 * @param cgNode Search each instruction to find a seed.
 * @param targetMethod is corresponding to target seed.
 * @return List<Statement> seeds: a List of seeds
*/
    public static List<Statement> findSeedsBySrc(String javaSrcPath, CGNode cgNode, String targetMethod) {
        List<Statement> seeds = new ArrayList<>();
        IR ir = cgNode.getIR();
        if(ir == null) {
            throw new InvalidParameterException("This node's IR is null:" + cgNode.toString());
        }

        Iterator<SSAInstruction> it = ir.iterateAllInstructions();
        while(it.hasNext()) {
            SSAInstruction ins = it.next();
            int iIndex = ins.iIndex();
            if(iIndex >= 0) {
                Statement s = new NormalStatement(cgNode, iIndex);
                String srcLine = "";
                try {
                    int srcLinuNum = AtomUtil.srcLineNumberOf(s);
                    if(srcLinuNum == -1) { // See javadoc of AtomUtil.srcLineNumberOf
                        continue;
                    }
                    srcLine = FileUtil.readContentByLineNumber(javaSrcPath, srcLinuNum);
                } catch (IOException e) {
                    System.out.println("Getting srcLine failed due to IOException, in findSeed");
                    e.printStackTrace();
                } catch (IllegalArgumentException e) {
                    // When pass a negative line number in to FileUtil.readContentByLineNumber
                    System.out.println("Getting srcLine failed due to negetive srcLine number, in findSeed");
                    e.printStackTrace();
                }
                if(srcLine.contains(targetMethod)) {
                    seeds.add(s);
                }
            }
        }
        return seeds;
    }
```
Generally, I will pass "assert" and "fail" as ``targetMethod`` to find a seed, but doing this always lead to  incompleteness. The will incur loss in test ability or make the generated test not executable. I'm using text operations as a stategy(draw out ``try-catch``s at first) to solve this problem at present, but the effect is not that good. There are always some errors if I want to make the whole process automatic.
Here is nearly all about my scenario, plz tell me if you have any advice, thx!

**Comment by msridhar** [comment]
I am trying to understand your problem.  It seems for the first few calls to `assertEquals`, the backward slice does not include previous calls to `alu.integerRepresentation` or `alu.floatRepresentation`.  However, when slicing from `assertEquals` after the `try-catch`, the slice **does** include the `alu.floatRepresentation("-",4, 4);` call within the `try-catch` block, which is not desired.  Is this what is going on?  If this is true, honestly I am not 100% sure what is going on and why `try-catch` is related.

Maybe you can make a small example, print the relevant parts of the SDG, and understand why the bad dependence occurs?  You can use code like `PDFSDG` to render things as a graph:

https://github.com/wala/WALA/blob/master/com.ibm.wala.core/src/main/java/com/ibm/wala/examples/drivers/PDFSDG.java

**Comment by msridhar** [comment]
Closing out some older issues with no follow-up in a while, but please re-open if there is still an issue
