### ISSUE TITLE
How to solve a "Could not create a entrypoint callsites" exception?

### ISSUE THREAD

**Issue by QRXqrx** [wala/WALA#721]
Hi there,
I bumped into a "Could not create a entrypoint callsites" today when slice, and here is the error stack:
```
Exception in thread "main" java.lang.IllegalStateException: Could not create a entrypoint callsites: 1. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/dnd/DragSourceListener
2. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/dnd/DropTargetListener
3. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/events/ControlListener
4. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/events/DisposeListener
5. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/events/FocusListener
6. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/events/KeyListener
7. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/events/MouseListener
8. [SEVERE] class com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning : Lorg/eclipse/swt/events/MouseTrackListener
9. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Lnetscape/javascript/JSException
10. [SEVERE] class com.ibm.wala.classLoader.ClassLoaderImpl$MultipleImplementationsWarning : Lnetscape/javascript/JSObject
11. [SEVERE] class com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder$EntrypointResolutionWarning : < Application, Lnet/logstash/logback/composite/AbstractPatternJsonProviderTest, <init>()V >([])
12. [SEVERE] class com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder$EntrypointResolutionWarning : < Application, Lnet/logstash/logback/composite/AbstractPatternJsonProviderTest, decorateParser(Lnet/logstash/logback/pattern/AbstractJsonPatternParser;)Lnet/logstash/logback/pattern/AbstractJsonPatternParser; >([],[])
13. [SEVERE] class com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder$EntrypointResolutionWarning : < Application, Lnet/logstash/logback/composite/AbstractPatternJsonProviderTest, setUp()V >([])
14. [SEVERE] class com.ibm.wala.ipa.callgraph.propagation.PropagationCallGraphBuilder$EntrypointResolutionWarning : < Application, Lnet/logstash/logback/composite/AbstractPatternJsonProviderTest, shouldDelegateToParser()V >([])
```
In fact, I encountered even more ``com.ibm.wala.classLoader.BytecodeClass$ClassNotFoundWarning`` at the very beginning, and I had solved most of them by modify the exclusions file. I don't why I still got a ``ClassNotFoundWarning`` for ``org.eclipse.swt.*`` even if I didn't exclude them any more, here's the exclusions file I used to slice:
![image](https://user-images.githubusercontent.com/49576982/76526503-92e53680-64a8-11ea-8ba5-5325184cc3ba.png)
What's more, I'd like to know how to solve ``MultipleImplementationsWarning``. I did notice that in the project I used, there indeed exists two classes under different package whice have duplicate name. I'd like to know what problems will this warning incur, and  as well as how to solve it. 

Please reply me at your convenience, thank u :-)

**Comment by msridhar** [comment]
> I don't why I still got a ClassNotFoundWarning for org.eclipse.swt.* even if I didn't exclude them any more

Can you confirm those classes are in some jar in your AnalysisScope?  Maybe they are just missing.

> What's more, I'd like to know how to solve MultipleImplementationsWarning

This doesn't directly cause any problems.  However, I believe WALA will just choose the first implementation.  The second implementataion will be ignored.  It's possible this may violate the assumptions of your analysis.

**Comment by QRXqrx** [comment]
Thank u for your reply. This problem is not that important at present, so I'll closed this issue. If I have further question, I'll reopen this issue and let you know, thx :-) !
