### ISSUE TITLE
aggregatedJavadocs task is broken

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#735]
When I run `./gradlew aggregatedJavadocs --info` locally, I see:

```
> Task :aggregatedJavadocs NO-SOURCE
Skipping task ':aggregatedJavadocs' as it has no source files and no previous output files.
```

This used to work (as of a couple of weeks ago) and was the basis for our Javadoc uploads from Travis.  Javadoc uploads are now failing, e.g., see https://travis-ci.org/github/wala/WALA/jobs/668216701.  

@liblit any idea what broke here?

**Comment by liblit** [comment]
I've reproduced the problem as described, and am investigating further.
