### ISSUE TITLE
Integrate ECJ compilation into regular build valuation

### ISSUE THREAD

**Issue by liblit** [wala/WALA#736]
Currently, compiling with ECJ instead of the standard `javac` requires a separate `./gradlew -PjavaCompiler=ecj ...` run. This makes thorough testing cumbersome: there is no one Gradle task and no one Gradle command line that can be used to perform all build validation steps we want.

Gradle has good abstractions for Java tool chains, which can be set on a task-by-task basis. In principle, it should be possible for both ECJ and standard compilation tasks to be active in a single Gradle run. They’d need different task names, different tool chains, and different output directories, but should otherwise coexist peacefully.

I have work in progress to make this happen and it’s looking good so far. I might need to request one small change from the maintainer of the ECJ Gradle plugin to make it easier for me to access the ECJ tool chain instance. But it all seems doable.

Question for @msridhar: assume I can rig this up. Which existing tasks would you want it to be a dependency of? The two obvious choices are `check` or `linters`. If triggered by `check`, then we will validate ECJ compilation as part of `./gradlew build` or `./gradlew check`, though not as part of `./gradlew test` as the latter is really just for running JUnit-style tests. Or if triggered by `linters` then we will validate ECJ compilation as part of `./gradlew linters` but not as part of `./gradlew check` or `./gradlew build`.

In the past, I favored putting all of the linters under `check` and therefore transitively under `build`. But @msridhar had different options and wanted the checks and the linters to be separate. Which would you prefer for ECJ compilation validation?

**Comment by msridhar** [comment]
Based on some quick reading, I think having `check` (and hence `build`) depend on the ECJ compilation tasks makes sense.  We just want to make sure that on CI we don't end up running the ECJ tasks twice by accident.

Can we get rid of `linters` and just use `check`?  Or is `check` a Java-specific thing?

Also, I found on [this page](https://help.eclipse.org/2020-03/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_batch_compiler.htm&resultof%3D%2522%2555%2573%2569%256e%2567%2522%2520%2522%2575%2573%2522%2520%2522%2562%2561%2574%2563%2568%2522%2520%2522%2563%256f%256d%2570%2569%256c%2565%2572%2522%2520%2522%2563%256f%256d%2570%2569%256c%2522%2520) that you can pass `-d none` to ECJ to disable generation of `.class` files.  Is this something we could try to see if it speeds up the ECJ tasks?

**Comment by liblit** [comment]
@msridhar:
> We just want to make sure that on CI we don't end up running the ECJ tasks twice by accident.

Easily done. I'll have a Gradle property, settable on the command line, that suppresses the ECJ tasks. We can use that on all but one CI job, but otherwise leave the ECJ tasks enabled by default.

> Can we get rid of `linters` and just use `check`? Or is `check` a Java-specific thing?

The `check` task is not Java specific. We could certainly move all of the current `linters` dependencies over to be `check` dependencies instead. That would be a change from your preferences as implemented in #492, but I'm fine with it if you are.

> you can pass `-d none` to ECJ to disable generation of `.class` files. Is this something we could try to see if it speeds up the ECJ tasks?

Interesting idea. That might interfere with Gradle's up-to-date checks for those tasks, but I will give it a try and see how it goes!

**Comment by msridhar** [comment]
Yeah I think I understand Gradle tasks better now 🙂 It now makes sense to me for all these tasks to happen under `check`.

**Comment by liblit** [comment]
Unfortunately there's no good way to get `-d none` onto ECJ's command line. Gradle's `JavaCompile` task class insists on adding its own `-d` flag to set the destination directory, and ECJ fails if `-d` appears twice. We cannot set the destination directory to the raw string `none` because Gradle enforces that the destination directory be a `File`. If we try to sneak `none` in as a `File`, it ends up being interpreted as a relative path and we end up with ECJ-compiled class files in `none` subdirectories of each subproject.

**Comment by msridhar** [comment]
Thanks for looking into this, @liblit.  Bummer it didn't work out.
