### ISSUE TITLE
Travis CI checks absent from pull requests

### ISSUE THREAD

**Issue by liblit** [wala/WALA#738]
Recent pull requests #733 and #737 included GitHub checks but not Travis CI checks.

#734 had Travis CI checks, but they are still marked as pending in GitHub even though [they actually finished in Travis CI quite some time ago](https://travis-ci.org/github/wala/WALA/builds/667767539?utm_source=github_status&utm_medium=notification).

#732 had Travis CI checks, correctly reported as done.

[Travis CI overall claims to be working normally.](https://www.traviscistatus.com/) Perhaps we broke the integration or hooks somehow just for WALA?

**Comment by msridhar** [comment]
I don’t know what is going on here. It’s odd that the checks start but then the feedback doesn’t come back. I suspect a Travis issue but I’ll look more closely

**Comment by msridhar** [comment]
I reset some configuration and this appears to be fixed now.  At least, Travis status was reported back on #739.  Will leave this open until we see at least one more PR go through

**Comment by liblit** [comment]
Sounds like a good plan to me. Thanks for investigating.

**Comment by msridhar** [comment]
Travis CI seems to be reporting back fine now, so I will go ahead and close
