### ISSUE TITLE
WALA giving empty points to set for pointers in JavaScript 

### ISSUE THREAD

**Issue by aliahsan07** [wala/WALA#743]
I'm iterating over all the instructions of a CGNode, then using heapModel.getPointerKeyForLocal(node, ssaVar) I get the pointer key and then use ptrAnalysis.getPointsToSet(ptrKey) to attain the points to set. But for all ptrkeys I get an empty point to set.

Example JavaScript code:

```
Example code:
var src = {}
var dest = {}

src["ext"] = {}
src["ins"] = {}
var prop = Math.random() > 0.50 ? "ext" : "ins";
var t = src[prop];
dest[prop] = t;

```
For src, dest and t the points to set is empty.

**Comment by msridhar** [comment]
Sorry for the slow response here.  I copied this script to a file and ran the JavaScript call graph builder on the file via [JSCallGraphDriver in WALA-start](https://github.com/wala/WALA-start/blob/master/src/main/java/com/ibm/wala/examples/drivers/JSCallGraphDriver.java).  I hacked the code to print some extra information about the call graph and pointer analysis; my branch is here:

https://github.com/msridhar/WALA-start/tree/extra-debug-info-js

When I run, I definitely get points-to sets for `src` and `dest`:

```
[upward:src:Node: <Code body of function Lfoo.js> Context: Everywhere] --> [SITE_IN_NODE{<Code body of function Lprologue.js>:NEW <JavaScriptLoader,LUndefined>@43 in Everywhere}, SITE_IN_NODE{<ctor for <JavaScriptLoader,LObject>>:NEW <JavaScriptLoader,LObject>@2 in Caller: Node: <Code body of function Lfoo.js> Context: Everywhere@11}]
[upward:dest:Node: <Code body of function Lfoo.js> Context: Everywhere] --> [SITE_IN_NODE{<Code body of function Lprologue.js>:NEW <JavaScriptLoader,LUndefined>@43 in Everywhere}, SITE_IN_NODE{<ctor for <JavaScriptLoader,LObject>>:NEW <JavaScriptLoader,LObject>@2 in Caller: Node: <Code body of function Lfoo.js> Context: Everywhere@15}]
```
Why does it print 'upward'?  I think what is happening is that due to the dynamic property accesses at the end of the code, WALA's correlation tracking is kicking in ([PDF of paper](https://www.franktip.org/pubs/ecoop2012.pdf)).  WALA extracts the last two statements into their own function, and analyzes that function separately for the property names `"ext"` and `"ins"`.  Here is the IR for that function:
```CFG:
BB0[-1..-2]
    -> BB1
BB1[0..4]
    -> BB2
    -> BB6
BB2[5..7]
    -> BB3
    -> BB6
BB3[8..10]
    -> BB4
    -> BB6
BB4[11..11]
    -> BB5
    -> BB6
BB5[12..12]
    -> BB6
BB6[-1..-2]
Instructions:
BB0
BB1
0   v4 = new <JavaScriptLoader,LArray>@0      [4=[arguments]]
1   v6 = global:global $$undefined            [6=[t]]
3   v10 = lexical:src@Lfoo.js                foo.js [117->120] (line 7)
4   check v10                                foo.js [117->120] (line 7)
BB2
6   v7 = prototype_values(v10)               foo.js [117->126] (line 7)
7   v8 = fieldref v7.v3                      foo.js [117->126] (line 7) [8=[t]3=[prop]]
BB3
9   v13 = lexical:dest@Lfoo.js               foo.js [128->132] (line 8)
10   check v13                               foo.js [128->132] (line 8)
BB4
11   fieldref v13.v3 = v8 = v8               foo.js [128->142] (line 8) [3=[prop]8=[t]]
BB5
12   return v8                                [8=[t]]
BB6
```
The IR variable `v8` corresponds to the `t` variable in the code.  We can see that its points-to set is not empty:
```
[Node: <Code body of function Lfoo.js/_forin_body_0> Context: property name context for SingleInstanceFilter: [ConstantKey:ext:<JavaScriptLoader,LString>] (class com.ibm.wala.ipa.callgraph.propagation.ConstantKey) over Everywhere, v8] --> [SITE_IN_NODE{<ctor for <JavaScriptLoader,LObject>>:NEW <JavaScriptLoader,LObject>@2 in Caller: Node: <Code body of function Lfoo.js> Context: Everywhere@19}]
```
Sorry for all the confusing output here.  

I am not sure what is going on in your scenario.  How is it you are figuring out which SSA locals correspond to which JavaScript local variables?

**Comment by msridhar** [comment]
Going to close this as I don't think there is a bug.  Feel free to re-open if you still think there is a WALA bug

**Comment by aliahsan07** [comment]
Went through the code, and yes you're right I do see the output. One follow up though, I see we've numerous print lines for nodes that are coming from Lprologue.js which might be useless for the purpose of analysis, is there a way that can tell me whether the current pointer key belongs to that file and can be discarded?

**Comment by aliahsan07** [comment]
```n.toString().contains("Lprologue")``` probably does the trick, but would need to make sure it doesn't filter any false negative.

**Comment by msridhar** [comment]
@aliahsan07 I think you can do `n.getMethod().getDeclaringClass().getName().toString()` and then check if that is equal to / contains `"Lprologue"`.  Does that work?

**Comment by aliahsan07** [comment]
Can't do getMethod on n. Atleast directly.

**Comment by msridhar** [comment]
`n.getNode().getMethod()`

**Comment by aliahsan07** [comment]
Also, the API doesn't support mapping from pointer variable to source variable right? Have to get the SSAVariable from IR which then gets mapped to JavaScript source variable.

**Comment by msridhar** [comment]
I actually just recently wrote some (hacky!) code for finding the source-level variable name(s) corresponding to an SSA value number:

https://github.com/wala/WALA/blob/60af67444dafe4071cd571b538cc2aff78b9d0ca/com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/callgraph/fieldbased/flowgraph/vertices/VarVertex.java#L60-L70

If you like I can extract this to a utility function and put it somewhere.

**Comment by aliahsan07** [comment]
yes please, I can add it to my fork, but this might be handy for others as well.

**Comment by aliahsan07** [comment]
hey @msridhar thank you for all the help, on extracting a new function based on dynamic accesses, why do src and dest have points to set of size 2, specifically `SITE_IN_NODE{<Code body of function Lprologue.js>:NEW <JavaScriptLoader,LUndefined>@43`.

**Comment by msridhar** [comment]
Hrm, I have no idea 😐 If you can track down the relevant code or show the points-to sets I can think about it.

Also, if you'd rather just disable the function extraction stuff I can give tips on how to do that.  Depending on what you are trying to do, it may not be necessary.

**Comment by aliahsan07** [comment]
Yeah just right now I'm looking to extract the points to set of source variables, so I can work with disable the extraction stuff. I'd like the tips, thanks @msridhar for all the trouble.

**Comment by msridhar** [comment]
Are you able to use one of these methods to get your CG builder?

https://github.com/wala/WALA/blob/448e374db2c40c148b2f6ea11fbfae287d8bcf48/com.ibm.wala.cast.js/src/main/java/com/ibm/wala/cast/js/util/JSCallGraphBuilderUtil.java#L179-L192

In any case, hopefully that code and what it calls will give you an idea of how to disable correlation tracking.
