### ISSUE TITLE
How to get slice that affect the value of a variable？

### ISSUE THREAD

**Issue by ligenPro** [wala/WALA#746]
Hi, I'm learning to use `Slicer` these days。I have a few questions, please look at my code example first：
- This is my test data：
```Java
package exc.inter;

public class Sum {

    public static void main(String[] args) {
        int current;
        int sum = 0;
        int i = 0;
        do {
            current = new Random().nextInt(10);
            if (current > 5) {
                sum = sum + current;
                i = i + 1;
            }
        }while(current > 5);
        sum = bar(sum);
        foo(sum);
    }

    static int bar(int x) {
        x = x + 1;
        return x;
    }

    static void foo(int x) {
        return;
    }
}
```
 I am using `PDFSlice` for testing，my running parameters：
- mainClass：Lexc/inter/Sum
- srcCaller：main
- srcCallee：foo
- dd：full
- cd：no_exceptional_edges
- dir：backwards

I want to get all the `statements` that affect `sum`, such as the corresponding statements in lines 22, 25, 26, 29 and 30 in the source code, but I only get the statement corresponding to line 30。

![image](https://user-images.githubusercontent.com/35886904/79209339-da7b2b80-7e75-11ea-9099-cd17bdcae932.png)

My ultimate goal is to analyze the source code that affects `sum`，how should I solve this problem？should I change the seed statement？Please reply me at your convenience, thanks a lot :-)

**Comment by msridhar** [comment]
@ligenPro I tried your example and I get many more statements in the backward slice, including the ones you expect.  I wonder if you are building the call graph correctly.  When I print `CallGraphStats.getStats(cg)` for my call graph I get:

```
Call graph stats:
  Nodes: 432
  Edges: 716
  Methods: 417
  Bytecode Bytes: 16763
```

Do you see something that large or larger?

**Comment by ligenPro** [comment]
Okay, let me double check. In addition, I would like to ask about `ControlDependenceOptions `,  what is the difference between `none` and `no_exceptional_edges` ?  I have read the source code of `ExceptionPrunedCFG`, I didn’t quite understand。I hope you can take the time to help answer

**Comment by msridhar** [comment]
> Okay, thank you, let me double check. In addition, I would like to ask about `ControlDependenceOptions `, what is the difference between `none` and `no_exceptional_edges` ? I have read the source code of `ExceptionPrunedCFG`, I didn’t quite understand。I hope you can take the time to help answer

Consider the following code:
```java
1: y = x.f;
2: z = w.f;
```
Technically, statement 2 is control-dependent on statement 1, since it only executes if 1 does not throw a `NullPointerException`.  The `NO_EXCEPTIONAL_EDGES` configuration ignores this type of control dependence, where a statement only executes if previous statements do not throw an exception.

**Comment by msridhar** [comment]
Closing for now, re-open if there is a WALA bug here
