### ISSUE TITLE
Importing to Eclipse does not work

### ISSUE THREAD

**Issue by 234235235** [wala/WALA#751]
I tried now several days already to import WALA into eclipse but always resultet in Errors. If I'm following the instrunctions on Getting Started i run in the same issues as described in #734, even though I'm using JDK8. But I still couldn find out how to resolve these issues. I also run in the git problem described in #731 which was mentioned to be fixed. 

However following my steps:
(1) I did fully delete all .gradle documents
(2) I did use a fresh workspace
(3) I cloned the git repo
(4) I installed Buildship 3.0 (no newer is found for eclipse.)
(5) I imported the WALA project as a Gradel Project using gradle 6.4 and Java JDK8.
(6) After that import I first run into:
 (a) 'Connecting Git team provider failed. See log for details.
Error connecting project WALA, no Git repositories found' (Auto Sharing Git Projects)
and successifely 
 (b) see screenshot
![image](https://user-images.githubusercontent.com/39551712/79766466-4fdc7580-8328-11ea-8a2f-e4400f08e509.png)
![image](https://user-images.githubusercontent.com/39551712/79766511-5cf96480-8328-11ea-9cc3-e154f619a2df.png)
![image](https://user-images.githubusercontent.com/39551712/79766535-64207280-8328-11ea-8c3d-5bfc201e62ad.png)
I did already search through closed issues, but did not yet find one solving my problem.

**Comment by msridhar** [comment]
@khatchad any idea what could be going wrong?

**Comment by khatchad** [comment]
@234235235 we are still looking into these errors (see https://github.com/wala/WALA/issues/742). As I can tell from your screenshot, these are all errors with `MANIFEST.MF`. I don't see any Java errors. As such, should still be able to build and run.

**Comment by 234235235** [comment]
Okay I dont know how, but maybe this was a solution (I finally got it running without any errors now):

(1) I installed gradle itself
(2) I deleted all files in WALA (.settings, .idea and .project)
(3) I did additionally run gradle cleanEclipse
(4) and gradle eclipse
(5) In eclipse i imported the project as a (Java) Project. 
(6) I choose to detect all subprojects and imported them
This somehow magically did work now, the only difference to before is that i was not using gradlew provided in the wala folder, but gradle itself.

**Comment by khatchad** [comment]
Yup, I was also able to do something similar with no errors. Ideally, my understanding is that we want to use the Buildship plug-in to import the project without these errors rather than using the eclipse gradle task.
