### ISSUE TITLE
JavaSourceAnalysisScope does not find implementation of ClassLoader

### ISSUE THREAD

**Issue by 234235235** [wala/WALA#754]
When trying to use the JavaSourceAnalysisScope, it does not find the according ClassLoader implementation (which also is not in git repo anymore?): 

(Same as #573, but no solution is mentioned there :D )

![image](https://user-images.githubusercontent.com/39551712/79872735-73fe8c00-83e6-11ea-9eb8-f02caf0134f9.png)
 In JAvaSourceAnalysisScope.java:

![image](https://user-images.githubusercontent.com/39551712/79872811-8aa4e300-83e6-11ea-9896-3db8e4fd27db.png)

Resulting (as the class does not exists anymore):

![image](https://user-images.githubusercontent.com/39551712/79872862-9db7b300-83e6-11ea-8c6f-4f8d88ff5d2a.png)

Do you know which  class to add here? i.e. maybe ECJSourceLoaderImpl? and if so how can i add it, becuase even though the class is available eclipse doesnt find it as well.

**Comment by 234235235** [comment]
P.S. it works with SourceDirectoryTreeModule (@see com.ibm.wala.cast.java.ecj project -> com.ibm.wala.cast.java.ecj.util: SourceDirCallGraph.java )

**Comment by juliandolby** [comment]
Could you post more of your code?  I suspect the issue is that you need to use the `ECJClassLoaderFactory` as it is used in `SourceDirCallGraph`.  The snippet that is likely relevant is below, but seeing more of your code might help.

`    IClassHierarchy cha =
        ClassHierarchyFactory.make(scope, new ECJClassLoaderFactory(scope.getExclusions()));
`

**Comment by 234235235** [comment]
I tried it again, this somehow works now. Simply moving the package into the com.ibm.wala.cast.java.ecj project (src/main/java/package) did resolve the issue.
