### ISSUE TITLE
Backward slice takes too long

### ISSUE THREAD

**Issue by ligenPro** [wala/WALA#758]
Hi, I am slicing my project. Here is my call graph states:
```
Call graph stats:
  Nodes: 1776
  Edges: 3354
  Methods: 1706
  Bytecode Bytes: 91860
```
I have allocated `8g` heap memory. The options for controlling dependency and data dependency are set as: `full`.

After I run `PDFSlice`, the program has not ended, has been running, and the CPU utilization has been very high. What may be the reason？

**Comment by msridhar** [comment]
I've added some discussion here:

https://github.com/wala/WALA/wiki/Slicer#performance-tips

It will be very difficult to scale the slicer with `full` dependence options.  I recommend reducing the dependencies tracked to the minimum required for your client.

**Comment by ligenPro** [comment]
@msridhar Thank you very much ！

**Comment by ligenPro** [comment]
@msridhar  Hi, I am analysing a project through slicing, but the program has been running，DataDependenceOptions：`FULL`，ControlDependenceOptions：`NO_EXCEPTIONAL_EDGES`
the running status is as follows：

![image](https://user-images.githubusercontent.com/35886904/84477082-a5e2ef00-acc1-11ea-9194-ec955b4fbd22.png)

When I exclude the entire `java.util.*` package, the slicer can run normally and exit。I would like to ask a few questions：
- What the slicer is doing, what caused the program to fail to exit
- Besides adjusting DataDependencyOption, ControlDependenceOptions, what can I do to speed up the analysis? Normally, I cannot exclude the entire `java.util.*` package ?

Please reply me at your convenience, thanks a lot
