### ISSUE TITLE
Removed parameter breaks third-party clients

### ISSUE THREAD

**Issue by khatchad** [wala/WALA#768]
We could that a parameter removed in https://github.com/wala/WALA/commit/6087b73cee366ce2f1c1b49e27d46f0ba7f33841 breaks our WALA client. Please see the description in https://github.com/wala/WALA/commit/6087b73cee366ce2f1c1b49e27d46f0ba7f33841#r38884311.

**Comment by msridhar** [comment]
Yes you are completely right.  Can you open a PR to add the parameter back, and add `@SuppressWarnings("unused")` with a comment that subclasses will use the parameter?

**Comment by khatchad** [comment]
It turns out that it is enough to simply document the parameter to avoid the warning (which is now an error). I can also add a comment if desired. Thanks!

**Comment by msridhar** [comment]
As long as we avoid the warnings that's fine!  Just submit the PR and we'll take a look.
