### ISSUE TITLE
Slicing results obtained through ZeroXContainerCFABuilder

### ISSUE THREAD

**Issue by ligenPro** [wala/WALA#782]
I am building a call graph through `ZeroXContainerCFABuilder` to slice, my source code is as follows:
- dd: `full`
- cd: `no_exceptional_edges`
- slice seed : `System.out.println()`
```Java
public class Sum {

     public static void main(String[] args) {
        Person tom = new Boy();
        Person mary = new Girl();
        tom.setAge(1);
        mary.setAge(2);

        Map<String, Person> boyMap = new HashMap<String, Person>();
        Map<String, Person> girlMap = new HashMap<String, Person>();
        boyMap.put("Tom", tom);
        girlMap.put("Mary", mary);

        Person person = girlMap.get("Mary");
        System.out.println(person.getAge());
    }
}

class Person {

    private Integer age;

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }
}

class Boy extends Person {}

class Girl extends Person {}
```
I found that the source code related to `tom` and `boyMap` are included in the slicing result. It seems that `ZeroOneContainerCFABuilder` is not working. Is it correct?

Looking forward to your reply, thank you very much !!

**Comment by msridhar** [comment]
This looks a bit strange.  Just to make sure it's not the code in the `System` class, can you try with this modified version?
```Java
public class Sum {

     public static void main(String[] args) {
        Person tom = new Boy();
        Person mary = new Girl();
        tom.setAge(1);
        mary.setAge(2);

        Map<String, Person> boyMap = new HashMap<String, Person>();
        Map<String, Person> girlMap = new HashMap<String, Person>();
        boyMap.put("Tom", tom);
        girlMap.put("Mary", mary);

        Person person = girlMap.get("Mary");
        doNothing(person.getAge());
    }

    static void doNothing(Object o) {}
}
```

Here your seed would be the call to `doNothing()`.  This way we can be sure there is an issue with analysis of maps.

Also, what version of the JDK standard library are you using?

**Comment by ligenPro** [comment]
> This looks a bit strange. Just to make sure it's not the code in the `System` class, can you try with this modified version?
> 
> ```java
> public class Sum {
> 
>      public static void main(String[] args) {
>         Person tom = new Boy();
>         Person mary = new Girl();
>         tom.setAge(1);
>         mary.setAge(2);
> 
>         Map<String, Person> boyMap = new HashMap<String, Person>();
>         Map<String, Person> girlMap = new HashMap<String, Person>();
>         boyMap.put("Tom", tom);
>         girlMap.put("Mary", mary);
> 
>         Person person = girlMap.get("Mary");
>         doNothing(person.getAge());
>     }
> 
>     static void doNothing(Object o) {}
> }
> ```
> 
> Here your seed would be the call to `doNothing()`. This way we can be sure there is an issue with analysis of maps.
> 
> Also, what version of the JDK standard library are you using?

Thank you very much for your reply ! 

I tried the method you provided, using the call to `doNothing` as the seed, but it didn't work.

The jdk version I use is: jdk1.8.0_151.jdk.

**Comment by msridhar** [comment]
@ligenPro any way you can try using JDK 1.5 or 1.6 to see if that makes a difference?  That would tell us if it's the library version that is the issue.
