### ISSUE TITLE
com.ibm.wala.dalvik.test: Compilation failure

### ISSUE THREAD

**Issue by Ido-Efrati** [wala/WALA#80]
[INFO] Building jar: /home/user/WALA/com.ibm.wala.cast.js.test/test.jar
[INFO] Building jar: /home/user/WALA/com.ibm.wala.dalvik/dalvik.jar
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.21.0:compile (default-compile) on project com.ibm.wala.dalvik.test: Compilation failure: Compilation failure:
[ERROR] /home/user/WALA/com.ibm.wala.dalvik.test/source/com/ibm/wala/dalvik/test/DalvikTestBase.java:[59]
[ERROR] com.android.dx.command.Main.main(new String[]{"--dex", "--output=" + f.getAbsolutePath(), jarFile});
[ERROR] ^^^^^^^^^^^
[ERROR] com.android cannot be resolved
[ERROR] 1 problem (1 error)
[ERROR] -> [Help 1]
[ERROR]

linux machine with java 1.8 and mvn 3.0.5

**Comment by msridhar** [comment]
See [this message](https://groups.google.com/d/msg/wala-sourceforge-net/cBYsfEvYVG0/Ua52dyQQU-YJ) for a fix.  Unfortunately, there's no good way for us to automatically pull in this jar.  For now, I've updated the Getting Started guide to indicate that `dx.jar` needs to get pulled in manually.  Let me know if you think any other documentation would be useful.
