### ISSUE TITLE
Design solutions to implement k-limited object sensitivity

### ISSUE THREAD

**Issue by genli9** [wala/WALA#801]
I was recently thinking about how to implement a `ContextSelector` for k-limited object sensitivity in Wala, my design is as follows, looking forward to your suggestions !

# Modification of related classes
The overall UML diagram is as follows:
- the blue ones are the original classes and will not be modified. 
- the red ones are added classes. 
- the yellow ones are modified classes based on the original

![image](https://user-images.githubusercontent.com/35886904/90909621-a1952980-e408-11ea-9403-b9b244a4d7de.png)

## Added classes
- AllocationString: Just like `CallString`, it maintains an `AllocationSite` array internally, recording the allocation sites
- HeapContextSelector：Responsible for providing `HeapContext` for the implementation classes corresponding to `AllocationSiteInNode` (eg: `NormalAllocationInNode`)
- NormalHeapContextSelector: It implements the `HeapContextSelector` interface and directly copies the `Context` corresponding to `CGNode` as the `HeapContext`, which is consistent with the existing logic
- nObjHeapContextSelector: Responsible for creating `AllocationString` as `HeapContext`
- nObjContextSelector: It implements the `ContextSelector` interface and is responsible for creating a `Context` for` CGNode`, which is `AllocationStringContext`

##  Modified classes
- AllocationSiteInNode: This class adds a new field, `HeapContext`
- AllocationSiteInNodeFactory: This class uses `HeapContextSelector` to create a `HeapContext` when creating an `AllocationSiteInNode` instance
- NormalAllocationInNode,MultiNewArrayInNode,ZeroLengthArrayInNode: Modifying the `equals()` and `hashCode()` methods, use `HeapContext` to distinguish

# Reasons not to use ReceiverInstanceContext
Now all `AllocationSiteInNodes` use the `Context` corresponding to `CGNode` as the HeapContext,  this will lead to create unlimited object sensitivity, as mentioned in the [AllocationSiteInNodeFactory](https://github.com/wala/WALA/blob/4a17844ac32a9b8ea433e258f6c5497b76de8af1/com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/AllocationSiteInNodeFactory.java) comment

# Current Progress
Most of the functions have been developed and are currently in the testing phase. If you agree with this plan, I will submit a pull request

# Other ideas
Based on k-limited object sensitivity and the paper: https://yanniss.github.io/hybrid-context-pldi13.pdf, I plan to implement UniformHybridContextSelector and SelectiveHybridContextSelector.

**Comment by msridhar** [comment]
> In fact, the effect I want to achieve is: A method context is a sequence of K allocation sites and a heap context is typically a sequence of K − 1 allocation sites, for example: 2obj + h. In order to distinguish it from the context of `CGNode`, I added HeapContext

I get it.  Is there evidence in the literature that there is an advantage to this approach as opposed to just using the same context for methods and allocation sites?  I seem to recall it may have just been an accident of history.  I'd prefer to keep the WALA code simple if this distinguishing of contexts is not necessary.

In general you can feel free to post your pull request.  I definitely want better objsens support in WALA.  But, I expect it will take some time to land, as I'd like to review carefully to make sure we are doing it right.

**Comment by msridhar** [comment]
Closed by #814

**Comment by msridhar** [comment]
Actually @ligenPro one more ask here.  Can you edit [this page](https://github.com/wala/WALA/wiki/Pointer-Analysis#built-in-policies) and document k-limited object sensitivity as a built-in policy, similar to the others?

**Comment by ligenPro** [comment]
@msridhar Ok, I will edit it later

**Comment by genli9** [comment]
@msridhar I have finished editing and added an introduction to N-CFA and N-Obj. If there is anything inappropriate, please contact me to modify it.
![image](https://user-images.githubusercontent.com/35886904/92756821-bccbd700-f3bf-11ea-88cc-4c3b15b24459.png)

**Comment by msridhar** [comment]
Thanks, @genli9!  We are all set here.
