### ISSUE TITLE
Backward slicing with the iterator as seed

### ISSUE THREAD

**Issue by malionet-sarka** [wala/WALA#810]
I did some backward slicing on the following code, but I didn't get the results I expected.

The configuration is as follows.

- Slicer.DataDependenceOptions.FULL
- Slicer.ControlDependenceOptions.NONE
- CallGraphBuilder: makeZeroOneContainerCFABuilder
- slice seed: Iterator.hasNest()
- java version: 1.8.0_211
- WALA version: 1.5.5

Slice result:
```java
public class ArraySample {
    public static void main(String[] args) {
        List<Integer> list = new ArrayList<>();
        list.add(1);
        for (Integer str : list) {
            System.out.println(str);
        }
    }
}
```

Slice result:
```
0 = {NormalReturnCaller@2194} "NORMAL_RET_CALLER:Node: < Application, LArraySample, main([Ljava/lang/String;)V > Context: Everywhere[13]13 = invokeinterface < Application, Ljava/util/Iterator, hasNext()Z > 11 @27 exception:12"
1 = {NormalStatement@2195} "NORMAL hasNext:return 9 Node: < Primordial, Ljava/util/ArrayList$Itr, hasNext()Z > Context: DelegatingContext [A=ReceiverInstanceContext<SITE_IN_NODE{< Primordial, Ljava/util/ArrayList, iterator()Ljava/util/Iterator; >:NEW <Primordial,Ljava/util/ArrayList$Itr>@0 in DelegatingContext [A=ReceiverInstanceContext<SITE_IN_NODE{< Application, LArraySample, main([Ljava/lang/String;)V >:NEW <Application,Ljava/util/ArrayList>@0 in Everywhere}>, B=Everywhere]}>, B=Everywhere]"
2 = {PhiStatement@2196} "PHI Node: < Primordial, Ljava/util/ArrayList$Itr, hasNext()Z > Context: DelegatingContext [A=ReceiverInstanceContext<SITE_IN_NODE{< Primordial, Ljava/util/ArrayList, iterator()Ljava/util/Iterator; >:NEW <Primordial,Ljava/util/ArrayList$Itr>@0 in DelegatingContext [A=ReceiverInstanceContext<SITE_IN_NODE{< Application, LArraySample, main([Ljava/lang/String;)V >:NEW <Application,Ljava/util/ArrayList>@0 in Everywhere}>, B=Everywhere]}>, B=Everywhere]:9 = phi  8,7"
3 = {NormalReturnCallee@2197} "NORMAL_RET_CALLEE:Node: < Primordial, Ljava/util/ArrayList$Itr, hasNext()Z > Context: DelegatingContext [A=ReceiverInstanceContext<SITE_IN_NODE{< Primordial, Ljava/util/ArrayList, iterator()Ljava/util/Iterator; >:NEW <Primordial,Ljava/util/ArrayList$Itr>@0 in DelegatingContext [A=ReceiverInstanceContext<SITE_IN_NODE{< Application, LArraySample, main([Ljava/lang/String;)V >:NEW <Application,Ljava/util/ArrayList>@0 in Everywhere}>, B=Everywhere]}>, B=Everywhere]"
```

The slice results I expect:
```java
List<Integer> list = new ArrayList<>();
list.add(1);
```
With this setup, I didn't get the slice results I was expecting.
However, I can get the expected result by setting ControlDependenceOption.NO_EXCEPTIONAL_EDGES.

Is this result correct?

**Comment by msridhar** [comment]
This appears to be a bug.  I am investigating

**Comment by msridhar** [comment]
Correction: in fact, we _do_ need to track control dependence to get the expected result here.  The Java code for `ArrayList$Itr.hasNext()` looks like:
```java
        public boolean hasNext() {
            return cursor != size;
        }
```
But when compiled to Java bytecode, the code turns into something like:
```java
        public boolean hasNext() {
            if (cursor != size) { 
              return true;
            } else {
              return false;
            };
        }
```
(In WALA IR, instead of two `return` statements, there is a `phi` statement defining the return value.)  So, control dependence tracking is required to discover the dependence of the `return` statements on the `cursor` and `size` fields.  I've added a test in #803 `testListIterator()` that captures this case.  It shows that with `DataDependenceOptions.FULL` and `ControlDependenceOptions.NO_INTERPROC_NO_EXCEPTION` the slice contains the expected statements.  `ControlDependenceOption.NO_EXCEPTIONAL_EDGES` will work as well.

Thanks again for the report @malionet-sarka!

**Comment by malionet-sarka** [comment]
I see... Now I understand the cause of the problem.

Thank you for the quick response @msridhar!
