### ISSUE TITLE
Build error because changing path of com.sun.jna

### ISSUE THREAD

**Issue by bowenshen** [wala/WALA#823]
I got this error when build WALA directly download from github. It's purely clean and no edit.
Error message as following:
Execution failed for task ':com.ibm.wala.ide:compileJava'.
> Could not resolve all files for configuration ':com.ibm.wala.ide:compileClasspath'.
   > Could not find any matches for com.sun.jna:com.sun.jna:[4.5.1,6.0.0) as no versions of com.sun.jna:com.sun.jna are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/sun/jna/com.sun.jna/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/sun/jna/com.sun.jna/maven-metadata.xml
     Required by:
         project :com.ibm.wala.ide > org.eclipse.platform:org.eclipse.ui.workbench:3.110.1 > org.eclipse.platform:org.eclipse.e4.ui.workbench.swt:0.14.1100 > org.eclipse.platform:org.eclipse.urischeme:1.1.100
   > Could not find any matches for com.sun.jna:com.sun.jna.platform:[4.5.1,6.0.0) as no versions of com.sun.jna:com.sun.jna.platform are available.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/sun/jna/com.sun.jna.platform/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/sun/jna/com.sun.jna.platform/maven-metadata.xml
     Required by:
         project :com.ibm.wala.ide > org.eclipse.platform:org.eclipse.ui.workbench:3.110.1 > org.eclipse.platform:org.eclipse.e4.ui.workbench.swt:0.14.1100 > org.eclipse.platform:org.eclipse.urischeme:1.1.100

My understanding:
After checking online. I found the issue was because a changed path.
https://mvnrepository.com/artifact/com.sun.jna/jna
This is the old link. But it has been moved to a new place
https://mvnrepository.com/artifact/net.java.dev.jna/jna

I believe this is the reason of version conflict of this error message.
Unfortunately, I don't know how to fix this bug. Not sure about where is the version requirement defined.

**Comment by msridhar** [comment]
Thanks for the report!  I've put up a PR that will hopefully fix this.
