### ISSUE TITLE
Why are SSAPiInstructions inserted at the end of basic blocks?

### ISSUE THREAD

**Issue by steohan** [wala/WALA#83]
Is there a reason SSAPiInstructions are inserted at the end of basic blocks?

I think it is not intuitive: Usually basic blocks have a single exit point. In case of a conditional branch, there will be pi instructions for each successor of the branch. Both pi instructions are inserted into the basic block of the branch. As a result this basic block has now two exit points.

**Comment by cos** [comment]
The SSAPiInstructions do not actually introduce new control-flow, they are only markers you can use for other analyses. What are you trying to do? If they are simply in your way, you can disable them from [SSAOptions](http://wala.sourceforge.net/javadocs/trunk/com/ibm/wala/ssa/SSAOptions.html).

**Comment by steohan** [comment]
We have two analysis, one needs the SSAPiInstructions, while the other may have a problem with them. But it is nothing we can't fix.

I just thought, that the pi instructions are inserted in the control-flow between the condition and its successors. If you "execute" the SSA form, you need to execute one of the pi-assignments, after branching. So they should introduce new control-flow, shouldn't they?

**Comment by cos** [comment]
While SSAPiInstructions do have a reference to a basic block number, they do not influence the control-flow at all, i.e., they do not introduce any branching. You can safely simply ignore them when "executing" the SSA form in some way.

**Comment by msridhar** [comment]
Closing as I don't think there's a bug here
