### ISSUE TITLE
How to use Wala to generate data flow graph？

### ISSUE THREAD

**Issue by YinHuiLin** [wala/WALA#836]
I have learned that Wala can do some data flow analysis, but how to generate a data flow graph？

**Comment by msridhar** [comment]
What is a data flow graph, exactly?  We do have the ability to generate visualizations of graphs, but I am not sure what kind of graph you need.

**Comment by RalfHerzog** [comment]
Hi @YinHuiLin. I created a [separate project for an executable java slicer](https://github.com/MethodResourcePrediction/Slicer-Examples) based on wala shrike. There are several graphs I need to consider for executable slice generation, so there might be the one you are looking for.
I do not know about a "data flow" graph but control flow (execution order) and data dependency (data flow)

**Comment by k4n5ha0** [comment]
@msridhar  @RalfHerzog 
 i think the "data flow graph" is  a picture like  http://wala.sourceforge.net/files/PLDI_WALA_Tutorial.pdf  's  "IR structure: pi nodes" part

**Comment by msridhar** [comment]
Sorry for the slow response.  I don't think we have anything inside WALA that can generate a graph like the one on that slide.  If you want a control-flow graph, or a data-dependence or control-dependence graph, we could likely help there
