### ISSUE TITLE
How to get the inital value of a final static int variable

### ISSUE THREAD

**Issue by 1wc** [wala/WALA#838]
Hello,

I want to get the inital value of a final static int variable, but I cannot find a method to do it for a staticField(instance of FieldImpl) in a IClass. Thanks!!!

**Comment by msridhar** [comment]
Hi!  I think you'll need to look through the IR in the `<clinit>` (static initializer) method of the corresponding class.  That's where the initialization code ends up after compilation to bytecode.  You'll be looking for an `SSAPutInstruction` to the relevant field.  Let us know if you need further help!  Closing for now

**Comment by 1wc** [comment]
Hello, @msridhar , Thanks for your answer!!
I read the WALA IR of the `<clinit>` in my case, but I cannot find such a `SSAPutInstruction` for those integer constants. Then I dumped the bytecode by `javap -c -verbose` and I still cannot find it. However, I found it in the Constant Pool.
```
{
  public static final java.lang.String[] tokenNames;
    descriptor: [Ljava/lang/String;
    flags: ACC_PUBLIC, ACC_STATIC, ACC_FINAL

  public static final int EOF;
    descriptor: I
    flags: ACC_PUBLIC, ACC_STATIC, ACC_FINAL
    ConstantValue: int -1

  public static final int AMPERSAND;
    descriptor: I
    flags: ACC_PUBLIC, ACC_STATIC, ACC_FINAL
    ConstantValue: int 4

  public static final int BITWISEOR;
    descriptor: I
    flags: ACC_PUBLIC, ACC_STATIC, ACC_FINAL
    ConstantValue: int 5
```
As a `public static final` integer such as `EOF` or `AMPERSAND`, how I can get the `ConstantValue` by WALA?

**Comment by msridhar** [comment]
That's interesting. I don't know if WALA exposes those values. I need to look into it.

**Comment by msridhar** [comment]
Ok, dug a bit.  It seems these values are not exposed in the WALA IR; we may want to do that someday.  In the meantime you can do the following.  When you build a `ClassHierarchy` from JVM bytecode, each `IClass` is actually a `ShrikeClass`.  Given a `ShrikeClass`:

1. Call `com.ibm.wala.classLoader.ShrikeClass#getReader()` to get a `ClassReader`.
2. Write code like this to find the `ConstantValue` attribute on the fields of interest: https://github.com/wala/WALA/blob/2191391fb80b26b87a363be7677dec50c0a8cff4/com.ibm.wala.shrike/src/main/java/com/ibm/wala/shrikeCT/ClassReader.java#L376

You'll need to identify the relevant field by name probably.  Note that the `IField` interface will expose whether a field is `static` or `final` and its type.  It just doesn't expose the value of such a field when it appears in the `ConstantValue` attribute.

Can you get something working based on that?

**Comment by 1wc** [comment]
Thanks!
I can get the ConstantValue by this way.
