### ISSUE TITLE
SSAPhiInstruction instruction-index not correctly set

### ISSUE THREAD

**Issue by akshayutture** [wala/WALA#840]
Calling the iIndex() function on an SSAPhiInstruction returns -1. 

This is problematic because without this iIndex() value, I am unable to find the correct SSAPhiInstruction which corresponds to the target of a SSAConditionalBranchInstruction.

Is this a bug or am I perhaps not using something correctly?  If it is a bug, is there any easy workaround for the same?

I can provide my analysis code and the test input if necessary.

**Comment by msridhar** [comment]
@akshayutture I am deeply sorry for my slow response.  `SSAPhiInstruction`s are not stored in the instruction array.  There is some documentation on this here:

https://github.com/wala/WALA/wiki/Intermediate-Representation-(IR)#phi-statements

This response is way too late, but I hope it is still helpful.  Sorry again.

I am going to close this out, but feel free to re-open if needed.

**Comment by akshayutture** [comment]
Thank you! The documentation link was quite helpful.
