### ISSUE TITLE
How to get TypeSignature?

### ISSUE THREAD

**Issue by HaofLi** [wala/WALA#856]
I can get TypeSignature of a field by following command: TypeSignature sig = ((FieldImpl) field).getGenericSignature();

If I wanna get TypeSignature of a local value, how should I do?

**Comment by msridhar** [comment]
@HaofLi sorry for the slow response.  Do you mean the type of a local variable?  I don't think that is preserved in the WALA bytecode frontend.  You might have to parse the source code to get that info.

**Comment by msridhar** [comment]
Closing out some older issues with no follow-up in a while, but please re-open if there is still an issue
