### ISSUE TITLE
con't Importing WALA Projects Into Eclipse in windows

### ISSUE THREAD

**Issue by qikahh** [wala/WALA#861]
When I imported Wala with "Existing Gradle Project", there were 178 errors, including:
 'source.target/dependency/com.ibm.wala.cast.jar' build entry is missing	
 Package 'com.ibm.wala.analysis.arraybounds' does not exist in this plug-in	
 OPTIMISTIC cannot be resolved to a variable
 build.properties does not exist	com.ibm.wala.shrike		Unknown	Plug-in Problem

I am a novice, what is the problem?
[errors.txt](https://github.com/wala/WALA/files/5983021/errors.txt)

**Comment by msridhar** [comment]
@qikahh for a novice, I would suggest starting with WALA-start rather than trying to build WALA from source:

https://github.com/wala/WALA-start

Can you get that one working?

**Comment by msridhar** [comment]
Closing out some older issues with no follow-up in a while, but please re-open if there is still an issue
