### ISSUE TITLE
Dataflow analysis of Javascript code

### ISSUE THREAD

**Issue by eleumasc** [wala/WALA#869]
Hi,
I am trying out some dataflow analysis of Javascript code.

First, I tried to run [this example](https://github.com/wala/Examples/blob/master/TaintExamples/source/tutorial/examples/CreateSDGForJavaScript.java). It finds the source and the sink, but then it doesn't find any path between the corresponding CGNodes. The tested code is the following (without some basic HTML code):
```js
var x = document.URL;
document.write(x);
```

Then, I tried to run [this analysis](https://github.com/wala/WALA-start/blob/master/src/main/java/com/ibm/wala/examples/analysis/dataflow/ContextSensitiveReachingDefs.java) on a CG computed from the following code:
```js
var a, b;
a = 2;
a = 3;
b = 4;
document.write(a + b);
```
The analysis produces some results, but I am not able to understand them (I am a newbie, I have just learned what is the tabulation algorithm) and I don't know if such analysis is good, since [it is used for analysis of Java code](https://github.com/wala/WALA-start/blob/master/src/main/java/com/ibm/wala/examples/drivers/CSReachingDefsDriver.java).

Could you provide some suggestions or examples of dataflow analysis of Javascript code (e.g. reaching definitions)?

Thank you in advance.

**Comment by msridhar** [comment]
@eleumasc thanks for your questions.  @juliandolby could you give any further guidance regarding the examples you wrote for the PLDI'16 tutorial?  I'm not too familiar with how they work.

Regarding examples of doing dataflow analysis on JavaScript code, the key difference with analyzing Java is that the JavaScript IR looks very different.  In particular, treatment of lexical variables in a reaching defs analysis would require some extra thinking.

Is there a particular analysis you are interesting in running?  If you let us know, I can try to see what might be the best example that is close to that analysis.

**Comment by eleumasc** [comment]
Thanks for the reply.

Please, can I have a simple example of taint analysis of Javascript? For example, we define that a variable is tainted if it has been assigned a user-supplied value (e.g. the value attribute of an input element) or the result of an expression which depends on a tainted variable (e.g. if x is tainted, then the statement `y=2*x+1;` makes y tainted).

Another question: is it "mandatory" to use the tabulation algorithm (in every case, I think it is a great approach) in order to solve this kind of problem with WALA or are there other strategies?

**Comment by msridhar** [comment]
@eleumasc the example you linked before does have a very simple example of tracking tainting:

https://github.com/wala/Examples/blob/master/TaintExamples/source/tutorial/examples/Analysis.java

This is not based on tabulation but instead uses an SDG.  It does not tract indirect taint (the `y=2*x+1` example you wrote) and it is context-insensitive for procedure calls.

To do what you suggest, I would suggest writing a dataflow analysis using the tabulation algorithm.  We do actually have an example of such an analysis for Android, in the com.ibm.wala.scandroid project:

https://github.com/wala/WALA/tree/master/com.ibm.wala.scandroid/src/main/java/org/scandroid

Unfortunately, there is very little documentation for the code, and no regression tests I can see.  This tech report describes the analysis:

https://www.cs.umd.edu/~avik/papers/scandroidascaa.pdf

If you understand the basics of tabulation (by understanding the ContextSensitiveReachingDefs example and looking at the [tutorial slides](http://wala.sourceforge.net/files/PLDI_WALA_Tutorial.pdf) on tabulation), I'll bet you could load up the Scandroid code in an IDE and get an idea of how it works.

Hope that helps!

**Comment by msridhar** [comment]
Closing but if you have more questions let us know
