### ISSUE TITLE
WALA installation error

### ISSUE THREAD

**Issue by mhmughees** [wala/WALA#87]
I am new to wala. Trying to configure it by following steps given at wala: gettingstarted. 

However, I have to face errors on each example I am trying to run. Please look at following errors:

1- Example  SWTTypeHierarchy 
 PANIC: roots.size()=0

2- Example PDFTypeHierarchy
spawning process [C:/Program Files (x86)/Graphviz2.38/bin/dot.exe, -Tpdf, -o, D:\WALAOut\th.pdf, -v, D:\WALAOut\temp.dt] process terminated with exit code 0 read 919 bytes from error stream

3- Js frontend com.ibm.wala.cast.js.rhino.test-JUnit
I am not able to use launcher instead when I open it following error is there
" [JRE]: Unknown JRE type specified: org.eclipse.jdt.internal.launching.macosx.MacOSXType"

I am not sure which step went wrong which have completely damage the execution. Please help

**Comment by msridhar** [comment]
Can you successfully build the code using Maven, as described [here](http://wala.sourceforge.net/wiki/index.php/UserGuide:Getting_Started#Building_the_code)?  If so, does this command succeed?

    mvn clean verify -B -q

If both of those succeed, the code is building and running fine; so it's an issue with the launchers.  I pushed a fix for issue 3 above.

**Comment by msridhar** [comment]
Going to close this one out assuming it got fixed.  If not, please re-open.
