### ISSUE TITLE
Resolve Inherited Interface Method in Interface

### ISSUE THREAD

**Issue by Myse1f** [wala/WALA#871]
```java
public interface InterA {
    funcA();
}

public interface InterB extends InterA {
    funB();
}
```
When I try to resolve `IterB.funA` inherited from `InterA` by calling `cha.resolveMethod(InterB.funA())`, WALA returns null.

I think it should return the `IMethod` refer to `InterA.funA()`. Did I get it wrong?

**Comment by msridhar** [comment]
Hi @Myse1f the method does not work the way that you expect.  `ClassHierarchy.resolveMethod()` requires that the declaring `IClass` represents a _class_, not an interface.  I think you would need to code up the lookup that you need on your own (it shouldn't be too hard).  I've opened #872 to fix the Javadoc.  Thanks for the report!
