### ISSUE TITLE
How to install this wala on pycharm

### ISSUE THREAD

**Issue by gjamesli2126** [wala/WALA#875]
![image](https://user-images.githubusercontent.com/46471838/111465733-661fcb00-875d-11eb-80dd-3a9388a74096.png)
The image above is the last step in the [wala guidance](https://wala.github.io/IDE/pycharm/)
However, what should I put in the extension box?
Could someone screen record how they install this plugin? (Assuming we got the latest Pycharm & LSP installed properly)

Thank you so much!!

**Comment by msridhar** [comment]
I think you probably meant to report this on wala/ML, so I'm going to close this one.  If I'm mistaken please re-open

**Comment by gjamesli2126** [comment]
Thank you!
Yeah, this should be in wala/ML. But just wonder no people get the same problem?
