### ISSUE TITLE
about invokeinterface in callgraph

### ISSUE THREAD

**Issue by ox1234** [wala/WALA#879]
when i generate a callgraph, find the invokeinterface method is not one CGNode in call graph.Is there any answer to add it in call graph? I need a full callgraph to do taint analysis

**Comment by ox1234** [comment]
and i use a methodselector to build cg, but it seems not work

```java
private CallGraph buildCG(Set<IMethod> entryMethod) throws Exception{
        Iterable<Entrypoint> entrypointIterator = Utils.getDefaultEntryPoints(entryMethod);
        AnalysisOptions options = new AnalysisOptions(GlobalConfig.scope, entrypointIterator);
        MethodTargetSelector methodTargetSelector = new ClassHierarchyMethodTargetSelector(GlobalConfig.classHierarchy);
        options.setSelector(methodTargetSelector);
        CallGraphBuilder builder = Util.makeZeroCFABuilder(
                new JavaLanguage(),
                options,
                new AnalysisCacheImpl(),
                GlobalConfig.classHierarchy,
                GlobalConfig.scope
        );
        CallGraph callGraph = builder.makeCallGraph(options, null);
        return callGraph;
    }
```

**Comment by msridhar** [comment]
Sorry for the slow response here.  I would certainly expect a 0-CFA builder to include targets for call sites using invokeinterface.  We have lots of tests for this.  Do you have a self-contained example where it is not working?  If you can create an example where I can build the call graph using [`ScopeFileCallGraph`](https://github.com/wala/WALA-start/blob/master/src/main/java/com/ibm/wala/examples/drivers/ScopeFileCallGraph.java) I will take a look.

**Comment by msridhar** [comment]
Closing but if you have an example please re-open
