### ISSUE TITLE
Missing object type for List??

### ISSUE THREAD

**Issue by leason805** [wala/WALA#885]
I tried to get return type for a method, which returning value like List <User> , but i found it just return a class type as java.util.List, without the object type in the list, demo as below:
My class and method:

```java
public class UserService {

    public List<User> list(){
       ......
   }

}
```

**Use ClassHierarchy to analyse the class and method:**
```java
  File exFile=new FileProvider().getFile("Exclusions.txt");
  AnalysisScope scope = AnalysisScopeReader.makeJavaBinaryAnalysisScope("my.jar", exFile);
  ClassHierarchy cha = ClassHierarchyFactory.make(scope);
  for(IClass klass : cha) {
       for(IMethod method : klass.getDeclaredMethods()) {
                //here i can only get java.util.List, not List<User>, looks no way to get the User type??
                System.out.println(method.getReturnType());
   }
```

**Comment by juliandolby** [comment]
That is the semantics of types at runtime in Java: there is only List, and
the element type is erased.

Sometimes Java compilers leave annotations in bytecode that say what the
type parameters were.  Do you see any such annotations in your bytecode?

-- Julian

**Comment by msridhar** [comment]
Looks like there is some code in Shrike for pulling out the type signature of a method, including generics:

https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.core/src/main/java/com/ibm/wala/classLoader/ShrikeCTMethod.java#L414-L417

Not quite sure how this is threaded through the rest of WALA but it's a start.

**Comment by msridhar** [comment]
Going to close this out but if you have a follow-up question let us know, thanks!

**Comment by sohah** [comment]
Thanks for this issue and the Shrike snippet. That method works to pull out the specific type, but I am also interested in having the TypeInference use it so that type information can propagate. Is this supported in Wala? Is there a way to obtain that? Thanks!
