### ISSUE TITLE
Proposal: add tests for Java 9+ JVM bytecode features

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#902]
We'd like to add / test WALA support for some JVM bytecode features added since Java 8.  This post gives a good overview of changes to JVML up through Java 12:

https://jakewharton.com/androids-java-9-10-11-and-12-support/

The features of interest (impacting bytecodes) are:

* Private interface methods
* Nestmates
* String concatenation via `invokedynamic`

To test support for these features, ideally we should be able to write JDK 9+ source code that compiles to bytecodes using the features of interest, and then run those bytecodes through WALA.  However, I think we should preserve being able to develop and test WALA as much as possible on Java 8, particularly since not all of the WALA builds and tests currently work on JDK 11 (another issue it would be good to solve, but separate from this one).

I propose the following approach:
* create another source set for JDK 9+ test inputs in com.ibm.wala.core.  Let's call it `testSubjects11` for now.
* set up config for `testSubjects11` in wala.core's build.gradle similar to how the `testSubjects` folder is handled, but all executed conditionally so `testSubjects11` only gets compiled if the JVM used for building is Java 11+.
* Write tests for these new features in a new sub-package under `com.ibm.wala.core/src/tests/java`, and only run those tests if the JVM used for building is Java 11+.

@juliandolby @liblit would appreciate your thoughts on this approach.

**Comment by liblit** [comment]
This sounds like a fine plan to me!

**Comment by msridhar** [comment]
These tests are now added and we have a mechanism for adding more, in the `com.ibm.wala.core.java11` module
