### ISSUE TITLE
One NPE in CAstPrinter.java

### ISSUE THREAD

**Issue by containerAnalyzer** [wala/WALA#903]
Hello,
Our static analyzer found a following potential NPE. We have checked the feasibility of this execution trace. It is necessary to defend this vulnerability to improve the code quality.

1. Return null to caller (Trace staring point)
https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java#L3785

2. Function visit executes and returns
https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java#L274

3. Function add executes and declEntities constains null value
https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java#L274

4. Function next executes and stores the return value to d (d can be null)
https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java#L278

5. d is used as the 1st parameter in function printTo (d can be null)
https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.cast.java.ecj/src/main/java/com/ibm/wala/cast/java/translator/jdt/JDTJava2CAstTranslator.java#L279

6. e is used as the 1st parameter in function doPrintTo (e can be null)
https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/util/CAstPrinter.java#L350

7. e is passed as the this pointer to function getKind (e can be null), which will leak to null pointer dereference
https://github.com/wala/WALA/blob/ac4772eb372493f4c61afd3513418a3a8e975872/com.ibm.wala.cast/src/main/java/com/ibm/wala/cast/util/CAstPrinter.java#L355

Commit: ac4772eb372493f4c61afd3513418a3a8e975872

ContainerAnalyzer

**Comment by msridhar** [comment]
This is a false positive. Before the first line linked there is an assertion that makes the `return null` unreachable.

Was this checked by a human before opening the issue? If so, proper contact information should be provided. If not, please don't automatically open issues on open source repos that might be false positives. It is a burden on maintainers to look at these issues. The text of the issue makes it sound like this is a verified bug but it is not.

Also the issue text has a bunch of grammatical errors.
