### ISSUE TITLE
how to analysis codes with a uninitialized field

### ISSUE THREAD

**Issue by sunxch** [wala/WALA#928]
i want to analysis a project under spring-framework. there are so many fields initialized by the framework.
but the wala seems doesnt  identify the method calls.

i have tried every Builder(8 in total) declared in `com.ibm.wala.ipa.callgraph.impl.Util`, but none is working

the sample code here
```
public class Test {
    /** initialized by framework */
    TestTool testTool;

    public void test() {
        testTool.commonMethod(); // not in call graph
    }
}
```
```
public class TestTool {
    public void commonMethod() {
        System.out.println("hello");
    }
}
```

**Comment by msridhar** [comment]
@sunxch I'm going to close this out.  If you are still interested in the extra features for `CHACallGraph` please open a new issue or just send a PR!
