### ISSUE TITLE
Can't Build WALA 1.5.7 Using Gradle Anymore

### ISSUE THREAD

**Issue by greenerpilotx** [wala/WALA#948]
Hello,

I was previously able to build Wala (1.5.7 SNAPSHOT) with no problem. I need to rebuild to add some changes. However, when I re-downloaded the latest version and built using the included gradlew script, I got many errors. I am using OpenJDK 8. 

I run:
`./gradlew build -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home`

And this is the output:

`> Task :com.ibm.wala.ide.jsdt:compileJava FAILED
...
> Task :com.ibm.wala.core:compileJavaUsingEcj
----------
1. WARNING in /Users/Desktop/WalaHelp/Latest/WALA-master/com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/summaries/LambdaMethodTargetSelector.java (at line 154)
        private static boolean isNonClinitLambdaMetafactoryMethod(
      IClassHierarchy cha, MethodReference target) {
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The method isNonClinitLambdaMetafactoryMethod(IClassHierarchy, MethodReference) from the type LambdaMethodTargetSelector is never used locally
----------
----------
2. WARNING in /Users/Desktop/WalaHelp/Latest/WALA-master/com.ibm.wala.core/src/main/java/com/ibm/wala/ipa/callgraph/propagation/PropagationSystem.java (at line 112)
        if (PointsToSetVariable.PARANOID || PointsToSetVariable.VERBOSE_PRINT) {
      PointsToSetVariable.instanceKeys = instanceKeys;
    }
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dead code
----------
----------
3. INFO in /Users/Desktop/WalaHelp/Latest/WALA-master/com.ibm.wala.core/src/main/java/com/ibm/wala/core/util/config/AnalysisScopeReader.java (at line 185)
        @SuppressWarnings("unused")
                          ^^^^^^^^
At least one of the problems in category 'unused' is not analysed due to a compiler option being ignored
----------
----------
4. INFO in /Users/Desktop/WalaHelp/Latest/WALA-master/com.ibm.wala.core/src/main/java/com/ibm/wala/examples/analysis/dataflow/ContextInsensitiveReachingDefs.java (at line 106)
        @SuppressWarnings({"rawtypes", "unchecked"})
                           ^^^^^^^^^^
At least one of the problems in category 'rawtypes' is not analysed due to a compiler option being ignored
----------
4 problems (0 errors, 2 warnings, 2 info)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.ibm.wala.ide.jsdt:compileJava'.
> Could not resolve all files for configuration ':com.ibm.wala.ide.jsdt:compileClasspath'.
   > Did not resolve 'org.eclipse.wst.jsdt:core:1.0.201.v2010012803' which is part of the dependency lock state
   > Did not resolve 'org.eclipse.wst.jsdt:ui:1.0.201.v2010012803' which is part of the dependency lock state
   > Could not resolve org.eclipse.wst.jsdt:core:1.0.201.v2010012803.
     Required by:
         project :com.ibm.wala.ide.jsdt
      > Could not resolve org.eclipse.wst.jsdt:core:1.0.201.v2010012803.
         > Could not get resource 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/core/1.0.201.v2010012803/core-1.0.201.v2010012803.pom'.
            > Could not GET 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/core/1.0.201.v2010012803/core-1.0.201.v2010012803.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.eclipse.wst.jsdt:ui:1.0.201.v2010012803.
     Required by:
         project :com.ibm.wala.ide.jsdt
      > Could not resolve org.eclipse.wst.jsdt:ui:1.0.201.v2010012803.
         > Could not get resource 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/ui/1.0.201.v2010012803/ui-1.0.201.v2010012803.pom'.
            > Could not GET 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/ui/1.0.201.v2010012803/ui-1.0.201.v2010012803.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.eclipse.wst.jsdt:core:1.0.201.v2010012803.
     Required by:
         project :com.ibm.wala.ide.jsdt
      > Could not resolve org.eclipse.wst.jsdt:core:1.0.201.v2010012803.
         > Could not get resource 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/core/1.0.201.v2010012803/core-1.0.201.v2010012803.pom'.
            > Could not GET 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/core/1.0.201.v2010012803/core-1.0.201.v2010012803.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
   > Could not resolve org.eclipse.wst.jsdt:ui:1.0.201.v2010012803.
     Required by:
         project :com.ibm.wala.ide.jsdt
      > Could not resolve org.eclipse.wst.jsdt:ui:1.0.201.v2010012803.
         > Could not get resource 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/ui/1.0.201.v2010012803/ui-1.0.201.v2010012803.pom'.
            > Could not GET 'https://artifacts.alfresco.com/nexus/content/repositories/public/org/eclipse/wst/jsdt/ui/1.0.201.v2010012803/ui-1.0.201.v2010012803.pom'.
               > The server may not support the client's requested TLS protocol versions: (TLSv1.2, TLSv1.3). You may need to configure the client to allow other protocols to be used. See: https://docs.gradle.org/7.2/userguide/build_environment.html#gradle_system_properties
                  > PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

`

**Comment by msridhar** [comment]
I think we just fixed this on WALA master 🙂 See #944 Can you give the latest master branch a shot?

**Comment by msridhar** [comment]
If you need to build an older version, this is the key change to get things working again:

https://github.com/wala/WALA/pull/944/files#diff-7f825392aa37acd1cee0c2e7b9bb7366ad6eac64f3e6cdd816e156bcb69d30deL21-L22

**Comment by greenerpilotx** [comment]
Able to build now with no issues! Thanks so much.
