### ISSUE TITLE
Inaccurate source code location information

### ISSUE THREAD

**Issue by Anditty** [wala/WALA#957]
There is a problem with the display of the line numbers of those lines of code enclosed in branch statements.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/71593976/132318505-e0ff4577-c9ad-477a-a037-151505e53741.png">
for example
the SSAinstruction  invokevirtual < Application, Ljava/lang/String, length()I >  should in the line12, but the result wala give is line10:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/71593976/132318722-887979c4-ae5f-44aa-bf4a-57e07b2a3790.png">

**Comment by Anditty** [comment]
I use getSourcePosition() in the ShrikeBTMethod to get the result:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/71593976/132318978-8ff78750-8906-4b0d-8bef-da87b794c5f3.png">

**Comment by msridhar** [comment]
AFAIK, WALA just pulls source position info from the `.class` files, so I'm not sure what could be going on here.  Any way you could post your full code snippet?

**Comment by Anditty** [comment]
sure,
```java
public static void main(String[] args) throws IOException, ClassHierarchyException, IllegalArgumentException,
            CancelException, InvalidClassFileException, CancelException {
        long start = System.currentTimeMillis();
        String scopeFile = "src/main/resources/scope.txt";
        AnalysisScope scope = AnalysisScopeReader.readJavaScope(scopeFile, null, com.ibm.wala.examples.drivers.ScopeFileCallGraph.class.getClassLoader());
        ExcludeUtils.addDefaultExclusions(scope);
        IClassHierarchy cha = ClassHierarchyFactory.makeWithRoot(scope);
        System.out.println(cha.getNumberOfClasses() + " classes");
        System.out.println(Warnings.asString());
        Warnings.clear();
        Iterable<Entrypoint> entrypoints = new AllApplicationEntrypoints(scope, cha);
        AnalysisOptions options = new AnalysisOptions(scope,entrypoints);
        AnalysisCache cache = new AnalysisCacheImpl();
        CHACallGraph cg = new KwaiCallGraph(cha);
        cg.init(entrypoints);
        System.out.println("building call graph...");
        int i=0;
        LifeCycle.init(cg);

        for(CGNode node: cg) {
            if (node.getIR() == null){
                continue;
            }
            if(node.getMethod() instanceof ShrikeBTMethod) {
                ShrikeBTMethod method = (ShrikeBTMethod) node.getMethod();
                if("Application".equals(method.getDeclaringClass().getClassLoader().toString())) {               
                    for(SSAInstruction ins:node.getIR().getInstructions()){
                        if(ins==null) continue;
                        System.out.println(ins+":"+node.getMethod().getSourcePosition(ins.iIndex()));
                    }
                }
            }
        }
        long end = System.currentTimeMillis();
        System.out.println("done");
        System.out.println("took " + (end-start) + "ms");
        System.out.println(CallGraphStats.getStats(cg));
    }
```

and  the benchmark is :
```java
public class benchmark {
   public void initXXX(People people) {
        if (people.self().getS() != null) {
         
            System.out.println(people.self().getS().length());
        }
       
    }
}
```

**Comment by msridhar** [comment]
I think I see the problem.  You are using the SSA instruction index to look up the line number, but you need to use the bytecode index, which may be different.  Here is sample code for getting a line number:

https://github.com/wala/WALA/wiki/Mapping-to-source-code#from-ir-instruction-to-bytecode-index--source-line-number

(`getSourcePosition()` will basically give you the same info, as there are no column numbers in Java bytecode.)  Basically, you need to call `method.getBytecodeIndex()` to convert the WALA IR index into a bytecode index.  Can you try that and see if it fixes the issue?

**Comment by msridhar** [comment]
I'm going to go ahead and close as I'm pretty sure that's the issue.  If it's something else you can reopen.

**Comment by Anditty** [comment]
Thank you so much, it really works, thank you very, very much!！！！！！！！！！！！！！！！！！

**Comment by msridhar** [comment]
You're welcome!
