### ISSUE TITLE
`lintGradle` task depends on `compileJavaUsingEcj` tasks

### ISSUE THREAD

**Issue by msridhar** [wala/WALA#964]
If I run `./gradlew lintGradle taskTree` I see:

```
:lintGradle
+--- :com.ibm.wala.cast:compileJava
|    +--- :com.ibm.wala.core:compileJava
|    |    +--- :com.ibm.wala.shrike:compileJava
|    |    |    \--- :com.ibm.wala.util:compileJava
|    |    \--- :com.ibm.wala.util:compileJava *
|    +--- :com.ibm.wala.shrike:compileJava *
|    \--- :com.ibm.wala.util:compileJava *
+--- :com.ibm.wala.cast:compileJavaUsingEcj
|    +--- :com.ibm.wala.core:compileJava *
|    +--- :com.ibm.wala.shrike:compileJava *
|    \--- :com.ibm.wala.util:compileJava *
...
```

I don't think there needs to be a dependence on `compileJavaUsingEcj` tasks, and these dependencies make it take longer to run `lintGradle` locally.  @liblit is this easy to fix?

**Comment by liblit** [comment]
Not easy to fix, but perhaps easy to work around when needed. These dependencies are established [here, down inside the Gradle linter plugin's own code](https://github.com/nebula-plugins/gradle-lint-plugin/blob/2d94688f812b2c513e0b92df9c9b5006bcb68009/src/main/groovy/com/netflix/nebula/lint/plugin/GradleLintPluginTaskConfigurer.groovy#L58-L63). Our `compileJavaUsingEcj` tasks are instances of a subclass of `AbstractCompile`, so they are included in the arguments to this `dependsOn` call.

That being said, you can already suppress ECJ compilation entirely, and that affects `lintGradle` too:

```shell
./gradlew lintGradle -PskipJavaUsingEcjTasks
```

Is that satisfactory for your needs, @msridhar?

**Comment by msridhar** [comment]
Hi @liblit, that is definitely helpful, thanks!  I guess that's the best we can do for now.  Will close this out as I don't see an obvious way to fix this in the near-term.
