### ISSUE TITLE
some class can't be found by use binaryDir option

### ISSUE THREAD

**Issue by Anditty** [wala/WALA#966]
Sorry to bother you again! I'm using wala and I'm trying to add the whole compiled folder to the scope file, but some kt compiled files in dir:"tmp/kotlin-classes" are not found by wala, only when I add tmp/kotlin-classes to the scope file manually can I solve this problem. Is there any other way to avoid this problem? Or how should I go about modifying wala to achieve this?

**Comment by msridhar** [comment]
`binaryDir` assumes the sub-directories of the given directory correspond to the package structure in the code.  E.g., if you have a class `com.foo.Bar`, the `Bar.class` file should be in the `com/foo` sub-directory of whatever you give as the `binaryDir`.  So in your case, I think you have to specify `tmp/kotlin-classes` as another `binaryDir` in the scope file.

If that doesn't make sense, please post a more complete example to illustrate the problem.

**Comment by msridhar** [comment]
@Anditty can I close this out?

**Comment by Anditty** [comment]
sure thanks for your answer！
