### ISSUE TITLE
maven build error

### ISSUE THREAD

**Issue by xuzhao9** [wala/WALA#97]
Hello all,
I am new to Wala. The version I am using is just git clone this repository.
I tried to build wala using the following command:
mvn clean verify -DskipTests=true -q
Here is the error I get:
[ERROR] WALA/com.ibm.wala.dalvik.test/source/com/ibm/wala/dalvik/test/util/Util.java:[62]
[ERROR] com.android.dx.command.Main.main(new String[]{"--dex", "--output=" + f.getAbsolutePath(), jarFile});

[ERROR] com.android cannot be resolved

Any ideas?
Should I add android dependency in pom.xml? If so, how should I do?

**Comment by msridhar** [comment]
You need to grab dx.jar from the Android SDK and stick it in the com.ibm.wala.dalvik.test/lib folder; see [here](http://wala.sourceforge.net/wiki/index.php/UserGuide:Getting_Started#Building_the_code).  Unfortunately, we cannot easily automate downloading of this jar.
