### ISSUE TITLE
Eclipse Mars build failure for FakeExceptionTypeBinding

### ISSUE THREAD

**Issue by liblit** [wala/WALA#98]
Class `com.ibm.wala.cast.java.translator.jdt.FakeExceptionTypeBinding` fails to build under Eclipse Mars (4.5.2). One error is reported for line 58 of `com.ibm.wala.ide.jdt/source/com/ibm/wala/cast/java/translator/jdt/FakeExceptionTypeBinding.java`: `The type FakeExceptionTypeBinding must implement the inherited abstract method ITypeBinding.getDeclaringMember()`.

`ITypeBinding` here refers to `org.eclipse.jdt.core.dom/ITypeBinding`, which presumably added this `getDeclaringMember()` method in recent Eclipse releases.

This is similar to issue #56, although in that case it was Eclipse Luna that had problems.

**Comment by msridhar** [comment]
Thanks for the report!
