### ISSUE TITLE
why there  two basic block?

### ISSUE THREAD

**Issue by Anditty** [wala/WALA#985]
```java
public class test {
    static String a="";
    public static void main(String[] args) {
       a.length();
       a.length();
    }
}
```
<img width="810" alt="image" src="https://user-images.githubusercontent.com/71593976/133807804-2ff274da-328c-40a7-a144-aa5664bb981e.png">

In my understanding of basicblock, these two uses of variable `a` should be in one basicblock, wondering why wala would split them into two basicblocks?

**Comment by msridhar** [comment]
This is because `a.length()` may throw an exception, so the first call may transition to the exceptional return or the second call.

**Comment by Anditty** [comment]
```java
public class test {
    public static void main(String[] args) {
        student s=new student();
        int t=s.x;
        int c=s.x;
    }
}
```
<img width="848" alt="image" src="https://user-images.githubusercontent.com/71593976/133824219-844c696f-e796-4ea8-8b96-26fdf6516728.png">
For `getfield` without exception, why this time still split them into two basicblocks?

**Comment by msridhar** [comment]
getfield can throw NullPoinetException. WALA CFG doesnt try to prove it
can’t happen in this case
